// @generated by OntOS Codesmith Resource v1
// @ontos-resource-owner siampark.work
// @ontos-resource-slug task
import type { OntosResourceType } from '@app/core-runtime';
import { Schema } from 'effect';

const ResourceIdSchema = Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(300)).pipe(
  Schema.brand('siampark.work.task.ResourceId'),
);
const TenantIdSchema = Schema.String.check(Schema.isUUID()).pipe(Schema.brand('TenantId'));

export const TaskRefSchema = Schema.Struct({
  moduleId: Schema.Literal('siampark.work'),
  resourceId: ResourceIdSchema,
  resourceType: Schema.Literal('siampark.work.task'),
  tenantId: TenantIdSchema,
});
export type TaskRef = typeof TaskRefSchema.Type;

export const taskResourceDescriptor = {
  capabilities: {
    graphVisible: false,
    linkable: false,
    mediaAttachable: false,
    searchable: false,
    timelineVisible: false,
  },
  description: 'Task resource.',
  key: 'siampark.work.task',
  label: 'Task',
  owningModuleId: 'siampark.work',
} as const satisfies OntosResourceType;
