// @generated by OntOS Codesmith Resource v1
// @ontos-resource-owner siampark.work
// @ontos-resource-slug task-collection
import type { OntosResourceType } from '@app/core-runtime';
import { Schema } from 'effect';

const ResourceIdSchema = Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(300)).pipe(
  Schema.brand('siampark.work.task-collection.ResourceId'),
);
const TenantIdSchema = Schema.String.check(Schema.isUUID()).pipe(Schema.brand('TenantId'));

export const TaskCollectionRefSchema = Schema.Struct({
  moduleId: Schema.Literal('siampark.work'),
  resourceId: ResourceIdSchema,
  resourceType: Schema.Literal('siampark.work.task-collection'),
  tenantId: TenantIdSchema,
});
export type TaskCollectionRef = typeof TaskCollectionRefSchema.Type;

export const taskCollectionResourceDescriptor = {
  capabilities: {
    graphVisible: false,
    linkable: false,
    mediaAttachable: false,
    searchable: false,
    timelineVisible: false,
  },
  description: 'Task Collection resource.',
  key: 'siampark.work.task-collection',
  label: 'Task Collection',
  owningModuleId: 'siampark.work',
} as const satisfies OntosResourceType;
