// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner siampark.billing-finance
// @ontos-action-http-slug apply-command
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted, Schema } from 'effect';
import { ApplyCommandActionApi, ApplyCommandPayloadSchema } from '../../shared/apis/apply-command-action.ts';
import type { ApplyCommandPayload } from '../../shared/actions/apply-command.ts';
import { operationGateway } from './action-gateway.ts';

const traceIdOption = 'traceId' as const;

export interface ApplyCommandActionClientOptions {
  readonly baseUrl?: string | URL;
  readonly compositionRevision?: string;
  readonly gateway?: Parameters<typeof operationGateway.invoke>[1];
  readonly idempotencyKey: string;
  readonly referenceCredentials?: Redacted.Redacted;
  readonly [traceIdOption]?: string;
}

type AuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options: ApplyCommandActionClientOptions,
];
type OperationInvocation = readonly [requestCorrelation: string, options: ApplyCommandActionClientOptions];

interface MakeClientOptions {
  readonly credential: Redacted.Redacted;
  readonly options: ApplyCommandActionClientOptions;
  readonly requestCorrelation: string;
}

const makeClient = ({ credential, options, requestCorrelation }: MakeClientOptions) =>
  makeGovernedEffectBffClient(
    {
      api: ApplyCommandActionApi,
      credential,
      defaultApiPrefix: '/siampark-billing-finance-api',
      idempotencyKey: options.idempotencyKey,
      requestCorrelation,
    },
    options,
  );

export const executeApplyCommandWithAuthorization = (
  payload: ApplyCommandPayload,
  ...[credential, requestCorrelation, options]: AuthorizedInvocation
) =>
  Schema.encodeUnknownEffect(ApplyCommandPayloadSchema)(payload).pipe(
    Effect.flatMap((encoded) =>
      makeClient({ credential: Redacted.make(credential), options, requestCorrelation }).pipe(
        Effect.flatMap((client) => client.applyCommandAction.execute({ payload: encoded })),
      ),
    ),
  );

export const executeApplyCommand = (
  payload: ApplyCommandPayload,
  ...[requestCorrelation, options]: OperationInvocation
) =>
  operationGateway.invoke(
    (credential, { apiBaseUrl, compositionRevision }) =>
      executeApplyCommandWithAuthorization(payload, credential, requestCorrelation, {
        ...options,
        baseUrl: apiBaseUrl,
        compositionRevision,
      }),
    options.gateway,
  );
