// @generated by OntOS Codesmith module-api v1
import {
  OperationContextUnavailable,
  ReadHandlerUnavailable,
  defineRead,
  defineTenantModuleEntrypoint,
} from '@app/core-runtime';
import { ActionPermission } from '@app/core-runtime/actions/runtime-wiring';
import { Effect } from 'effect';
import type { OperationalScope, ReadHandlerContext, ReadServiceFactory } from '@app/core-runtime';
import { persistenceService, projectFinanceRecords } from '../services/persistence.service.ts';
import { RecordsRequestSchema, RecordsResponseSchema } from '../../shared/apis/records.ts';

type Services = Effect.Success<ReturnType<typeof persistenceService>> & { readonly canWrite: boolean };

const financeModuleKey = 'siampark.billing-finance';

const recordsEntrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: { kind: 'context_permission', permission: 'module.access' },
  entrypointKey: 'siampark.billing-finance.api.records',
  moduleKey: financeModuleKey,
  role: 'api',
});

export const financeWriteCapability = Effect.fn('Finance.writeCapability')(function* financeWriteCapability(
  scope: Pick<OperationalScope, 'principalId' | 'correlationId'>,
) {
  const permission = yield* ActionPermission;
  const decision = yield* permission
    .checkActionPermission({
      actionKey: 'siampark.billing-finance.apply-command',
      correlationId: scope.correlationId,
      principalId: scope.principalId,
    })
    .pipe(
      Effect.mapError((failure) =>
        Object.defineProperty(
          new OperationContextUnavailable({
            code: 'operation_context_unavailable',
            reason: 'Finance write permission could not be determined',
          }),
          'cause',
          { value: failure },
        ),
      ),
    );
  return decision === 'allowed';
});

const makeRecordsServices: ReadServiceFactory<Services, ActionPermission> = Effect.fn('Finance.makeRecordsServices')(
  function* makeServices(transaction, scope) {
    const persistence = yield* persistenceService(transaction, scope);
    const canWrite = yield* financeWriteCapability(scope);
    return { ...persistence, canWrite };
  },
);

export const recordsRead = defineRead(
  {
    accessKind: 'detail',
    entrypoint: recordsEntrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'siampark.billing-finance.api.records.evidence.v1',
    },
    inputSchema: RecordsRequestSchema,
    legalEntityScope: 'required',
    owningModuleKey: financeModuleKey,
    permissionTarget: 'module',
    policies: [],
    readKey: 'siampark.billing-finance.api.records',
    resultSchema: RecordsResponseSchema,
    schemaVersion: '1',
  },
  (input, context: ReadHandlerContext<Services>) =>
    context.services.load().pipe(
      Effect.mapError(
        (failure) => new ReadHandlerUnavailable({ code: 'read_handler_unavailable', reason: failure.reason }),
      ),
      Effect.map(({ revision, state }) => {
        const result = projectFinanceRecords(state, revision, input);
        return {
          evidence: { resultCount: result.state.invoices.length + result.state.financialPlanEntries.length },
          result: { ...result, canWrite: context.services.canWrite },
        };
      }),
    ),
  makeRecordsServices,
  () => ({ kind: 'module', moduleId: financeModuleKey }),
);
