// @generated by OntOS Codesmith Module Contract v1
// @ontos-deployment-app-id siampark-occupancy
// @ontos-module-id siampark.occupancy
import { defineVerticalRuntimeRegistration } from '@app/core-runtime';
import { siamparkOccupancyManifest } from './vertical.manifest.ts';
// <generated-module-registration-imports>
import { applyCommandAction } from './src/actions/apply-command.action.ts';
// </generated-module-registration-imports>

export const siamparkOccupancyRegistration = defineVerticalRuntimeRegistration({
  actions: [
    // <generated-module-registration-actions>
    applyCommandAction,
    // </generated-module-registration-actions>
  ],
  entrypoints: {
    api: {
      // <generated-module-registration-apis>
      records: () => import('./src/api/records-client.ts'),
      // </generated-module-registration-apis>
    },
    components: {
      // <generated-module-registration-components>
      // </generated-module-registration-components>
    },
    pages: {
      // <generated-module-registration-pages>
      'page-records': () => import('./src/routes/[lang]/siampark/occupancy/page.tsx'),
      // </generated-module-registration-pages>
    },
    reports: {
      // <generated-module-registration-reports>
      // </generated-module-registration-reports>
    },
    search: {
      // <generated-module-registration-search>
      // </generated-module-registration-search>
    },
  },
  manifest: siamparkOccupancyManifest,
  outboxWorkers: [
    // <generated-module-registration-workers>
    // </generated-module-registration-workers>
  ],
});

// <generated-public-component-registrations>
// </generated-public-component-registrations>
// <generated-search-registrations>
// </generated-search-registrations>
// <generated-report-registrations>
// </generated-report-registrations>
