// @generated by OntOS Codesmith module-api v1
import { ReadHandlerUnavailable, defineRead, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { Effect } from 'effect';
import type { ReadHandlerContext, ReadServiceFactory } from '@app/core-runtime';
import { persistenceService } from '../services/persistence.service.ts';
import { RecordsRequestSchema, RecordsResponseSchema } from '../../shared/apis/records.ts';

type Services = Effect.Success<ReturnType<typeof persistenceService>>;

const moduleKey = 'siampark.property';
const unavailable = (cause: unknown) => {
  const failure = new ReadHandlerUnavailable({
    code: 'read_handler_unavailable',
    reason: 'Property records are unavailable',
  });
  Object.defineProperty(failure, 'cause', { value: cause });
  return failure;
};

const recordsEntrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: { kind: 'context_permission', permission: 'module.access' },
  entrypointKey: 'siampark.property.api.records',
  moduleKey,
  role: 'api',
});

const makeRecordsServices: ReadServiceFactory<Services> = (transaction, scope) =>
  persistenceService(transaction, scope);

export const recordsRead = defineRead(
  {
    accessKind: 'detail',
    entrypoint: recordsEntrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'siampark.property.api.records.evidence.v1',
    },
    inputSchema: RecordsRequestSchema,
    legalEntityScope: 'required',
    owningModuleKey: moduleKey,
    permissionTarget: 'module',
    policies: [],
    readKey: 'siampark.property.api.records',
    resultSchema: RecordsResponseSchema,
    schemaVersion: '1',
  },
  (input, context: ReadHandlerContext<Services>) =>
    context.services.load().pipe(
      Effect.mapError(unavailable),
      Effect.map(({ revision, state }) => {
        const properties = state.properties.filter(
          (record) => input.resourceId === undefined || record.propertyRef.resourceId === input.resourceId,
        );
        const units = state.units.filter(
          (record) =>
            (input.resourceId === undefined || record.unitRef.resourceId === input.resourceId) &&
            (input.propertyId === undefined || record.propertyRef.resourceId === input.propertyId),
        );
        const assets = state.assets.filter(
          (record) =>
            (input.resourceId === undefined || record.assetRef.resourceId === input.resourceId) &&
            (input.propertyId === undefined || record.propertyRef.resourceId === input.propertyId),
        );
        return {
          evidence: { resultCount: properties.length + units.length + assets.length },
          result: { assets, properties, revision, units },
        };
      }),
    ),
  makeRecordsServices,
  () => ({ kind: 'module', moduleId: moduleKey }),
);
