// @generated by OntOS Codesmith module-api v1
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted } from 'effect';
import { RecordsApi } from '../../shared/apis/records.ts';
import type { RecordsRequest } from '../../shared/apis/records.ts';
import { operationGateway } from './action-gateway.ts';

export interface RecordsClientOptions {
  readonly baseUrl?: string | URL;
  readonly compositionRevision?: string;
}

type RecordsAuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options?: RecordsClientOptions,
];

type RecordsOperationInvocation = readonly [requestCorrelation: string, options?: RecordsClientOptions];

const recordsClient = (credential: Redacted.Redacted, requestCorrelation: string, options: RecordsClientOptions) =>
  makeGovernedEffectBffClient(
    {
      api: RecordsApi,
      credential,
      defaultApiPrefix: '/siampark-property-api',
      requestCorrelation,
    },
    options,
  );

export const executeRecordsWithAuthorization = (
  payload: RecordsRequest,
  ...[credential, requestCorrelation, options = {}]: RecordsAuthorizedInvocation
) =>
  recordsClient(Redacted.make(credential), requestCorrelation, options).pipe(
    Effect.flatMap((client) => client.records.execute({ payload })),
  );

export const executeRecords = (
  payload: RecordsRequest,
  ...[requestCorrelation, options = {}]: RecordsOperationInvocation
) =>
  operationGateway.invoke((credential, { apiBaseUrl, compositionRevision }) =>
    executeRecordsWithAuthorization(payload, credential, requestCorrelation, {
      ...options,
      baseUrl: apiBaseUrl,
      compositionRevision,
    }),
  );
