// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner siampark.property
// @ontos-action-http-slug apply-command
import { decodeActionEndpointHeaders } from '@app/core-runtime/http/action-runner';
import { Effect, HttpApiBuilder, Layer } from '@modern-js/bff-effect/effect-edge';
import type { HttpServerRequest } from 'effect/unstable/http';
import { Redacted, Schema } from 'effect';
import { siamparkPropertyApi } from '../shared/api.ts';
import { applyCommandAction } from '../src/actions/apply-command.action.ts';
import { bindActionHttpRunner } from './action-http-runner.ts';
import {
  applyCommandActionProblem,
  applyCommandActionSchemaErrorLive,
  mapApplyCommandActionProblem,
} from './apply-command-action-problems.ts';

const runActionHttp = bindActionHttpRunner({
  authentication: applyCommandActionProblem.authentication,
  unavailable: () => applyCommandActionProblem.unavailable('operation_context_unavailable'),
});

const execute = Effect.fn('ApplyCommandActionServer.execute')(function* executeApplyCommand(
  payload: typeof applyCommandAction.descriptor.payloadSchema.Encoded,
  request: HttpServerRequest.HttpServerRequest,
) {
  const correlationId = request.headers['x-correlation-id'];
  if (correlationId !== undefined && correlationId.length > 200) {
    return yield* Effect.fail(applyCommandActionProblem.invalid());
  }
  const endpointHeaders = yield* decodeActionEndpointHeaders(request.headers).pipe(
    Effect.mapError(applyCommandActionProblem.invalid),
  );
  const decoded = yield* Schema.decodeEffect(applyCommandAction.descriptor.payloadSchema)(payload).pipe(
    Effect.mapError(applyCommandActionProblem.invalid),
  );
  return yield* runActionHttp({
    endpointHeaders,
    internalProblem: applyCommandActionProblem.internal,
    invalidCorrelationProblem: applyCommandActionProblem.invalid,
    mapError: mapApplyCommandActionProblem,
    payload: decoded,
    registration: applyCommandAction,
    requestHeaders: {
      authorization: Redacted.make(request.headers['authorization']),
      'x-correlation-id': correlationId,
    },
  });
});

export const applyCommandActionApiLive = HttpApiBuilder.group(siamparkPropertyApi, 'applyCommandAction', (handlers) =>
  handlers.handle('execute', ({ payload, request }) => execute(payload, request)),
).pipe(Layer.provide(applyCommandActionSchemaErrorLive));
