// @generated by OntOS Codesmith Resource v1
// @ontos-resource-owner siampark.property
// @ontos-resource-slug asset
import type { OntosResourceType } from '@app/core-runtime';
import { Schema } from 'effect';

const ResourceIdSchema = Schema.toEncoded(Schema.String.check(Schema.isUUID()).pipe(Schema.brand('ResourceId')));
const TenantIdSchema = Schema.toEncoded(Schema.String.check(Schema.isUUID()).pipe(Schema.brand('TenantId')));

export const AssetRefSchema = Schema.Struct({
  moduleId: Schema.Literal('siampark.property'),
  resourceId: ResourceIdSchema,
  resourceType: Schema.Literal('siampark.property.asset'),
  tenantId: TenantIdSchema,
});
export type AssetRef = typeof AssetRefSchema.Type;

export const assetResourceDescriptor = {
  capabilities: {
    graphVisible: false,
    linkable: false,
    mediaAttachable: false,
    searchable: false,
    timelineVisible: false,
  },
  description: 'Asset resource.',
  key: 'siampark.property.asset',
  label: 'Asset',
  owningModuleId: 'siampark.property',
} as const satisfies OntosResourceType;
