// @generated by OntOS Codesmith Resource v1
// @ontos-resource-owner siampark.property
// @ontos-resource-slug property
import type { OntosResourceType } from '@app/core-runtime';
import { Schema } from 'effect';

const ResourceIdSchema = Schema.toEncoded(Schema.String.check(Schema.isUUID()).pipe(Schema.brand('ResourceId')));
const TenantIdSchema = Schema.toEncoded(Schema.String.check(Schema.isUUID()).pipe(Schema.brand('TenantId')));

export const PropertyRefSchema = Schema.Struct({
  moduleId: Schema.Literal('siampark.property'),
  resourceId: ResourceIdSchema,
  resourceType: Schema.Literal('siampark.property.property'),
  tenantId: TenantIdSchema,
});
export type PropertyRef = typeof PropertyRefSchema.Type;

export const propertyResourceDescriptor = {
  capabilities: {
    graphVisible: false,
    linkable: false,
    mediaAttachable: false,
    searchable: false,
    timelineVisible: false,
  },
  description: 'Property resource.',
  key: 'siampark.property.property',
  label: 'Property',
  owningModuleId: 'siampark.property',
} as const satisfies OntosResourceType;
