// @generated by OntOS Codesmith Resource v1
// @ontos-resource-owner siampark.property
// @ontos-resource-slug unit
import type { OntosResourceType } from '@app/core-runtime';
import { Schema } from 'effect';

const ResourceIdSchema = Schema.toEncoded(Schema.String.check(Schema.isUUID()).pipe(Schema.brand('ResourceId')));
const TenantIdSchema = Schema.toEncoded(Schema.String.check(Schema.isUUID()).pipe(Schema.brand('TenantId')));

export const UnitRefSchema = Schema.Struct({
  moduleId: Schema.Literal('siampark.property'),
  resourceId: ResourceIdSchema,
  resourceType: Schema.Literal('siampark.property.unit'),
  tenantId: TenantIdSchema,
});
export type UnitRef = typeof UnitRefSchema.Type;

export const unitResourceDescriptor = {
  capabilities: {
    graphVisible: false,
    linkable: false,
    mediaAttachable: false,
    searchable: false,
    timelineVisible: false,
  },
  description: 'Unit resource.',
  key: 'siampark.property.unit',
  label: 'Unit',
  owningModuleId: 'siampark.property',
} as const satisfies OntosResourceType;
