// @generated by scaffold:outbox-worker worker-host
// @ontos-outbox-worker-host-owner commerce.inventory
import { Layer } from 'effect';
import { defineOutboxWorkerEntry, extractOutboxWorkerSubscriptions } from '@app/core-runtime/outbox/worker';
import { InventoryBackendEffectsUnavailableLive } from '../services/inventory-backend-effects.service.ts';
import { outboxWorkers } from '../workers/index.ts';
import {
  outboxWorkerCorePersistenceLive,
  outboxWorkerDatabaseConfigLive,
  outboxWorkerLayer as outboxWorkerDefinitionLayer,
  outboxWorkerRepositoryLive,
} from './layer.ts';

/** The combined Outbox Worker host polls this entry in its own runtime under its own claim owner. */
export const outboxWorkerEntry = defineOutboxWorkerEntry({
  claimOwnerPrefix: 'commerce.inventory-outbox-worker',
  layer: outboxWorkerDefinitionLayer.pipe(
    Layer.provide(InventoryBackendEffectsUnavailableLive),
    Layer.provide(outboxWorkerRepositoryLive),
    Layer.provide(outboxWorkerCorePersistenceLive),
    Layer.provide(outboxWorkerDatabaseConfigLive),
  ),
  registrations: outboxWorkers,
  subscriptions: extractOutboxWorkerSubscriptions(outboxWorkers),
});
