// @generated by OntOS Codesmith module-api v1
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted } from 'effect';
import { ConfigurationApi } from '../../shared/apis/configuration.ts';
import type { ConfigurationRequest } from '../../shared/apis/configuration.ts';
import { operationGateway } from './action-gateway.ts';

export interface ConfigurationClientOptions {
  readonly baseUrl?: string | URL;
}

type ConfigurationAuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options?: ConfigurationClientOptions,
];

type ConfigurationOperationInvocation = readonly [requestCorrelation: string, options?: ConfigurationClientOptions];

const configurationClient = (
  credential: Redacted.Redacted,
  requestCorrelation: string,
  options: ConfigurationClientOptions,
) =>
  makeGovernedEffectBffClient(
    {
      api: ConfigurationApi,
      credential,
      defaultApiPrefix: '/assortment-api',
      requestCorrelation,
    },
    options,
  );

export const executeConfigurationWithAuthorization = (
  payload: ConfigurationRequest,
  ...[credential, requestCorrelation, options = {}]: ConfigurationAuthorizedInvocation
) =>
  configurationClient(Redacted.make(credential), requestCorrelation, options).pipe(
    Effect.flatMap((client) => client.configuration.execute({ headers: {}, params: {}, payload, query: {} })),
  );

export const executeConfiguration = (
  payload: ConfigurationRequest,
  ...[requestCorrelation, options = {}]: ConfigurationOperationInvocation
) =>
  operationGateway.invoke((credential) =>
    executeConfigurationWithAuthorization(payload, credential, requestCorrelation, options),
  );
