import { executeRecordsWithAuthorization as executeOccupancyRecords } from '@app/siampark-occupancy/clients/records';
import type { OccupancyRef } from '@app/siampark-occupancy/resources/occupancy';
import type { PropertyRef } from '@app/siampark-property/resources/property';
// @generated by OntOS Codesmith Action Service v1
import type { OperationalScope, ReadServiceFactory } from '@app/core-runtime';
import type { PartyRef } from '@app/party-registry/resources/party';
import type { CounterpartyRef } from '@app/party-registry/resources/counterparty';
import type { UnitRef } from '@app/siampark-property/resources/unit';
import { makeReferenceGatewayCredentialSource } from '@app/gateway-principal-verifier/server';
import { executeCounterpartyReadWithAuthorization } from '@app/party-registry/api/client';
import { executeRecordsWithAuthorization as executePropertyRecords } from '@app/siampark-property/clients/records';
import { and, eq } from 'drizzle-orm';
import { Crypto, DateTime, Effect, Match, Schema } from 'effect';

import {
  AgreementsConflict,
  AgreementsNotFound,
  AgreementsPersistenceUnavailable,
  AgreementsRejected,
} from '../../shared/actions/apply-command.ts';
import type { AgreementsCommand, AgreementsError } from '../../shared/actions/apply-command.ts';
import { AgreementsStateSchema, DEMO_BUSINESS_DATE } from '../../shared/apis/records.ts';
import type {
  AgreementsState,
  Contract,
  Document,
  RecordsRequest,
  RecordsResponse,
} from '../../shared/apis/records.ts';
import type { ContractRef } from '../../shared/resources/contract.ts';
import type { DocumentRef } from '../../shared/resources/document.ts';
import { agreementsState } from '../database/schema.ts';

type ScopedTransaction = Parameters<ReadServiceFactory<Readonly<Record<string, never>>>>[0];
export interface AgreementsGuardScope {
  readonly legalEntityId: string;
  readonly tenantId: string;
}
export interface AgreementsValidators {
  readonly counterparty: (ref: CounterpartyRef) => Effect.Effect<
    {
      readonly activeCustomer: boolean;
      readonly archived: boolean;
      readonly counterpartyRef: CounterpartyRef;
      readonly displayName: string | null;
      readonly legalEntityId: string;
      readonly partyRef: PartyRef;
    },
    AgreementsError
  >;
  readonly occupancy: (ref: OccupancyRef) => Effect.Effect<
    {
      readonly customerCounterpartyRef: CounterpartyRef | null;
      readonly kind: 'LONG_TERM_LEASE' | 'SHORT_STAY';
      readonly occupancyRef: OccupancyRef;
      readonly unitRef: UnitRef;
    },
    AgreementsError
  >;

  readonly signatureRequestId: Effect.Effect<string, AgreementsError>;
  readonly unit: (ref: UnitRef) => Effect.Effect<
    {
      readonly legalEntityId: string;
      readonly lifecycleState: string;
      readonly propertyRef: PropertyRef;
      readonly unitRef: UnitRef;
    },
    AgreementsError
  >;
}
export const unavailableAgreementsValidators: AgreementsValidators = {
  counterparty: () =>
    Effect.fail(
      new AgreementsPersistenceUnavailable({
        code: 'agreements_persistence_unavailable',
        reason: 'Counterparty validation is unavailable',
      }),
    ),
  occupancy: () =>
    Effect.fail(
      new AgreementsPersistenceUnavailable({
        code: 'agreements_persistence_unavailable',
        reason: 'Occupancy validation is unavailable',
      }),
    ),
  signatureRequestId: Effect.fail(
    new AgreementsPersistenceUnavailable({
      code: 'agreements_persistence_unavailable',
      reason: 'Signature request identity is unavailable',
    }),
  ),
  unit: () =>
    Effect.fail(
      new AgreementsPersistenceUnavailable({
        code: 'agreements_persistence_unavailable',
        reason: 'Unit validation is unavailable',
      }),
    ),
};
const rejected = (reason: string, cause?: unknown) => {
  const error = new AgreementsRejected({ code: 'agreements_rejected', reason });
  return cause === undefined
    ? error
    : Object.defineProperty(error, 'cause', { configurable: false, enumerable: false, value: cause, writable: false });
};
const conflict = (reason: string) => new AgreementsConflict({ code: 'agreements_conflict', reason });
const unavailable = (cause?: unknown) => {
  const error = new AgreementsPersistenceUnavailable({
    code: 'agreements_persistence_unavailable',
    reason: 'Agreements persistence is temporarily unavailable',
  });
  return cause === undefined
    ? error
    : Object.defineProperty(error, 'cause', { configurable: false, enumerable: false, value: cause, writable: false });
};
const refMatches = (
  left: { readonly resourceId: string; readonly tenantId: string },
  right: { readonly resourceId: string; readonly tenantId: string },
) => left.tenantId === right.tenantId && left.resourceId === right.resourceId;
const ensureContractScope = (record: Contract, scope: AgreementsGuardScope) =>
  [
    record.contractRef,
    record.counterpartyRef,
    record.occupancyRef,
    record.propertyRef,
    record.unitRef,
    record.supersedesContractRef,
  ].every((ref) => ref === null || ref.tenantId === scope.tenantId)
    ? Effect.void
    : Effect.fail(rejected('scope_mismatch'));
const validateOccupancyLink = Effect.fn('Agreements.validateOccupancyLink')(function* validateOccupancyLink(
  record: Contract,
  validators: AgreementsValidators,
) {
  if (record.occupancyRef !== null) {
    const occupancy = yield* validators.occupancy(record.occupancyRef);
    if (
      !refMatches(occupancy.occupancyRef, record.occupancyRef) ||
      record.kind !== 'LEASE' ||
      occupancy.kind !== 'LONG_TERM_LEASE' ||
      record.unitRef === null ||
      !refMatches(occupancy.unitRef, record.unitRef) ||
      occupancy.customerCounterpartyRef === null ||
      !refMatches(occupancy.customerCounterpartyRef, record.counterpartyRef)
    ) {
      return yield* rejected('occupancy_link_mismatch');
    }
  }
  return yield* Effect.void;
});
const validateContract = Effect.fn('Agreements.validateContract')(function* validateContract(
  record: Contract,
  scope: AgreementsGuardScope,
  validators: AgreementsValidators,
) {
  yield* ensureContractScope(record, scope);
  if (record.endDate !== null && record.endDate <= record.startDate) {
    return yield* rejected('invalid_period');
  }
  if (record.kind === 'LEASE' && record.unitRef === null) {
    return yield* rejected('lease_requires_unit');
  }
  const customer = yield* validators.counterparty(record.counterpartyRef);
  if (
    !refMatches(customer.counterpartyRef, record.counterpartyRef) ||
    customer.legalEntityId !== scope.legalEntityId ||
    customer.archived ||
    (record.kind === 'LEASE' && !customer.activeCustomer)
  ) {
    return yield* rejected('counterparty_not_usable');
  }
  if (record.unitRef !== null) {
    const unit = yield* validators.unit(record.unitRef);
    if (
      !refMatches(unit.unitRef, record.unitRef) ||
      unit.legalEntityId !== scope.legalEntityId ||
      unit.lifecycleState !== 'ACTIVE' ||
      (record.propertyRef !== null && !refMatches(record.propertyRef, unit.propertyRef))
    ) {
      return yield* rejected('unit_not_usable');
    }
  }
  yield* validateOccupancyLink(record, validators);
  return yield* Effect.void;
});
const findContract = (state: AgreementsState, ref: ContractRef, scope: AgreementsGuardScope) => {
  if (ref.tenantId !== scope.tenantId) {
    return Effect.fail(rejected('scope_mismatch'));
  }
  const record = state.contracts.find((value) => refMatches(value.contractRef, ref));
  return record === undefined
    ? Effect.fail(
        new AgreementsNotFound({
          code: 'agreements_not_found',
          reason: 'Contract is not present in the authorized scope',
        }),
      )
    : Effect.succeed(record);
};
const findDocument = (state: AgreementsState, ref: DocumentRef, scope: AgreementsGuardScope) => {
  if (ref.tenantId !== scope.tenantId) {
    return Effect.fail(rejected('scope_mismatch'));
  }
  const record = state.documents.find((value) => refMatches(value.documentRef, ref));
  return record === undefined
    ? Effect.fail(
        new AgreementsNotFound({
          code: 'agreements_not_found',
          reason: 'Document is not present in the authorized scope',
        }),
      )
    : Effect.succeed(record);
};
export interface AgreementsTransition {
  readonly resourceRef: ContractRef | DocumentRef;
  readonly snapshot: AgreementsState;
}
const replaceContract = (state: AgreementsState, record: Contract): AgreementsTransition => ({
  resourceRef: record.contractRef,
  snapshot: {
    ...state,
    contracts: state.contracts.map((value) => (refMatches(value.contractRef, record.contractRef) ? record : value)),
  },
});
const replaceDocument = (state: AgreementsState, record: Document): AgreementsTransition => ({
  resourceRef: record.documentRef,
  snapshot: {
    ...state,
    documents: state.documents.map((value) => (refMatches(value.documentRef, record.documentRef) ? record : value)),
  },
});
const validateDocument = Effect.fn('Agreements.validateDocument')(function* validateDocument(
  state: AgreementsState,
  record: Document,
  scope: AgreementsGuardScope,
) {
  if (
    record.documentRef.tenantId !== scope.tenantId ||
    (record.contractRef !== null && record.contractRef.tenantId !== scope.tenantId)
  ) {
    return yield* rejected('scope_mismatch');
  }
  if (record.contractRef !== null) {
    yield* findContract(state, record.contractRef, scope);
  }
  return yield* Effect.void;
});
export const transitionAgreements = (
  state: AgreementsState,
  command: AgreementsCommand,
  scope: AgreementsGuardScope,
  validators: AgreementsValidators,
): Effect.Effect<AgreementsTransition, AgreementsError> =>
  Match.value(command).pipe(
    Match.tag(
      'CreateContract',
      Effect.fn('Agreements.CreateContract')(function* createContract({
        record,
      }: Extract<AgreementsCommand, { readonly _tag: 'CreateContract' }>) {
        if (
          record.lifecycleState !== 'DRAFT' ||
          record.signatureState !== 'NOT_SENT' ||
          record.supersedesContractRef !== null
        ) {
          return yield* rejected('new_contract_must_be_unsigned_draft');
        }
        if (state.contracts.some((value) => refMatches(value.contractRef, record.contractRef))) {
          return yield* conflict('contract_already_exists');
        }
        yield* validateContract(record, scope, validators);
        return { resourceRef: record.contractRef, snapshot: { ...state, contracts: [...state.contracts, record] } };
      }),
    ),
    Match.tag(
      'UpdateContract',
      Effect.fn('Agreements.UpdateContract')(function* updateContract({
        record,
      }: Extract<AgreementsCommand, { readonly _tag: 'UpdateContract' }>) {
        const previous = yield* findContract(state, record.contractRef, scope);
        if (
          previous.lifecycleState !== 'DRAFT' ||
          previous.signatureState !== 'NOT_SENT' ||
          record.lifecycleState !== previous.lifecycleState ||
          record.signatureState !== previous.signatureState ||
          (previous.supersedesContractRef === null
            ? record.supersedesContractRef !== null
            : record.supersedesContractRef === null ||
              !refMatches(previous.supersedesContractRef, record.supersedesContractRef))
        ) {
          return yield* conflict('update_requires_unsigned_draft');
        }
        yield* validateContract(record, scope, validators);
        return replaceContract(state, record);
      }),
    ),
    Match.tag(
      'ActivateContract',
      Effect.fn('Agreements.ActivateContract')(function* activateContract({
        contractRef,
      }: Extract<AgreementsCommand, { readonly _tag: 'ActivateContract' }>) {
        const record = yield* findContract(state, contractRef, scope);
        if (record.lifecycleState !== 'DRAFT') {
          return yield* conflict('activate_requires_draft');
        }
        if (record.endDate !== null && record.endDate <= DEMO_BUSINESS_DATE) {
          return yield* rejected('cannot_activate_expired_contract');
        }
        yield* validateContract(record, scope, validators);
        return replaceContract(state, { ...record, lifecycleState: 'ACTIVE' });
      }),
    ),
    Match.tag(
      'TerminateContract',
      Effect.fn('Agreements.TerminateContract')(function* terminateContract({
        contractRef,
      }: Extract<AgreementsCommand, { readonly _tag: 'TerminateContract' }>) {
        const record = yield* findContract(state, contractRef, scope);
        if (record.lifecycleState !== 'ACTIVE') {
          return yield* conflict('terminate_requires_active');
        }
        return replaceContract(state, { ...record, lifecycleState: 'TERMINATED' });
      }),
    ),
    Match.tag(
      'RenewContract',
      Effect.fn('Agreements.RenewContract')(function* renewContract({
        contractRef,
        successor,
      }: Extract<AgreementsCommand, { readonly _tag: 'RenewContract' }>) {
        const previous = yield* findContract(state, contractRef, scope);
        if (previous.lifecycleState !== 'ACTIVE' && previous.lifecycleState !== 'EXPIRED') {
          return yield* conflict('renew_requires_active_or_expired');
        }
        if (
          state.contracts.some(
            (value) =>
              refMatches(value.contractRef, successor.contractRef) ||
              (value.supersedesContractRef !== null &&
                refMatches(value.supersedesContractRef, contractRef) &&
                value.lifecycleState === 'DRAFT'),
          )
        ) {
          return yield* conflict('successor_already_exists');
        }
        if (
          successor.lifecycleState !== 'DRAFT' ||
          successor.signatureState !== 'NOT_SENT' ||
          successor.supersedesContractRef === null ||
          !refMatches(successor.supersedesContractRef, previous.contractRef) ||
          !refMatches(successor.counterpartyRef, previous.counterpartyRef) ||
          successor.kind !== previous.kind ||
          (previous.unitRef === null
            ? successor.unitRef !== null
            : successor.unitRef === null || !refMatches(previous.unitRef, successor.unitRef)) ||
          (previous.endDate !== null && successor.startDate < previous.endDate)
        ) {
          return yield* rejected('invalid_successor');
        }
        yield* validateContract(successor, scope, validators);
        return {
          resourceRef: successor.contractRef,
          snapshot: { ...state, contracts: [...state.contracts, successor] },
        };
      }),
    ),
    Match.tag(
      'SendSignature',
      Effect.fn('Agreements.SendSignature')(function* sendSignature({
        contractRef,
        signerContact,
      }: Extract<AgreementsCommand, { readonly _tag: 'SendSignature' }>) {
        const record = yield* findContract(state, contractRef, scope);
        if (
          record.lifecycleState !== 'DRAFT' ||
          (record.signatureState !== 'NOT_SENT' && record.signatureState !== 'DECLINED')
        ) {
          return yield* conflict('signature_send_requires_unsigned_draft');
        }
        const customer = yield* validators.counterparty(record.counterpartyRef);
        if (
          customer.archived ||
          !customer.activeCustomer ||
          customer.legalEntityId !== scope.legalEntityId ||
          !refMatches(customer.counterpartyRef, record.counterpartyRef) ||
          customer.partyRef.tenantId !== scope.tenantId
        ) {
          return yield* rejected('signature_signer_projection_mismatch');
        }
        const contact = yield* Schema.decodeEffect(Schema.Trim.check(Schema.isMinLength(1), Schema.isMaxLength(500)))(
          signerContact,
        ).pipe(Effect.mapError((error) => rejected('signature_contact_required', error)));
        const observationId = yield* validators.signatureRequestId;
        const attemptedAt = DateTime.formatIso(yield* DateTime.now);
        const changed = replaceContract(state, { ...record, signatureState: 'SENT' });
        return {
          ...changed,
          snapshot: {
            ...changed.snapshot,
            signatureObservations: [
              ...state.signatureObservations,
              {
                attemptedAt,
                completedAt: null,
                contractRef,
                correlation: `signature:${observationId}`,
                documentRef: null,
                integrationKind: 'ELECTRONIC_SIGNATURE' as const,
                mode: 'SIMULATED' as const,
                observationId,
                ownerResourceRef: contractRef,
                providerLabel: 'DEMO',
                requestSummary: `Contract ${contractRef.resourceId}; canonical signer ${customer.partyRef.resourceId}`,
                resultSummary: 'SIMULATED: signature request submitted',
                signer: {
                  contact,
                  counterpartyRef: customer.counterpartyRef,
                  displayName: customer.displayName,
                  partyRef: customer.partyRef,
                },
                state: 'SENT' as const,
              },
            ],
          },
        };
      }),
    ),
    Match.tag(
      'ObserveSignature',
      Effect.fn('Agreements.ObserveSignature')(function* observeSignature({
        contractRef,
        document,
        outcome,
      }: Extract<AgreementsCommand, { readonly _tag: 'ObserveSignature' }>) {
        const record = yield* findContract(state, contractRef, scope);
        if (record.lifecycleState !== 'DRAFT' || record.signatureState !== 'SENT') {
          return yield* conflict('signature_result_requires_sent');
        }
        if (outcome === 'SIGNED') {
          if (
            document === null ||
            document.contractRef === null ||
            !refMatches(document.contractRef, contractRef) ||
            document.lifecycleState !== 'FINAL' ||
            document.signedDocumentReference === null
          ) {
            return yield* rejected('signed_result_requires_final_document');
          }
          yield* validateDocument(state, document, scope);
          if (state.documents.some((value) => refMatches(value.documentRef, document.documentRef))) {
            return yield* conflict('signed_document_already_exists');
          }
        } else if (document !== null) {
          return yield* rejected('declined_result_has_no_signed_document');
        }
        const pending = state.signatureObservations.findLast(
          (value) => refMatches(value.contractRef, contractRef) && value.state === 'SENT',
        );
        if (pending === undefined) {
          return yield* conflict('signature_pending_observation_required');
        }
        const observedAt = DateTime.formatIso(yield* DateTime.now);
        const stampedDocument =
          document === null ? null : { ...document, createdAt: observedAt, updatedAt: observedAt };
        const changed = replaceContract(state, { ...record, signatureState: outcome });
        return {
          ...changed,
          snapshot: {
            ...changed.snapshot,
            documents: stampedDocument === null ? state.documents : [...state.documents, stampedDocument],
            signatureObservations: state.signatureObservations.map((value) =>
              value.observationId === pending.observationId
                ? {
                    ...value,
                    completedAt: observedAt,
                    documentRef: document?.documentRef ?? null,
                    resultSummary: `SIMULATED: ${outcome}`,
                    state: outcome,
                  }
                : value,
            ),
          },
        };
      }),
    ),
    Match.tag(
      'CreateDocument',
      Effect.fn('Agreements.CreateDocument')(function* createDocument({
        record,
      }: Extract<AgreementsCommand, { readonly _tag: 'CreateDocument' }>) {
        if (record.lifecycleState !== 'DRAFT' || record.signedDocumentReference !== null) {
          return yield* rejected('new_document_must_be_draft');
        }
        if (state.documents.some((value) => refMatches(value.documentRef, record.documentRef))) {
          return yield* conflict('document_already_exists');
        }
        yield* validateDocument(state, record, scope);
        const createdAt = DateTime.formatIso(yield* DateTime.now);
        return {
          resourceRef: record.documentRef,
          snapshot: { ...state, documents: [...state.documents, { ...record, createdAt, updatedAt: createdAt }] },
        };
      }),
    ),
    Match.tag(
      'UpdateDocument',
      Effect.fn('Agreements.UpdateDocument')(function* updateDocument({
        record,
      }: Extract<AgreementsCommand, { readonly _tag: 'UpdateDocument' }>) {
        const previous = yield* findDocument(state, record.documentRef, scope);
        if (
          previous.lifecycleState !== 'DRAFT' ||
          record.lifecycleState !== 'DRAFT' ||
          record.signedDocumentReference !== null
        ) {
          return yield* conflict('update_requires_draft_document');
        }
        yield* validateDocument(state, record, scope);
        const updatedAt = DateTime.formatIso(yield* DateTime.now);
        return replaceDocument(state, { ...record, createdAt: previous.createdAt, updatedAt });
      }),
    ),
    Match.tag(
      'FinalizeDocument',
      Effect.fn('Agreements.FinalizeDocument')(function* finalizeDocument({
        documentRef,
      }: Extract<AgreementsCommand, { readonly _tag: 'FinalizeDocument' }>) {
        const record = yield* findDocument(state, documentRef, scope);
        if (record.lifecycleState !== 'DRAFT') {
          return yield* conflict('finalize_requires_draft_document');
        }
        return replaceDocument(state, {
          ...record,
          lifecycleState: 'FINAL',
          updatedAt: DateTime.formatIso(yield* DateTime.now),
        });
      }),
    ),
    Match.tag(
      'ArchiveDocument',
      Effect.fn('Agreements.ArchiveDocument')(function* archiveDocument({
        documentRef,
      }: Extract<AgreementsCommand, { readonly _tag: 'ArchiveDocument' }>) {
        const record = yield* findDocument(state, documentRef, scope);
        if (record.lifecycleState === 'ARCHIVED') {
          return yield* conflict('document_already_archived');
        }
        return replaceDocument(state, {
          ...record,
          lifecycleState: 'ARCHIVED',
          updatedAt: DateTime.formatIso(yield* DateTime.now),
        });
      }),
    ),
    Match.exhaustive,
  );
export const presentContracts = (state: AgreementsState) =>
  state.contracts.map((record) => {
    const hasSuccessorDraft = state.contracts.some(
      (value) =>
        value.supersedesContractRef !== null &&
        refMatches(value.supersedesContractRef, record.contractRef) &&
        value.lifecycleState === 'DRAFT',
    );
    const isExpired =
      record.lifecycleState === 'EXPIRED' ||
      (record.lifecycleState === 'ACTIVE' && record.endDate !== null && record.endDate <= DEMO_BUSINESS_DATE);
    const daysRemaining =
      record.endDate === null
        ? null
        : (DateTime.toEpochMillis(DateTime.makeUnsafe(`${record.endDate}T00:00:00.000Z`)) -
            DateTime.toEpochMillis(DateTime.makeUnsafe(`${DEMO_BUSINESS_DATE}T00:00:00.000Z`))) /
          86_400_000;
    return {
      ...record,
      expiringSoon: record.lifecycleState === 'ACTIVE' && !isExpired && daysRemaining !== null && daysRemaining <= 30,
      hasSuccessorDraft,
      isExpired,
    };
  });
export const filterAgreementsRecords = (
  state: AgreementsState,
  revision: number,
  input: RecordsRequest,
): RecordsResponse => {
  const contracts = presentContracts(state).filter(
    (record) =>
      (input.resourceId === undefined || record.contractRef.resourceId === input.resourceId) &&
      (input.kind === undefined || record.kind === input.kind) &&
      (input.state === undefined || record.lifecycleState === input.state) &&
      (input.expiringSoon !== true || record.expiringSoon),
  );
  const documents = state.documents.filter(
    (record) =>
      (input.resourceId === undefined &&
        input.kind === undefined &&
        input.state === undefined &&
        input.expiringSoon !== true) ||
      record.documentRef.resourceId === input.resourceId ||
      (record.contractRef !== null &&
        contracts.some(
          (contract) => record.contractRef !== null && refMatches(contract.contractRef, record.contractRef),
        )),
  );
  return {
    contracts,
    documents,
    revision,
    signatureObservations: state.signatureObservations.filter((observation) =>
      contracts.some((record) => refMatches(record.contractRef, observation.contractRef)),
    ),
  };
};
export type AgreementsPersistence = Readonly<{
  load: () => Effect.Effect<
    { readonly revision: number; readonly snapshot: AgreementsState },
    AgreementsPersistenceUnavailable
  >;
  save: (
    snapshot: AgreementsState,
    expectedRevision: number,
  ) => Effect.Effect<number, AgreementsPersistenceUnavailable | AgreementsConflict>;
}>;
export const persistenceService = (
  transaction: ScopedTransaction,
  scope: OperationalScope,
): Effect.Effect<AgreementsPersistence, AgreementsPersistenceUnavailable> => {
  if (scope.legalEntityId === undefined) {
    return Effect.fail(unavailable());
  }
  const { legalEntityId, tenantId } = scope;
  const scopeWhere = and(eq(agreementsState.tenantId, tenantId), eq(agreementsState.legalEntityId, legalEntityId));
  return Effect.succeed({
    load: () =>
      transaction
        .select()
        .from(agreementsState)
        .where(scopeWhere)
        .limit(1)
        .pipe(
          Effect.mapError(unavailable),
          Effect.flatMap(([row]) =>
            row === undefined
              ? Effect.fail(unavailable())
              : Schema.decodeEffect(AgreementsStateSchema)(row.snapshot).pipe(
                  Effect.mapError(unavailable),
                  Effect.map((snapshot) => ({ revision: row.revision, snapshot })),
                ),
          ),
        ),
    save: (snapshot: AgreementsState, expectedRevision: number) =>
      transaction
        .update(agreementsState)
        .set({ revision: expectedRevision + 1, snapshot })
        .where(and(scopeWhere, eq(agreementsState.revision, expectedRevision)))
        .returning({ revision: agreementsState.revision })
        .pipe(
          Effect.mapError(unavailable),
          Effect.flatMap(([row]) =>
            row === undefined ? Effect.fail(conflict('stale_revision')) : Effect.succeed(row.revision),
          ),
        ),
  });
};

export const makeAgreementsValidators = Effect.fn('Agreements.validators')(function* makeAgreementsValidators(
  scope: OperationalScope,
) {
  if (scope.legalEntityId === undefined) {
    return yield* unavailable();
  }
  const { legalEntityId } = scope;
  const source = yield* makeReferenceGatewayCredentialSource(scope).pipe(Effect.mapError(unavailable));
  const crypto = yield* Crypto.Crypto;
  return {
    counterparty: Effect.fn('Agreements.counterpartyProjection')(function* counterpartyProjection(
      ref: CounterpartyRef,
    ) {
      const target = yield* source.issue('party-registry');
      const value = yield* executeCounterpartyReadWithAuthorization(
        { counterpartyRef: ref },
        target.authorization,
        scope.correlationId,
        { baseUrl: target.apiBaseUrl, compositionRevision: target.compositionRevision },
      );
      return {
        activeCustomer: value.currentRoles.some((role) => role.roleType === 'CUSTOMER' && role.state === 'ACTIVE'),
        archived: value.party.archived,
        counterpartyRef: value.counterpartyRef,
        displayName: value.party.displayName,
        legalEntityId: value.legalEntityRef.resourceId,
        partyRef: value.party.canonicalPartyRef,
      };
    }, Effect.mapError(unavailable)),
    occupancy: Effect.fn('Agreements.occupancyProjection')(
      function* occupancyProjection(ref: OccupancyRef) {
        const target = yield* source.issue('siampark-occupancy');
        const result = yield* executeOccupancyRecords(
          { resourceId: ref.resourceId },
          target.authorization,
          scope.correlationId,
          { baseUrl: target.apiBaseUrl, compositionRevision: target.compositionRevision },
        );
        const occupancy = result.occupancies.find((record) => refMatches(record.occupancyRef, ref));
        if (occupancy === undefined) {
          return yield* rejected('occupancy_link_mismatch');
        }
        return {
          customerCounterpartyRef: occupancy.customerCounterpartyRef,
          kind: occupancy.kind,
          occupancyRef: occupancy.occupancyRef,
          unitRef: occupancy.unitRef,
        };
      },
      Effect.mapError(
        Match.type<
          | Effect.Error<ReturnType<typeof executeOccupancyRecords>>
          | Effect.Error<ReturnType<typeof source.issue>>
          | AgreementsRejected
        >().pipe(
          Match.tag('AgreementsRejected', (value) => value),
          Match.orElse(unavailable),
        ),
      ),
    ),
    signatureRequestId: crypto.randomUUIDv4.pipe(Effect.mapError(unavailable)),
    unit: Effect.fn('Agreements.unitProjection')(function* unitProjection(ref: UnitRef) {
      const target = yield* source.issue('siampark-property').pipe(Effect.mapError(unavailable));
      const value = yield* executePropertyRecords(
        { resourceId: ref.resourceId },
        target.authorization,
        scope.correlationId,
        { baseUrl: target.apiBaseUrl, compositionRevision: target.compositionRevision },
      ).pipe(Effect.mapError(unavailable));
      const unit = value.units.find((record) => refMatches(record.unitRef, ref));
      if (unit === undefined) {
        return yield* rejected('unit_not_usable');
      }
      const parentTarget = yield* source.issue('siampark-property').pipe(Effect.mapError(unavailable));
      const parent = yield* executePropertyRecords(
        { resourceId: unit.propertyRef.resourceId },
        parentTarget.authorization,
        scope.correlationId,
        { baseUrl: parentTarget.apiBaseUrl, compositionRevision: parentTarget.compositionRevision },
      ).pipe(Effect.mapError(unavailable));
      const property = parent.properties.find((record) => refMatches(record.propertyRef, unit.propertyRef));
      if (
        property === undefined ||
        property.lifecycleState !== 'ACTIVE' ||
        property.legalEntityRef.resourceId !== legalEntityId
      ) {
        return yield* rejected('unit_not_usable');
      }
      return {
        legalEntityId: property.legalEntityRef.resourceId,
        lifecycleState: unit.lifecycleState,
        propertyRef: unit.propertyRef,
        unitRef: unit.unitRef,
      };
    }),
  } satisfies AgreementsValidators;
});
