// @generated by OntOS Codesmith Action Service v1
import { ContextAccess, OperationContextUnavailable, principalEligibilityForTransaction } from '@app/core-runtime';
import { makeReferenceGatewayCredentialSource } from '@app/gateway-principal-verifier/server';
import { executeRecordsWithAuthorization as executePropertyRecords } from '@app/siampark-property/clients/records';
import type { ContextAccessService, OperationalScope, ScopedTransactionExecutor } from '@app/core-runtime';
import { and, eq } from 'drizzle-orm';
import { Context, DateTime, Effect, Match, Option, Predicate, Schema, Struct } from 'effect';

import {
  WorkLifecycleConflict,
  WorkNotFound,
  WorkPermissionDenied,
  WorkPersistenceUnavailable,
  WorkReferenceIneligible,
  WorkReferenceUnavailable,
  WorkRevisionConflict,
  WorkScopeMismatch,
} from '../../shared/actions/apply-command.ts';
import type { WorkCommand } from '../../shared/actions/apply-command.ts';
import { WorkStateSchema } from '../../shared/apis/records.ts';
import type { ContextRef, RecordsRequest, Task, TaskState, WorkState } from '../../shared/apis/records.ts';
import { TaskRefSchema } from '../../shared/resources/task.ts';
import { workStates } from '../database/schema.ts';

const unavailable = (cause?: unknown) =>
  Object.defineProperty(
    new WorkPersistenceUnavailable({
      code: 'work_persistence_unavailable',
      reason: 'Work persistence is temporarily unavailable',
    }),
    'cause',
    { enumerable: false, value: cause },
  );

const referenceUnavailable = (cause?: unknown) =>
  Object.defineProperty(
    new WorkReferenceUnavailable({
      code: 'work_reference_unavailable',
      reason: 'Reference authorization is temporarily unavailable',
    }),
    'cause',
    { enumerable: false, value: cause },
  );

export interface WorkReferenceVerifierService {
  readonly verify: (
    refs: readonly ContextRef[],
    scope: OperationalScope,
  ) => Effect.Effect<void, WorkReferenceIneligible | WorkReferenceUnavailable>;
}
export class WorkReferenceVerifier extends Context.Service<WorkReferenceVerifier, WorkReferenceVerifierService>()(
  '@app/siampark-work/services/persistence.service/WorkReferenceVerifier',
) {}

const propertyRecordMatches = (
  result: Effect.Success<ReturnType<typeof executePropertyRecords>>,
  ref: ContextRef,
  tenantId: string,
) =>
  [
    ...result.properties.map(({ propertyRef }) => propertyRef),
    ...result.units.map(({ unitRef }) => unitRef),
    ...result.assets.map(({ assetRef }) => assetRef),
  ].some(
    (owned) =>
      owned.resourceId === ref.resourceId && owned.tenantId === tenantId && owned.resourceType === ref.resourceType,
  );

const propertyReadFailure = (error: Effect.Error<ReturnType<typeof executePropertyRecords>>) =>
  Match.value(error).pipe(
    Match.tag(
      'RecordsForbiddenProblem',
      'RecordsNotFoundProblem',
      () =>
        new WorkReferenceIneligible({
          code: 'work_reference_ineligible',
          reason: 'Task context is absent or forbidden',
        }),
    ),
    Match.orElse(referenceUnavailable),
  );

export const makeWorkReferenceVerifier = (
  source: Effect.Success<ReturnType<typeof makeReferenceGatewayCredentialSource>>,
): WorkReferenceVerifierService => ({
  verify: (refs, scope) =>
    Effect.forEach(
      refs,
      Effect.fn('Work.verifyReference')(function* verifyReference(ref) {
        if (ref.tenantId !== scope.tenantId) {
          return yield* new WorkReferenceIneligible({
            code: 'work_reference_ineligible',
            reason: 'Reference must belong to the trusted tenant',
          });
        }
        if (
          ref.moduleId !== 'siampark.property' ||
          !['siampark.property.property', 'siampark.property.unit', 'siampark.property.asset'].includes(
            ref.resourceType,
          )
        ) {
          return yield* new WorkReferenceIneligible({
            code: 'work_reference_ineligible',
            reason: 'This Task context is not supported',
          });
        }
        const credential = yield* source.issue('siampark-property').pipe(Effect.mapError(referenceUnavailable));
        const result = yield* executePropertyRecords(
          { resourceId: ref.resourceId },
          credential.authorization,
          scope.correlationId,
          { baseUrl: credential.apiBaseUrl, compositionRevision: credential.compositionRevision },
        ).pipe(Effect.mapError(propertyReadFailure));
        const valid = propertyRecordMatches(result, ref, scope.tenantId);
        if (!valid) {
          return yield* new WorkReferenceIneligible({
            code: 'work_reference_ineligible',
            reason: 'Task context does not exist in its owner',
          });
        }
        return yield* Effect.void;
      }),
      { concurrency: 1, discard: true },
    ),
});

export const taskStatusGroup = (state: TaskState) =>
  Match.value(state).pipe(
    Match.when('NEW', () => 'NOT_STARTED' as const),
    Match.whenOr('DONE', 'CANCELLED', () => 'DONE' as const),
    Match.whenOr('IN_PROGRESS', 'WAITING', () => 'IN_PROGRESS' as const),
    Match.exhaustive,
  );
export const taskIsOverdue = (task: Task, referenceDate = '2026-10-05') =>
  taskStatusGroup(task.state) !== 'DONE' && task.dueDate !== undefined && task.dueDate < referenceDate;

const legalTransitions = {
  CANCELLED: [],
  DONE: [],
  IN_PROGRESS: ['WAITING', 'DONE', 'CANCELLED'],
  NEW: ['IN_PROGRESS', 'CANCELLED'],
  WAITING: ['IN_PROGRESS', 'DONE', 'CANCELLED'],
} as const satisfies Readonly<Record<TaskState, readonly TaskState[]>>;

export const evolveWorkState = Effect.fn('Work.evolveState')(function* evolveWorkState(
  state: WorkState,
  command: WorkCommand,
  input: { readonly now: DateTime.Utc; readonly resourceId: string; readonly tenantId: string },
) {
  const { tenantId } = input;
  const refs = Match.value(command).pipe(
    Match.tag('CreateTask', ({ contextRefs = [] }) => contextRefs),
    Match.tag('UpdateTask', 'AssignTask', 'ChangeTaskState', ({ taskRef }) => [taskRef]),
    Match.exhaustive,
  );
  const owner = Match.value(command).pipe(
    Match.tag('CreateTask', 'UpdateTask', 'AssignTask', ({ ownerPrincipalRef }) =>
      Option.fromUndefinedOr(ownerPrincipalRef),
    ),
    Match.tag('ChangeTaskState', () => Option.none()),
    Match.exhaustive,
  );
  if (
    state.collection.ref.tenantId !== tenantId ||
    refs.some((ref) => ref.tenantId !== tenantId) ||
    (Option.isSome(owner) && owner.value.tenantId !== tenantId)
  ) {
    return yield* new WorkScopeMismatch({
      code: 'work_scope_mismatch',
      reason: 'References must belong to the trusted tenant',
    });
  }
  const task = yield* Match.value(command).pipe(
    Match.tag(
      'CreateTask',
      Effect.fn('Work.createTask')(function* createTask(value: Extract<WorkCommand, { readonly _tag: 'CreateTask' }>) {
        const ref = yield* Schema.decodeEffect(TaskRefSchema)({
          moduleId: 'siampark.work',
          resourceId: input.resourceId,
          resourceType: 'siampark.work.task',
          tenantId,
        }).pipe(
          Effect.mapError((cause) =>
            Object.defineProperty(
              new WorkScopeMismatch({ code: 'work_scope_mismatch', reason: 'Task identity must be valid' }),
              'cause',
              { enumerable: false, value: cause },
            ),
          ),
        );
        return {
          collectionRef: state.collection.ref,
          contextRefs: value.contextRefs ?? [],
          createdAt: input.now,
          ...Struct.pick(value, ['description', 'dueDate', 'ownerPrincipalRef']),
          priority: value.priority ?? 'NORMAL',
          ref,
          state: 'NEW' as const,
          title: value.title,
          updatedAt: input.now,
        };
      }),
    ),
    Match.tag(
      'UpdateTask',
      'AssignTask',
      'ChangeTaskState',
      Effect.fn('Work.updateTask')(function* updateTask(value: Exclude<WorkCommand, { readonly _tag: 'CreateTask' }>) {
        const existing = state.tasks.find(
          (entry) => entry.ref.resourceId === value.taskRef.resourceId && entry.ref.tenantId === tenantId,
        );
        if (existing === undefined) {
          return yield* new WorkNotFound({
            code: 'work_not_found',
            reason: 'Task does not exist in the authorized scope',
          });
        }
        if (taskStatusGroup(existing.state) === 'DONE') {
          return yield* new WorkLifecycleConflict({
            code: 'work_lifecycle_conflict',
            reason: 'A completed or cancelled Task cannot change',
          });
        }
        return yield* Match.value(value).pipe(
          Match.tag('AssignTask', ({ ownerPrincipalRef }) =>
            Effect.succeed({ ...existing, ownerPrincipalRef, updatedAt: input.now }),
          ),
          Match.tag('ChangeTaskState', ({ state: target }) =>
            legalTransitions[existing.state].some((candidate) => candidate === target)
              ? Effect.succeed({ ...existing, state: target, updatedAt: input.now })
              : Effect.fail(
                  new WorkLifecycleConflict({
                    code: 'work_lifecycle_conflict',
                    reason: 'The requested Task transition is not allowed',
                  }),
                ),
          ),
          Match.tag('UpdateTask', ({ _tag, taskRef, ...changes }) => {
            void _tag;
            void taskRef;
            return Effect.succeed({ ...existing, ...changes, updatedAt: input.now });
          }),
          Match.exhaustive,
        );
      }),
    ),
    Match.exhaustive,
  );
  if (
    state.tasks.some((entry) => entry.ref.resourceId === task.ref.resourceId) &&
    Predicate.isTagged('CreateTask')(command)
  ) {
    return yield* new WorkRevisionConflict({
      code: 'work_revision_conflict',
      reason: 'Task identity is already in use',
    });
  }
  return {
    state: { ...state, tasks: [...state.tasks.filter((entry) => entry.ref.resourceId !== task.ref.resourceId), task] },
    task,
  };
});

const contextGrant = Effect.fn('Work.contextGrant')(function* contextGrant(
  scope: OperationalScope,
  permission: 'read_all' | 'write_all',
) {
  const access = yield* ContextAccess;
  if (scope.legalEntityId === undefined || access.contextPermissions === undefined) {
    return yield* referenceUnavailable();
  }
  const decisions = yield* access.contextPermissions({
    legalEntityId: scope.legalEntityId,
    principalId: scope.principalId,
    targets: [{ moduleId: 'siampark.work', permission: `siampark.work.${permission}` }],
    tenantId: scope.tenantId,
  });
  if (
    decisions.length !== 1 ||
    decisions[0]?.key !== `siampark.work:siampark.work.${permission}` ||
    decisions[0]?.decision === 'unavailable'
  ) {
    return yield* referenceUnavailable();
  }
  return decisions[0]?.decision === 'allowed';
});

export const visibleWorkTasks = Effect.fn('Work.visibleTasks')(function* visibleTasks(
  tasks: readonly Task[],
  scope: OperationalScope,
) {
  const access = yield* ContextAccess;
  if (yield* contextGrant(scope, 'read_all')) {
    return tasks;
  }
  if (scope.legalEntityId === undefined) {
    return yield* referenceUnavailable();
  }
  const decisions = yield* access.resources({
    legalEntityId: scope.legalEntityId,
    principalId: scope.principalId,
    resources: tasks.map(({ ref }) => ref),
    tenantId: scope.tenantId,
  });
  if (
    decisions.length !== tasks.length ||
    decisions.some(
      (decision, index) =>
        decision.decision === 'unavailable' ||
        decision.key !==
          `${tasks[index]?.ref.moduleId}:${tasks[index]?.ref.resourceType}:${tasks[index]?.ref.resourceId}`,
    )
  ) {
    return yield* referenceUnavailable();
  }
  return tasks.filter((_, index) => decisions[index]?.decision === 'allowed');
});

const validWriteDecision = (
  decisions: Effect.Success<ReturnType<ContextAccessService['resources']>>,
  ref: Task['ref'],
) =>
  decisions.length === 1 &&
  decisions[0]?.key === `${ref.moduleId}:${ref.resourceType}:${ref.resourceId}` &&
  decisions[0]?.decision !== 'unavailable';

export const persistenceService = Effect.fn('Work.persistenceService')(
  function* makePersistence(transaction: ScopedTransactionExecutor, scope: OperationalScope) {
    const { legalEntityId } = scope;
    if (
      legalEntityId === undefined ||
      transaction.scope.tenantId !== scope.tenantId ||
      transaction.scope.legalEntityId !== legalEntityId
    ) {
      return yield* new WorkScopeMismatch({
        code: 'work_scope_mismatch',
        reason: 'A scoped company transaction is required',
      });
    }
    const access = yield* ContextAccess;
    const principalEligibility = principalEligibilityForTransaction(transaction);
    const injectedVerifier = yield* Effect.serviceOption(WorkReferenceVerifier);
    const source = yield* makeReferenceGatewayCredentialSource(scope).pipe(Effect.mapError(referenceUnavailable));
    const verifier = Option.getOrElse(injectedVerifier, () => makeWorkReferenceVerifier(source));
    const whereScope = and(eq(workStates.tenantId, scope.tenantId), eq(workStates.legalEntityId, legalEntityId));
    const load = Effect.fn('Work.load')(function* load() {
      const rows = yield* transaction
        .select()
        .from(workStates)
        .where(whereScope)
        .limit(1)
        .pipe(Effect.mapError(unavailable));
      const [row] = rows;
      if (row === undefined) {
        return yield* unavailable();
      }
      const state = yield* Schema.decodeUnknownEffect(WorkStateSchema)(row.state).pipe(Effect.mapError(unavailable));
      return { revision: row.revision, state };
    });
    const save = Effect.fn('Work.save')(function* save(expectedRevision: number, state: WorkState) {
      const encoded = yield* Schema.encodeEffect(WorkStateSchema)(state).pipe(Effect.mapError(unavailable));
      const updatedAt = yield* DateTime.now;
      const rows = yield* transaction
        .update(workStates)
        .set({ revision: expectedRevision + 1, state: encoded, updatedAt: DateTime.toDateUtc(updatedAt) })
        .where(and(whereScope, eq(workStates.revision, expectedRevision)))
        .returning({ revision: workStates.revision })
        .pipe(Effect.mapError(unavailable));
      if (rows.length !== 1) {
        return yield* new WorkRevisionConflict({
          code: 'work_revision_conflict',
          reason: 'Work changed; refresh before another operation',
        });
      }
      return expectedRevision + 1;
    });
    const apply = Effect.fn('Work.apply')(function* apply(
      command: WorkCommand,
      expectedRevision: number,
      resourceId: string,
    ) {
      if (!(yield* contextGrant(scope, 'write_all'))) {
        if (Predicate.isTagged('CreateTask')(command)) {
          return yield* new WorkPermissionDenied({
            code: 'work_permission_denied',
            reason: 'Creating Tasks requires Work write permission',
          });
        }
        const decisions = yield* access.resources({
          legalEntityId,
          permission: 'write',
          principalId: scope.principalId,
          resources: [command.taskRef],
          tenantId: scope.tenantId,
        });
        if (!validWriteDecision(decisions, command.taskRef)) {
          return yield* referenceUnavailable();
        }
        if (decisions[0]?.decision !== 'allowed') {
          return yield* new WorkPermissionDenied({
            code: 'work_permission_denied',
            reason: 'Task mutation is forbidden',
          });
        }
      }
      const snapshot = yield* load();
      if (snapshot.revision !== expectedRevision) {
        return yield* new WorkRevisionConflict({
          code: 'work_revision_conflict',
          reason: 'Work changed; refresh before another operation',
        });
      }
      const owner = Predicate.isTagged('ChangeTaskState')(command) ? undefined : command.ownerPrincipalRef;
      if (owner !== undefined) {
        if (owner.tenantId !== scope.tenantId) {
          return yield* new WorkScopeMismatch({
            code: 'work_scope_mismatch',
            reason: 'Principal must belong to the trusted tenant',
          });
        }
        const eligibility = yield* principalEligibility.resolve(owner);
        if (eligibility.decision === 'unavailable') {
          return yield* referenceUnavailable();
        }
        if (eligibility.decision !== 'eligible') {
          return yield* new WorkReferenceIneligible({
            code: 'work_reference_ineligible',
            reason: 'Task owner must be an active Principal in the trusted tenant',
          });
        }
      }
      if (Predicate.isTagged('CreateTask')(command) && (command.contextRefs?.length ?? 0) > 0) {
        yield* verifier.verify(command.contextRefs ?? [], scope);
      }
      const now = yield* DateTime.now;
      const change = yield* evolveWorkState(snapshot.state, command, { now, resourceId, tenantId: scope.tenantId });
      const revision = yield* save(expectedRevision, change.state);
      return { revision, task: change.task };
    });
    const records = Effect.fn('Work.records')(function* records(request: RecordsRequest) {
      const snapshot = yield* load();
      const visible = yield* visibleWorkTasks(snapshot.state.tasks, scope);
      if (request.resourceId !== undefined && !visible.some((task) => task.ref.resourceId === request.resourceId)) {
        return yield* new WorkPermissionDenied({
          code: 'work_permission_denied',
          reason: 'Task detail is forbidden or absent',
        });
      }
      const items = visible.filter(
        (task) =>
          (request.resourceId === undefined || task.ref.resourceId === request.resourceId) &&
          (request.state === undefined || task.state === request.state) &&
          (request.ownerPrincipalId === undefined ||
            task.ownerPrincipalRef?.principalId === request.ownerPrincipalId) &&
          (request.contextResourceId === undefined ||
            task.contextRefs.some((ref) => ref.resourceId === request.contextResourceId)),
      );
      return {
        actorPrincipalRef: { principalId: scope.principalId, tenantId: scope.tenantId },
        canWrite: yield* contextGrant(scope, 'write_all'),
        collection: snapshot.state.collection,
        indicators: {
          open: items.filter((task) => taskStatusGroup(task.state) !== 'DONE').length,
          overdue: items.filter((task) => taskIsOverdue(task)).length,
        },
        items,
        referenceDate: '2026-10-05' as const,
        revision: snapshot.revision,
      };
    });
    return { apply, records };
  },
  Effect.mapError((cause) =>
    Object.defineProperty(
      new OperationContextUnavailable({
        code: 'operation_context_unavailable',
        reason: 'Owner-scoped services are temporarily unavailable',
      }),
      'cause',
      { enumerable: false, value: cause },
    ),
  ),
);
