// @generated by OntOS Codesmith module-api v1
import { makeGovernedReadHttpHandler } from '@app/core-runtime/http/governed-read';
import { makeGovernedReadProblems } from '@app/shared-contracts/server/effect-bff-runtime';
import { HttpApiBuilder } from '@modern-js/bff-effect/effect-edge';
import { siamparkOccupancyApi } from '../shared/api.ts';
import {
  RecordsAuthenticationProblemSchema,
  RecordsForbiddenProblemSchema,
  RecordsInternalProblemSchema,
  RecordsInvalidProblemSchema,
  RecordsNotFoundProblemSchema,
  RecordsPolicyConflictProblemSchema,
  RecordsPolicyProblemSchema,
  RecordsUnavailableProblemSchema,
} from '../shared/apis/records.ts';
import { recordsRead } from '../src/api/records.read.ts';
import { authenticateOperationPrincipal } from './auth/action-principal.ts';

const problems = makeGovernedReadProblems({
  authentication: RecordsAuthenticationProblemSchema,
  forbidden: RecordsForbiddenProblemSchema,
  internal: RecordsInternalProblemSchema,
  invalid: RecordsInvalidProblemSchema,
  notFound: RecordsNotFoundProblemSchema,
  policyConflict: RecordsPolicyConflictProblemSchema,
  policyIneligible: RecordsPolicyProblemSchema,
  unavailable: RecordsUnavailableProblemSchema,
});

export const recordsReadApiLive = HttpApiBuilder.group(siamparkOccupancyApi, 'records', (handlers) =>
  handlers.handle(
    'execute',
    makeGovernedReadHttpHandler({
      authenticatePrincipal: authenticateOperationPrincipal,
      problems,
      registration: recordsRead,
    }),
  ),
);
