// @generated by OntOS Codesmith Module Contract v1
// @ontos-deployment-app-id siampark-property
// @ontos-module-id siampark.property
import {
  defineOntosModuleManifest,
  ShellNavigationContributionSchema,
  ShellPageContributionSchema,
} from '@app/core-runtime';
import { Result, Schema } from 'effect';
// <generated-module-manifest-imports>
import { applyCommandAction } from './src/actions/apply-command.action.ts';
import { assetResourceDescriptor } from './shared/resources/asset.ts';
import { IntegrationsPage } from './src/routes/[lang]/siampark/integrations/page.tsx';
import { OverviewPage } from './src/routes/[lang]/siampark/overview/page.tsx';
import { propertyResourceDescriptor } from './shared/resources/property.ts';
import { RecordsApi } from './shared/apis/records.ts';
import { RecordsPage } from './src/routes/[lang]/siampark/properties/page.tsx';
import { unitResourceDescriptor } from './shared/resources/unit.ts';
// </generated-module-manifest-imports>

type NavigationContributionInput = typeof ShellNavigationContributionSchema.Encoded;
type PageContributionInput = typeof ShellPageContributionSchema.Encoded;

const navigationContribution = (value: NavigationContributionInput) =>
  Result.getOrThrow(Schema.decodeResult(ShellNavigationContributionSchema)(value));
const pageContribution = (value: PageContributionInput) =>
  Result.getOrThrow(Schema.decodeResult(ShellPageContributionSchema)(value));

const moduleKey = 'siampark.property';
const accessPermission = 'module.access';
const navigationGroup = 'shell.navigation.modules';
const integrationsPageKey = 'siampark.property.page.integrations';
const overviewPageKey = 'siampark.property.page.overview';
const recordsPageKey = 'siampark.property.page.records';

export const siamparkPropertyManifest = defineOntosModuleManifest({
  activation: {
    defaultState: 'inactive',
    preservesHistoryWhenInactive: true,
    scope: 'tenant',
    supportedStates: ['inactive', 'active', 'read_only', 'suspended', 'quarantined', 'deprecated', 'archived'],
  },
  module: {
    description: 'Siampark Property business capability.',
    displayName: 'Siampark Property',
    id: moduleKey,
    implementedAs: 'ultramodern_microvertical',
    kind: 'business_module',
  },
  publicSurface: {
    actions: [
      // <generated-module-manifest-actions>
      applyCommandAction,
      // </generated-module-manifest-actions>
    ],
    api: {
      // <generated-module-manifest-apis>
      records: RecordsApi,
      // </generated-module-manifest-apis>
    },
    businessPermissions: [
      // <generated-module-manifest-business-permissions>
      // </generated-module-manifest-business-permissions>
    ],
    components: {
      // <generated-module-manifest-components>
      'page-integrations': IntegrationsPage,
      'page-overview': OverviewPage,
      'page-records': RecordsPage,
      // </generated-module-manifest-components>
    },
    events: [],
    reports: [
      // <generated-module-manifest-reports>
      // </generated-module-manifest-reports>
    ],
    resourceTypes: [
      // <generated-module-manifest-resources>
      assetResourceDescriptor,
      propertyResourceDescriptor,
      unitResourceDescriptor,
      // </generated-module-manifest-resources>
    ],
    search: [
      // <generated-module-manifest-search>
      // </generated-module-manifest-search>
    ],
    shellContributions: {
      mediaAttachments: [],
      navigation: [
        // <generated-module-shell-navigation>
        navigationContribution({
          contributionKey: 'siampark.property.navigation.integrations',
          entrypoint: {
            access: 'read',
            authorization: { kind: 'context_permission', permission: accessPermission },
            entrypointKey: integrationsPageKey,
            moduleKey,
            role: 'page',
            scope: 'tenant',
          },
          groupKey: navigationGroup,
          order: 100,
          pageKey: integrationsPageKey,
        }),
        navigationContribution({
          contributionKey: 'siampark.property.navigation.overview',
          entrypoint: {
            access: 'read',
            authorization: { kind: 'context_permission', permission: accessPermission },
            entrypointKey: overviewPageKey,
            moduleKey,
            role: 'page',
            scope: 'tenant',
          },
          groupKey: navigationGroup,
          order: 100,
          pageKey: overviewPageKey,
        }),
        navigationContribution({
          contributionKey: 'siampark.property.navigation.records',
          entrypoint: {
            access: 'read',
            authorization: { kind: 'context_permission', permission: accessPermission },
            entrypointKey: recordsPageKey,
            moduleKey,
            role: 'page',
            scope: 'tenant',
          },
          groupKey: navigationGroup,
          order: 100,
          pageKey: recordsPageKey,
        }),
        // </generated-module-shell-navigation>
      ],
      pages: [
        // <generated-module-shell-pages>
        pageContribution({
          componentKey: 'siampark.property.page-integrations',
          contributionKey: integrationsPageKey,
          entrypoint: {
            access: 'read',
            authorization: { kind: 'context_permission', permission: accessPermission },
            entrypointKey: integrationsPageKey,
            moduleKey,
            role: 'page',
            scope: 'tenant',
          },
          expose: './PageIntegrations',
          routePath: '/siampark/integrations',
        }),
        pageContribution({
          componentKey: 'siampark.property.page-overview',
          contributionKey: overviewPageKey,
          entrypoint: {
            access: 'read',
            authorization: { kind: 'context_permission', permission: accessPermission },
            entrypointKey: overviewPageKey,
            moduleKey,
            role: 'page',
            scope: 'tenant',
          },
          expose: './PageOverview',
          routePath: '/siampark/overview',
        }),
        pageContribution({
          componentKey: 'siampark.property.page-records',
          contributionKey: recordsPageKey,
          entrypoint: {
            access: 'read',
            authorization: { kind: 'context_permission', permission: accessPermission },
            entrypointKey: recordsPageKey,
            moduleKey,
            role: 'page',
            scope: 'tenant',
          },
          expose: './PageRecords',
          routePath: '/siampark/properties',
        }),
        // </generated-module-shell-pages>
      ],
      publicComponents: [
        // <generated-module-shell-components>
        // </generated-module-shell-components>
      ],
      reports: [
        // <generated-module-shell-reports>
        // </generated-module-shell-reports>
      ],
      resourceDetails: [],
      search: [
        // <generated-module-shell-search>
        // </generated-module-shell-search>
      ],
      timelines: [],
    },
  },
});
