// @generated by OntOS Codesmith Module Contract v1
// @ontos-deployment-app-id siampark-property
// @ontos-module-id siampark.property
import { defineVerticalRuntimeRegistration } from '@app/core-runtime';
import { siamparkPropertyManifest } from './vertical.manifest.ts';
// <generated-module-registration-imports>
import { applyCommandAction } from './src/actions/apply-command.action.ts';
// </generated-module-registration-imports>

export const siamparkPropertyRegistration = defineVerticalRuntimeRegistration({
  actions: [
    // <generated-module-registration-actions>
    applyCommandAction,
    // </generated-module-registration-actions>
  ],
  entrypoints: {
    api: {
      // <generated-module-registration-apis>
      records: () => import('./src/api/records-client.ts'),
      // </generated-module-registration-apis>
    },
    components: {
      // <generated-module-registration-components>
      // </generated-module-registration-components>
    },
    pages: {
      // <generated-module-registration-pages>
      'page-integrations': () => import('./src/routes/[lang]/siampark/integrations/page.tsx'),
      'page-overview': () => import('./src/routes/[lang]/siampark/overview/page.tsx'),
      'page-records': () => import('./src/routes/[lang]/siampark/properties/page.tsx'),
      // </generated-module-registration-pages>
    },
    reports: {
      // <generated-module-registration-reports>
      // </generated-module-registration-reports>
    },
    search: {
      // <generated-module-registration-search>
      // </generated-module-registration-search>
    },
  },
  manifest: siamparkPropertyManifest,
  outboxWorkers: [
    // <generated-module-registration-workers>
    // </generated-module-registration-workers>
  ],
});

// <generated-public-component-registrations>
// </generated-public-component-registrations>
// <generated-search-registrations>
// </generated-search-registrations>
// <generated-report-registrations>
// </generated-report-registrations>
