// @generated by OntOS Codesmith module-api v1
import {
  OperationContextUnavailable,
  ReadHandlerUnavailable,
  ReadPermissionDenied,
  defineRead,
  defineTenantModuleEntrypoint,
} from '@app/core-runtime';
import { Effect, Match } from 'effect';
import type { ReadHandlerContext, ReadHandlerResult, ReadServiceFactory } from '@app/core-runtime';
import type { RecordsRequest, RecordsResponse } from '../../shared/apis/records.ts';
import { persistenceService } from '../services/persistence.service.ts';
import { RecordsRequestSchema, RecordsResponseSchema } from '../../shared/apis/records.ts';

type Services = Effect.Success<ReturnType<typeof persistenceService>>;

const readFailure = (failure: Effect.Error<ReturnType<Services['records']>>) =>
  Match.value(failure).pipe(
    Match.tag(
      'WorkPermissionDenied',
      () => new ReadPermissionDenied({ code: 'read_permission_denied', reason: 'The requested record is forbidden' }),
    ),
    Match.tag(
      'WorkPersistenceUnavailable',
      'WorkReferenceUnavailable',
      () =>
        new ReadHandlerUnavailable({
          code: 'read_handler_unavailable',
          reason: 'Records are temporarily unavailable',
        }),
    ),
    Match.exhaustive,
  );

const moduleKey = 'siampark.work';
const recordsEntrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: { kind: 'context_permission', permission: 'module.access' },
  entrypointKey: 'siampark.work.api.records',
  moduleKey,
  role: 'api',
});

const makeRecordsServices: ReadServiceFactory<Services, Effect.Services<ReturnType<typeof persistenceService>>> = (
  transaction,
  scope,
) =>
  persistenceService(transaction, scope).pipe(
    Effect.mapError((cause) =>
      Object.defineProperty(
        new OperationContextUnavailable({
          code: 'operation_context_unavailable',
          reason: 'Owner records services are temporarily unavailable',
        }),
        'cause',
        { configurable: false, enumerable: false, value: cause, writable: false },
      ),
    ),
  );

export const recordsRead = defineRead(
  {
    accessKind: 'list',
    entrypoint: recordsEntrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'siampark.work.api.records.evidence.v1',
    },
    inputSchema: RecordsRequestSchema,
    legalEntityScope: 'required',
    owningModuleKey: moduleKey,
    permissionTarget: 'module',
    policies: [],
    readKey: 'siampark.work.api.records',
    resultSchema: RecordsResponseSchema,
    schemaVersion: '1',
  },
  (
    input: RecordsRequest,
    context: ReadHandlerContext<Services>,
  ): Effect.Effect<
    ReadHandlerResult<RecordsResponse>,
    ReadPermissionDenied | ReadHandlerUnavailable,
    Effect.Services<ReturnType<typeof persistenceService>> | Effect.Services<ReturnType<Services['records']>>
  > =>
    context.services.records(input).pipe(
      Effect.mapError(readFailure),
      Effect.map((result) => ({ evidence: { resultCount: result.items.length }, result })),
    ),
  makeRecordsServices,
  () => ({ kind: 'module', moduleId: moduleKey }),
);
