// @generated by OntOS Codesmith Action Service v1
import { OperationContextUnavailable } from '@app/core-runtime';
import type { OperationalScope, ReadServiceFactory } from '@app/core-runtime';
import { and, eq, sql } from 'drizzle-orm';
import { DateTime, Effect, Match, Schema } from 'effect';
import type { PropertyState } from '../../shared/apis/records.ts';
import { PropertyStateSchema } from '../../shared/apis/records.ts';
import type { PropertyCommand } from '../../shared/actions/apply-command.ts';
import {
  PropertyConflict,
  PropertyIneligible,
  PropertyNotFound,
  PropertyUnavailable,
} from '../../shared/actions/apply-command.ts';
import { propertyState } from '../database/schema.ts';

type ScopedTransaction = Parameters<ReadServiceFactory<Readonly<Record<string, never>>>>[0];
const unavailable = (cause?: unknown) =>
  new PropertyUnavailable({ cause, code: 'property_unavailable', reason: 'Property storage is unavailable' });
const conflict = (reason: string) => new PropertyConflict({ code: 'property_conflict', reason });
const ineligible = (reason: string) => new PropertyIneligible({ code: 'property_ineligible', reason });
const missing = () => new PropertyNotFound({ code: 'property_not_found', reason: 'Property resource not found' });

type PropertyTransitionContext = Readonly<{ legalEntityId: string; now: string; resourceId: string; tenantId: string }>;

export const applyPropertyCommand = Effect.fn('Property.applyCommand')(function* applyPropertyCommandEffect(
  state: PropertyState,
  command: PropertyCommand,
  context: PropertyTransitionContext,
) {
  const ref = (resourceType: 'siampark.property.property' | 'siampark.property.unit' | 'siampark.property.asset') => ({
    moduleId: 'siampark.property' as const,
    resourceId: context.resourceId,
    resourceType,
    tenantId: context.tenantId,
  });
  if ('propertyRef' in command && command.propertyRef.tenantId !== context.tenantId) {
    return yield* ineligible('Cross-tenant Property reference');
  }
  if ('unitRef' in command && command.unitRef !== null && command.unitRef.tenantId !== context.tenantId) {
    return yield* ineligible('Cross-tenant Unit reference');
  }
  if ('assetRef' in command && command.assetRef.tenantId !== context.tenantId) {
    return yield* ineligible('Cross-tenant Asset reference');
  }
  if (
    'code' in command &&
    [...state.properties, ...state.units, ...state.assets].some((record) => record.code === command.code)
  ) {
    return yield* conflict('Business code already exists');
  }
  if (
    'propertyRef' in command &&
    !state.properties.some((record) => record.propertyRef.resourceId === command.propertyRef.resourceId)
  ) {
    return yield* missing();
  }
  if (
    'assetRef' in command &&
    !state.assets.some((record) => record.assetRef.resourceId === command.assetRef.resourceId)
  ) {
    return yield* missing();
  }
  if (
    'unitRef' in command &&
    command.unitRef !== null &&
    !state.units.some((record) => record.unitRef.resourceId === command.unitRef?.resourceId)
  ) {
    return yield* missing();
  }
  yield* Match.value(command).pipe(
    Match.tag('CreateAsset', (input) =>
      input.unitRef !== null &&
      !state.units.some(
        (unit) =>
          unit.unitRef.resourceId === input.unitRef?.resourceId &&
          unit.propertyRef.resourceId === input.propertyRef.resourceId,
      )
        ? Effect.fail(ineligible('Asset Unit belongs to another Property'))
        : Effect.void,
    ),
    Match.orElse(() => Effect.void),
  );
  return yield* Match.value(command).pipe(
    Match.tags({
      ChangeAssetLifecycle: (input) =>
        Effect.succeed({
          resourceRef: input.assetRef,
          state: {
            ...state,
            assets: state.assets.map((record) =>
              record.assetRef.resourceId === input.assetRef.resourceId
                ? { ...record, lifecycleState: input.lifecycleState }
                : record,
            ),
          },
        }),
      ChangePropertyLifecycle: (input) =>
        Effect.succeed({
          resourceRef: input.propertyRef,
          state: {
            ...state,
            properties: state.properties.map((record) =>
              record.propertyRef.resourceId === input.propertyRef.resourceId
                ? { ...record, lifecycleState: input.lifecycleState, updatedAt: context.now }
                : record,
            ),
          },
        }),
      ChangeUnitLifecycle: (input) =>
        Effect.succeed({
          resourceRef: input.unitRef,
          state: {
            ...state,
            units: state.units.map((record) =>
              record.unitRef.resourceId === input.unitRef.resourceId
                ? { ...record, lifecycleState: input.lifecycleState }
                : record,
            ),
          },
        }),
      CreateAsset: (input) => {
        const assetRef = { ...ref('siampark.property.asset'), resourceType: 'siampark.property.asset' as const };
        const asset = {
          acquiredAt: null,
          assetRef,
          category: input.category,
          code: input.code,
          lastServiceAt: null,
          lifecycleState: 'ACTIVE' as const,
          name: input.name,
          nextServiceAt: null,
          propertyRef: input.propertyRef,
          serialNumber: null,
          unitRef: input.unitRef,
        };
        return Effect.succeed({ resourceRef: assetRef, state: { ...state, assets: [...state.assets, asset] } });
      },
      CreateProperty: (input) => {
        const propertyRef = {
          ...ref('siampark.property.property'),
          resourceType: 'siampark.property.property' as const,
        };
        const property = {
          address: input.address,
          code: input.code,
          createdAt: context.now,
          legalEntityRef: {
            moduleId: 'core.identity' as const,
            resourceId: context.legalEntityId,
            resourceType: 'core.identity.legal-entity' as const,
            tenantId: context.tenantId,
          },
          lifecycleState: 'PLANNED' as const,
          name: input.name,
          note: null,
          propertyRef,
          updatedAt: context.now,
        };
        return Effect.succeed({
          resourceRef: propertyRef,
          state: { ...state, properties: [...state.properties, property] },
        });
      },
      CreateUnit: (input) => {
        const unitRef = { ...ref('siampark.property.unit'), resourceType: 'siampark.property.unit' as const };
        const unit = {
          capacity: input.capacity,
          code: input.code,
          lifecycleState: 'ACTIVE' as const,
          name: input.name,
          note: null,
          propertyRef: input.propertyRef,
          unitKind: null,
          unitRef,
        };
        return Effect.succeed({ resourceRef: unitRef, state: { ...state, units: [...state.units, unit] } });
      },
      UpdateAsset: (input) =>
        Effect.succeed({
          resourceRef: input.assetRef,
          state: {
            ...state,
            assets: state.assets.map((record) =>
              record.assetRef.resourceId === input.assetRef.resourceId
                ? { ...record, category: input.category, name: input.name, serialNumber: input.serialNumber }
                : record,
            ),
          },
        }),
      UpdateProperty: (input) =>
        Effect.succeed({
          resourceRef: input.propertyRef,
          state: {
            ...state,
            properties: state.properties.map((record) =>
              record.propertyRef.resourceId === input.propertyRef.resourceId
                ? { ...record, address: input.address, name: input.name, note: input.note, updatedAt: context.now }
                : record,
            ),
          },
        }),
      UpdateUnit: (input) =>
        Effect.succeed({
          resourceRef: input.unitRef,
          state: {
            ...state,
            units: state.units.map((record) =>
              record.unitRef.resourceId === input.unitRef.resourceId
                ? { ...record, name: input.name, note: input.note }
                : record,
            ),
          },
        }),
    }),
    Match.exhaustive,
  );
});

export const persistenceService = (transaction: ScopedTransaction, scope: OperationalScope) => {
  if (scope.legalEntityId === undefined) {
    return Effect.fail(
      new OperationContextUnavailable({ code: 'operation_context_unavailable', reason: 'A Legal Entity is required' }),
    );
  }
  const { legalEntityId } = scope;
  const predicate = and(eq(propertyState.tenantId, scope.tenantId), eq(propertyState.legalEntityId, legalEntityId));
  const load = () =>
    transaction
      .select()
      .from(propertyState)
      .where(predicate)
      .limit(1)
      .pipe(
        Effect.mapError(unavailable),
        Effect.flatMap(([row]) =>
          row === undefined
            ? Effect.fail(unavailable())
            : Schema.decodeEffect(PropertyStateSchema)(row.payload).pipe(
                Effect.mapError(unavailable),
                Effect.map((state) => ({ revision: row.revision, state })),
              ),
        ),
      );
  return Effect.succeed({
    apply: Effect.fn('Property.persistence.apply')(function* applyPropertyState(input: {
      readonly command: PropertyCommand;
      readonly expectedRevision: number;
      readonly now: string;
      readonly resourceId: string;
    }) {
      const current = yield* load();
      if (current.revision !== input.expectedRevision) {
        return yield* conflict('The Property revision changed');
      }
      const next = yield* applyPropertyCommand(current.state, input.command, {
        legalEntityId,
        now: input.now,
        resourceId: input.resourceId,
        tenantId: scope.tenantId,
      });
      const rows = yield* transaction
        .update(propertyState)
        .set({
          payload: next.state,
          revision: sql`${propertyState.revision} + 1`,
          updatedAt: DateTime.toDateUtc(DateTime.makeUnsafe(input.now)),
        })
        .where(and(predicate, eq(propertyState.revision, input.expectedRevision)))
        .returning({ revision: propertyState.revision })
        .pipe(Effect.mapError(unavailable));
      if (rows[0] === undefined) {
        return yield* conflict('A concurrent Property change occurred');
      }
      return { resourceRef: next.resourceRef, revision: rows[0].revision };
    }),
    load,
  });
};
