// @generated by OntOS Codesmith Resource v1
// @ontos-resource-owner siampark.relationships
// @ontos-resource-slug activity
import type { OntosResourceType } from '@app/core-runtime';
import { Schema } from 'effect';

const ResourceIdSchema = Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(300)).pipe(
  Schema.brand('siampark.relationships.activity.ResourceId'),
);
const TenantIdSchema = Schema.String.check(Schema.isUUID()).pipe(Schema.brand('TenantId'));

export const ActivityRefSchema = Schema.Struct({
  moduleId: Schema.Literal('siampark.relationships'),
  resourceId: ResourceIdSchema,
  resourceType: Schema.Literal('siampark.relationships.activity'),
  tenantId: TenantIdSchema,
});
export type ActivityRef = typeof ActivityRefSchema.Type;

export const activityResourceDescriptor = {
  capabilities: {
    graphVisible: false,
    linkable: false,
    mediaAttachable: false,
    searchable: false,
    timelineVisible: false,
  },
  description: 'Activity resource.',
  key: 'siampark.relationships.activity',
  label: 'Activity',
  owningModuleId: 'siampark.relationships',
} as const satisfies OntosResourceType;
