// @generated by OntOS Codesmith MicroVertical Action Boundary v1
// Owner technical adapter, exposed at the generated HTTP seam.
export {
  GatewayAssertionPgClientLive,
  GatewayAssertionRedemptionDatabaseLive,
  GatewayAssertionRedemptionLive,
} from '../../src/auth/gateway-assertion-redemption-runtime.ts';
