// @generated by OntOS Codesmith Business Permission v1
// @ontos-permission-owner siampark.relationships
// @ontos-permission-code siampark.relationships.write_all
import { defineBusinessPermission } from '@app/core-runtime';

export const siamparkRelationshipsWriteAllPermission = defineBusinessPermission({
  allowedScopeKinds: ['module'],
  auditSensitivity: 'sensitive',
  authorityGroups: [],
  customerDelegable: false,
  internalGrantable: false,
  key: 'siampark.relationships.write_all',
  meaning: 'Siampark Relationships Write All module-scoped permission.',
  owningCapability: 'siampark.relationships',
  protectedEntrypoints: [],
  schemaVersion: '1',
});
