import type { Contract } from '@app/siampark-agreements/contracts/records';
// @generated by OntOS Codesmith Action Service v1
import type { OperationalScope, ReadServiceFactory } from '@app/core-runtime';
import type { CounterpartyRef } from '@app/party-registry/resources/counterparty';
import type { PartyRef } from '@app/party-registry/resources/party';
import type { ContractRef } from '@app/siampark-agreements/resources/contract';
import type { UnitRef } from '@app/siampark-property/resources/unit';
import { makeReferenceGatewayCredentialSource } from '@app/gateway-principal-verifier/server';
import {
  executeCounterpartyReadWithAuthorization,
  executePartyDetailWithAuthorization,
} from '@app/party-registry/api/client';
import { executeRecordsWithAuthorization as executePropertyRecords } from '@app/siampark-property/clients/records';
import { executeRecordsWithAuthorization as executeAgreementsRecords } from '@app/siampark-agreements/clients/records';
import { and, eq } from 'drizzle-orm';
import { DateTime, Effect, Match, Option, Schema } from 'effect';

import {
  OccupancyConflict,
  OccupancyNotFound,
  OccupancyPersistenceUnavailable,
  OccupancyRejected,
} from '../../shared/actions/apply-command.ts';
import type { OccupancyCommand, OccupancyError } from '../../shared/actions/apply-command.ts';
import { OccupancyStateSchema } from '../../shared/apis/records.ts';
import type { Occupancy, OccupancyState, RecordsRequest, RecordsResponse } from '../../shared/apis/records.ts';
import type { OccupancyRef } from '../../shared/resources/occupancy.ts';
import { occupancyState } from '../database/schema.ts';

type ScopedTransaction = Parameters<ReadServiceFactory<Readonly<Record<string, never>>>>[0];
export interface OccupancyGuardScope {
  readonly legalEntityId: string;
  readonly tenantId: string;
}
export interface OccupancyValidators {
  readonly contract: (
    ref: ContractRef,
  ) => Effect.Effect<
    Pick<Contract, 'contractRef' | 'counterpartyRef' | 'endDate' | 'kind' | 'lifecycleState' | 'startDate' | 'unitRef'>,
    OccupancyError
  >;
  readonly counterparty: (ref: CounterpartyRef) => Effect.Effect<
    {
      readonly activeCustomer: boolean;
      readonly archived: boolean;
      readonly counterpartyRef: CounterpartyRef;
      readonly legalEntityId: string;
    },
    OccupancyError
  >;
  readonly guest: (
    ref: PartyRef,
  ) => Effect.Effect<{ readonly archived: boolean; readonly partyRef: PartyRef }, OccupancyError>;
  readonly unit: (ref: UnitRef) => Effect.Effect<
    {
      readonly legalEntityId: string;
      readonly lifecycleState: string;
      readonly unitRef: UnitRef;
    },
    OccupancyError
  >;
}
export const unavailableOccupancyValidators: OccupancyValidators = {
  contract: () =>
    Effect.fail(
      new OccupancyPersistenceUnavailable({
        code: 'occupancy_persistence_unavailable',
        reason: 'Contract validation is unavailable',
      }),
    ),
  counterparty: () =>
    Effect.fail(
      new OccupancyPersistenceUnavailable({
        code: 'occupancy_persistence_unavailable',
        reason: 'Counterparty validation is unavailable',
      }),
    ),
  guest: () =>
    Effect.fail(
      new OccupancyPersistenceUnavailable({
        code: 'occupancy_persistence_unavailable',
        reason: 'Guest validation is unavailable',
      }),
    ),
  unit: () =>
    Effect.fail(
      new OccupancyPersistenceUnavailable({
        code: 'occupancy_persistence_unavailable',
        reason: 'Unit validation is unavailable',
      }),
    ),
};
const rejected = (reason: string) => new OccupancyRejected({ code: 'occupancy_rejected', reason });
const conflict = (reason: string) => new OccupancyConflict({ code: 'occupancy_conflict', reason });
const unavailable = (cause?: unknown) => {
  const error = new OccupancyPersistenceUnavailable({
    code: 'occupancy_persistence_unavailable',
    reason: 'Occupancy persistence is temporarily unavailable',
  });
  return cause === undefined
    ? error
    : Object.defineProperty(error, 'cause', { configurable: false, enumerable: false, value: cause, writable: false });
};
const refMatches = (
  left: { readonly resourceId: string; readonly tenantId: string },
  right: { readonly resourceId: string; readonly tenantId: string },
) => left.tenantId === right.tenantId && left.resourceId === right.resourceId;
export const occupancyPeriodsOverlap = (
  left: Pick<Occupancy, 'startDate' | 'endDate'>,
  right: Pick<Occupancy, 'startDate' | 'endDate'>,
) =>
  (right.endDate === null || left.startDate < right.endDate) &&
  (left.endDate === null || right.startDate < left.endDate);
export const occupancyHasConflict = (state: OccupancyState, candidate: Occupancy) =>
  state.occupancies.some(
    (other) =>
      !refMatches(other.occupancyRef, candidate.occupancyRef) &&
      refMatches(other.unitRef, candidate.unitRef) &&
      (other.state === 'CONFIRMED' || other.state === 'ACTIVE') &&
      occupancyPeriodsOverlap(other, candidate),
  );
const ensureRecordScope = (record: Occupancy, scope: OccupancyGuardScope) => {
  const refs = [
    record.occupancyRef,
    record.unitRef,
    record.customerCounterpartyRef,
    record.guestPartyRef,
    record.contractRef,
  ];
  return refs.every((ref) => ref === null || ref.tenantId === scope.tenantId)
    ? Effect.void
    : Effect.fail(rejected('scope_mismatch'));
};
const validateOccupancy = Effect.fn('Occupancy.validate')(function* validateOccupancy(
  record: Occupancy,
  scope: OccupancyGuardScope,
  validators: OccupancyValidators,
) {
  yield* ensureRecordScope(record, scope);
  if (record.endDate !== null && record.endDate <= record.startDate) {
    return yield* rejected('invalid_period');
  }
  if (
    record.kind === 'LONG_TERM_LEASE'
      ? record.customerCounterpartyRef === null || record.guestPartyRef !== null
      : record.guestPartyRef === null || record.customerCounterpartyRef !== null || record.endDate === null
  ) {
    return yield* rejected('invalid_customer_or_guest');
  }
  const unit = yield* validators.unit(record.unitRef);
  if (
    !refMatches(unit.unitRef, record.unitRef) ||
    unit.legalEntityId !== scope.legalEntityId ||
    unit.lifecycleState !== 'ACTIVE'
  ) {
    return yield* rejected('unit_not_usable');
  }
  if (record.customerCounterpartyRef !== null) {
    const customer = yield* validators.counterparty(record.customerCounterpartyRef);
    if (
      !refMatches(customer.counterpartyRef, record.customerCounterpartyRef) ||
      customer.legalEntityId !== scope.legalEntityId ||
      customer.archived ||
      !customer.activeCustomer
    ) {
      return yield* rejected('customer_not_usable');
    }
  }
  if (record.guestPartyRef !== null) {
    const guest = yield* validators.guest(record.guestPartyRef);
    if (!refMatches(guest.partyRef, record.guestPartyRef) || guest.archived) {
      return yield* rejected('guest_not_usable');
    }
  }
  return yield* Effect.void;
});
export interface OccupancyTransition {
  readonly resourceRef: OccupancyRef | null;
  readonly snapshot: OccupancyState;
}
const replaceOccupancy = (state: OccupancyState, record: Occupancy): OccupancyTransition => ({
  resourceRef: record.occupancyRef,
  snapshot: {
    ...state,
    occupancies: state.occupancies.map((value) =>
      refMatches(value.occupancyRef, record.occupancyRef) ? record : value,
    ),
  },
});
const findOccupancy = (state: OccupancyState, ref: OccupancyRef, scope: OccupancyGuardScope) => {
  if (ref.tenantId !== scope.tenantId) {
    return Effect.fail(rejected('scope_mismatch'));
  }
  const record = state.occupancies.find((value) => refMatches(value.occupancyRef, ref));
  return record === undefined
    ? Effect.fail(
        new OccupancyNotFound({
          code: 'occupancy_not_found',
          reason: 'Occupancy is not present in the authorized scope',
        }),
      )
    : Effect.succeed(record);
};
const importBooking = Effect.fn('Occupancy.importBooking')(function* importBooking(
  state: OccupancyState,
  command: Extract<OccupancyCommand, { readonly _tag: 'ImportBooking' }>,
  scope: OccupancyGuardScope,
  validators: OccupancyValidators,
  attempts: number,
) {
  yield* ensureRecordScope(command.record, scope);
  if (command.record.kind !== 'SHORT_STAY' || command.record.state !== 'CONFIRMED') {
    return yield* rejected('booking_requires_confirmed_short_stay');
  }
  if (
    state.occupancies.some(
      (value) =>
        value.externalBookingCorrelation === command.correlation ||
        refMatches(value.occupancyRef, command.record.occupancyRef),
    )
  ) {
    return yield* conflict('booking_already_imported');
  }
  if (
    attempts === 1 &&
    state.bookingObservations.some(
      (value) => value.observationId === command.observationId || value.correlation === command.correlation,
    )
  ) {
    return yield* conflict('booking_observation_already_exists');
  }
  yield* validateOccupancy(command.record, scope, validators);
  let status: 'FAILED' | 'CONFLICT' | 'SUCCESS' = 'FAILED';
  if (command.outcome === 'SUCCESS') {
    status = occupancyHasConflict(state, command.record) ? 'CONFLICT' : 'SUCCESS';
  }
  const record = { ...command.record, externalBookingCorrelation: command.correlation };
  const resourceRef = status === 'SUCCESS' ? record.occupancyRef : null;
  const observedAt = DateTime.formatIso(yield* DateTime.now);
  return {
    resourceRef,
    snapshot: {
      bookingObservations: [
        ...state.bookingObservations.filter((value) => value.observationId !== command.observationId),
        {
          attemptedAt: observedAt,
          attempts,
          completedAt: observedAt,
          correlation: command.correlation,
          integrationKind: 'BOOKING' as const,
          mode: 'SIMULATED' as const,
          observationId: command.observationId,
          occupancyRef: resourceRef,
          ownerResourceRef: resourceRef ?? record.unitRef,
          providerLabel: 'DEMO',
          requestSummary: `Unit ${record.unitRef.resourceId}; ${record.startDate} → ${record.endDate}; guests ${record.peopleCount ?? 0}`,
          resultSummary: `SIMULATED: ${status}; ${command.correlation}`,
          state: status,
        },
      ],
      occupancies: status === 'SUCCESS' ? [...state.occupancies, record] : state.occupancies,
    },
  } satisfies OccupancyTransition;
});
export const transitionOccupancy = (
  state: OccupancyState,
  command: OccupancyCommand,
  scope: OccupancyGuardScope,
  validators: OccupancyValidators,
): Effect.Effect<OccupancyTransition, OccupancyError> =>
  Match.value(command).pipe(
    Match.tag(
      'CreateDraft',
      Effect.fn('Occupancy.CreateDraft')(function* createDraft({
        record,
      }: Extract<OccupancyCommand, { readonly _tag: 'CreateDraft' }>) {
        if (record.state !== 'DRAFT' || record.contractRef !== null || record.externalBookingCorrelation !== null) {
          return yield* rejected('new_occupancy_must_be_draft');
        }
        if (state.occupancies.some((value) => refMatches(value.occupancyRef, record.occupancyRef))) {
          return yield* conflict('occupancy_already_exists');
        }
        yield* validateOccupancy(record, scope, validators);
        return {
          resourceRef: record.occupancyRef,
          snapshot: { ...state, occupancies: [...state.occupancies, record] },
        };
      }),
    ),
    Match.tag(
      'UpdateDraft',
      Effect.fn('Occupancy.UpdateDraft')(function* updateDraft({
        endDate,
        occupancyRef,
        startDate,
      }: Extract<OccupancyCommand, { readonly _tag: 'UpdateDraft' }>) {
        const record = yield* findOccupancy(state, occupancyRef, scope);
        if (record.state !== 'DRAFT') {
          return yield* conflict('update_requires_draft');
        }
        const updated = { ...record, endDate, startDate };
        yield* validateOccupancy(updated, scope, validators);
        return replaceOccupancy(state, updated);
      }),
    ),
    Match.tag(
      'Confirm',
      Effect.fn('Occupancy.Confirm')(function* confirm({
        occupancyRef,
      }: Extract<OccupancyCommand, { readonly _tag: 'Confirm' }>) {
        const record = yield* findOccupancy(state, occupancyRef, scope);
        if (record.state !== 'DRAFT') {
          return yield* conflict('confirm_requires_draft');
        }
        yield* validateOccupancy(record, scope, validators);
        if (occupancyHasConflict(state, record)) {
          return yield* conflict('occupancy_period_overlap');
        }
        return replaceOccupancy(state, { ...record, state: 'CONFIRMED' });
      }),
    ),
    Match.tag(
      'Activate',
      Effect.fn('Occupancy.Activate')(function* activate({
        contractRef,
        occupancyRef,
      }: Extract<OccupancyCommand, { readonly _tag: 'Activate' }>) {
        const record = yield* findOccupancy(state, occupancyRef, scope);
        if (record.state !== 'CONFIRMED') {
          return yield* conflict('activate_requires_confirmed');
        }
        yield* validateOccupancy(record, scope, validators);
        if (occupancyHasConflict(state, record)) {
          return yield* conflict('occupancy_period_overlap');
        }
        if (record.kind === 'LONG_TERM_LEASE') {
          if (contractRef === null || contractRef.tenantId !== scope.tenantId) {
            return yield* rejected('active_lease_requires_contract');
          }
          const contract = yield* validators.contract(contractRef);
          if (
            !refMatches(contract.contractRef, contractRef) ||
            contract.kind !== 'LEASE' ||
            contract.lifecycleState !== 'ACTIVE' ||
            contract.unitRef === null ||
            !refMatches(contract.unitRef, record.unitRef) ||
            record.customerCounterpartyRef === null ||
            !refMatches(contract.counterpartyRef, record.customerCounterpartyRef) ||
            contract.startDate > record.startDate ||
            (contract.endDate !== null && (record.endDate === null || contract.endDate < record.endDate))
          ) {
            return yield* rejected('contract_does_not_cover_lease');
          }
        } else if (contractRef !== null) {
          return yield* rejected('short_stay_does_not_require_lease_contract');
        }
        return replaceOccupancy(state, { ...record, contractRef, state: 'ACTIVE' });
      }),
    ),
    Match.tag(
      'Complete',
      Effect.fn('Occupancy.Complete')(function* complete({
        occupancyRef,
      }: Extract<OccupancyCommand, { readonly _tag: 'Complete' }>) {
        const record = yield* findOccupancy(state, occupancyRef, scope);
        if (record.state !== 'ACTIVE') {
          return yield* conflict('complete_requires_active');
        }
        return replaceOccupancy(state, { ...record, state: 'COMPLETED' });
      }),
    ),
    Match.tag(
      'Cancel',
      Effect.fn('Occupancy.Cancel')(function* cancel({
        occupancyRef,
      }: Extract<OccupancyCommand, { readonly _tag: 'Cancel' }>) {
        const record = yield* findOccupancy(state, occupancyRef, scope);
        if (record.state !== 'DRAFT' && record.state !== 'CONFIRMED') {
          return yield* conflict('cancel_requires_draft_or_confirmed');
        }
        return replaceOccupancy(state, { ...record, state: 'CANCELLED' });
      }),
    ),
    Match.tag('ImportBooking', (value) => importBooking(state, value, scope, validators, 1)),
    Match.tag(
      'RetryBooking',
      Effect.fn('Occupancy.RetryBooking')(function* retryBooking({
        observationId,
        record,
      }: Extract<OccupancyCommand, { readonly _tag: 'RetryBooking' }>) {
        const observation = state.bookingObservations.find((value) => value.observationId === observationId);
        if (observation === undefined) {
          return yield* new OccupancyNotFound({
            code: 'occupancy_not_found',
            reason: 'Booking observation was not found',
          });
        }
        if (observation.state === 'SUCCESS') {
          return yield* conflict('booking_already_imported');
        }
        if (!refMatches(observation.ownerResourceRef, record.unitRef)) {
          return yield* rejected('booking_retry_unit_mismatch');
        }
        return yield* importBooking(
          state,
          { _tag: 'ImportBooking', correlation: observation.correlation, observationId, outcome: 'SUCCESS', record },
          scope,
          validators,
          observation.attempts + 1,
        );
      }),
    ),
    Match.exhaustive,
  );
export const filterOccupancyRecords = (
  state: OccupancyState,
  revision: number,
  input: RecordsRequest,
): RecordsResponse => {
  const occupancies = state.occupancies.filter(
    (record) =>
      (input.resourceId === undefined || record.occupancyRef.resourceId === input.resourceId) &&
      (input.kind === undefined || record.kind === input.kind) &&
      (input.state === undefined || record.state === input.state) &&
      (input.unitRef === undefined || refMatches(record.unitRef, input.unitRef)) &&
      (input.fromDate === undefined || record.endDate === null || record.endDate > input.fromDate) &&
      (input.toDate === undefined || record.startDate < input.toDate),
  );
  return {
    bookingObservations:
      input.resourceId === undefined &&
      input.unitRef === undefined &&
      input.kind === undefined &&
      input.state === undefined &&
      input.fromDate === undefined &&
      input.toDate === undefined
        ? state.bookingObservations
        : state.bookingObservations.filter(
            (observation) =>
              observation.occupancyRef !== null &&
              occupancies.some(
                (record) =>
                  observation.occupancyRef !== null && refMatches(record.occupancyRef, observation.occupancyRef),
              ),
          ),
    occupancies,
    revision,
  };
};
export type OccupancyPersistence = Readonly<{
  load: () => Effect.Effect<
    { readonly revision: number; readonly snapshot: OccupancyState },
    OccupancyPersistenceUnavailable
  >;
  save: (
    snapshot: OccupancyState,
    expectedRevision: number,
  ) => Effect.Effect<number, OccupancyPersistenceUnavailable | OccupancyConflict>;
}>;
export const persistenceService = (
  transaction: ScopedTransaction,
  scope: OperationalScope,
): Effect.Effect<OccupancyPersistence, OccupancyPersistenceUnavailable> => {
  if (scope.legalEntityId === undefined) {
    return Effect.fail(unavailable());
  }
  const { legalEntityId, tenantId } = scope;
  const scopeWhere = and(eq(occupancyState.tenantId, tenantId), eq(occupancyState.legalEntityId, legalEntityId));
  return Effect.succeed({
    load: () =>
      transaction
        .select()
        .from(occupancyState)
        .where(scopeWhere)
        .limit(1)
        .pipe(
          Effect.mapError(unavailable),
          Effect.flatMap(([row]) =>
            row === undefined
              ? Effect.fail(unavailable())
              : Schema.decodeEffect(OccupancyStateSchema)(row.snapshot).pipe(
                  Effect.mapError(unavailable),
                  Effect.map((snapshot) => ({ revision: row.revision, snapshot })),
                ),
          ),
        ),
    save: (snapshot: OccupancyState, expectedRevision: number) =>
      transaction
        .update(occupancyState)
        .set({ revision: expectedRevision + 1, snapshot })
        .where(and(scopeWhere, eq(occupancyState.revision, expectedRevision)))
        .returning({ revision: occupancyState.revision })
        .pipe(
          Effect.mapError(unavailable),
          Effect.flatMap(([row]) =>
            row === undefined ? Effect.fail(conflict('stale_revision')) : Effect.succeed(row.revision),
          ),
        ),
  });
};

export const makeOccupancyValidators = Effect.fn('Occupancy.validators')(function* makeOccupancyValidators(
  scope: OperationalScope,
) {
  if (scope.legalEntityId === undefined) {
    return yield* unavailable();
  }
  const { legalEntityId } = scope;
  const source = yield* makeReferenceGatewayCredentialSource(scope).pipe(Effect.mapError(unavailable));
  return {
    contract: Effect.fn('Occupancy.contractProjection')(function* contractProjection(ref: ContractRef) {
      const target = yield* source.issue('siampark-agreements').pipe(Effect.mapError(unavailable));
      const value = yield* executeAgreementsRecords(
        { resourceId: ref.resourceId },
        target.authorization,
        scope.correlationId,
        { baseUrl: target.apiBaseUrl, compositionRevision: target.compositionRevision },
      ).pipe(Effect.mapError(unavailable));
      const contract = value.contracts.find((record) => refMatches(record.contractRef, ref));
      if (contract === undefined || contract.isExpired) {
        return yield* rejected('contract_does_not_cover_lease');
      }
      return {
        contractRef: contract.contractRef,
        counterpartyRef: contract.counterpartyRef,
        endDate: contract.endDate,
        kind: contract.kind,
        lifecycleState: contract.lifecycleState,
        startDate: contract.startDate,
        unitRef: contract.unitRef,
      };
    }),
    counterparty: Effect.fn('Occupancy.counterpartyProjection')(function* counterpartyProjection(ref: CounterpartyRef) {
      const target = yield* source.issue('party-registry');
      const value = yield* executeCounterpartyReadWithAuthorization(
        { counterpartyRef: ref },
        target.authorization,
        scope.correlationId,
        { baseUrl: target.apiBaseUrl, compositionRevision: target.compositionRevision },
      );
      return {
        activeCustomer: value.currentRoles.some((role) => role.roleType === 'CUSTOMER' && role.state === 'ACTIVE'),
        archived: value.party.archived,
        counterpartyRef: value.counterpartyRef,
        legalEntityId: value.legalEntityRef.resourceId,
      };
    }, Effect.mapError(unavailable)),
    guest: Effect.fn('Occupancy.guestProjection')(function* guestProjection(ref: PartyRef) {
      const target = yield* source.issue('party-registry');
      const value = yield* executePartyDetailWithAuthorization(
        { partyRef: ref },
        target.authorization,
        scope.correlationId,
        { baseUrl: target.apiBaseUrl, compositionRevision: target.compositionRevision },
      );
      return { archived: Option.isSome(value.party.archivedAt), partyRef: value.resolution.canonicalPartyRef };
    }, Effect.mapError(unavailable)),
    unit: Effect.fn('Occupancy.unitProjection')(function* unitProjection(ref: UnitRef) {
      const target = yield* source.issue('siampark-property').pipe(Effect.mapError(unavailable));
      const value = yield* executePropertyRecords(
        { resourceId: ref.resourceId },
        target.authorization,
        scope.correlationId,
        { baseUrl: target.apiBaseUrl, compositionRevision: target.compositionRevision },
      ).pipe(Effect.mapError(unavailable));
      const unit = value.units.find((record) => refMatches(record.unitRef, ref));
      if (unit === undefined) {
        return yield* rejected('unit_not_usable');
      }
      const parentTarget = yield* source.issue('siampark-property').pipe(Effect.mapError(unavailable));
      const parent = yield* executePropertyRecords(
        { resourceId: unit.propertyRef.resourceId },
        parentTarget.authorization,
        scope.correlationId,
        { baseUrl: parentTarget.apiBaseUrl, compositionRevision: parentTarget.compositionRevision },
      ).pipe(Effect.mapError(unavailable));
      const property = parent.properties.find((record) => refMatches(record.propertyRef, unit.propertyRef));
      if (
        property === undefined ||
        property.lifecycleState !== 'ACTIVE' ||
        property.legalEntityRef.resourceId !== legalEntityId
      ) {
        return yield* rejected('unit_not_usable');
      }
      return {
        legalEntityId: property.legalEntityRef.resourceId,
        lifecycleState: unit.lifecycleState,
        unitRef: unit.unitRef,
      };
    }),
  } satisfies OccupancyValidators;
});
