// @generated by OntOS Codesmith Resource v1
// @ontos-resource-owner siampark.billing-finance
// @ontos-resource-slug financial-plan-entry
import type { OntosResourceType } from '@app/core-runtime';
import { Schema } from 'effect';

const ResourceIdSchema = Schema.toEncoded(
  Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(300)).pipe(Schema.brand('FinanceResourceId')),
);
const TenantIdSchema = Schema.toEncoded(Schema.String.check(Schema.isUUID()).pipe(Schema.brand('FinanceTenantId')));

export const FinancialPlanEntryRefSchema = Schema.Struct({
  moduleId: Schema.Literal('siampark.billing-finance'),
  resourceId: ResourceIdSchema,
  resourceType: Schema.Literal('siampark.billing-finance.financial-plan-entry'),
  tenantId: TenantIdSchema,
});
export type FinancialPlanEntryRef = typeof FinancialPlanEntryRefSchema.Type;

export const financialPlanEntryResourceDescriptor = {
  capabilities: {
    graphVisible: false,
    linkable: false,
    mediaAttachable: false,
    searchable: false,
    timelineVisible: false,
  },
  description: 'Financial Plan Entry resource.',
  key: 'siampark.billing-finance.financial-plan-entry',
  label: 'Financial Plan Entry',
  owningModuleId: 'siampark.billing-finance',
} as const satisfies OntosResourceType;
