// @generated by OntOS Codesmith Resource v1
// @ontos-resource-owner siampark.billing-finance
// @ontos-resource-slug invoice
import type { OntosResourceType } from '@app/core-runtime';
import { Schema } from 'effect';

const ResourceIdSchema = Schema.toEncoded(
  Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(300)).pipe(Schema.brand('FinanceResourceId')),
);
const TenantIdSchema = Schema.toEncoded(Schema.String.check(Schema.isUUID()).pipe(Schema.brand('FinanceTenantId')));

export const InvoiceRefSchema = Schema.Struct({
  moduleId: Schema.Literal('siampark.billing-finance'),
  resourceId: ResourceIdSchema,
  resourceType: Schema.Literal('siampark.billing-finance.invoice'),
  tenantId: TenantIdSchema,
});
export type InvoiceRef = typeof InvoiceRefSchema.Type;

export const invoiceResourceDescriptor = {
  capabilities: {
    graphVisible: false,
    linkable: false,
    mediaAttachable: false,
    searchable: false,
    timelineVisible: false,
  },
  description: 'Invoice resource.',
  key: 'siampark.billing-finance.invoice',
  label: 'Invoice',
  owningModuleId: 'siampark.billing-finance',
} as const satisfies OntosResourceType;
