// @generated by OntOS Codesmith Resource v1
// @ontos-resource-owner siampark.agreements
// @ontos-resource-slug contract
import type { OntosResourceType } from '@app/core-runtime';
import { Schema } from 'effect';

const ResourceIdSchema = Schema.String.check(Schema.isUUID()).pipe(Schema.brand('ResourceId'));
const TenantIdSchema = Schema.String.check(Schema.isUUID()).pipe(Schema.brand('TenantId'));

export const ContractRefSchema = Schema.Struct({
  moduleId: Schema.Literal('siampark.agreements'),
  resourceId: Schema.toEncoded(ResourceIdSchema),
  resourceType: Schema.Literal('siampark.agreements.contract'),
  tenantId: Schema.toEncoded(TenantIdSchema),
});
export type ContractRef = typeof ContractRefSchema.Type;

export const contractResourceDescriptor = {
  capabilities: {
    graphVisible: false,
    linkable: false,
    mediaAttachable: false,
    searchable: false,
    timelineVisible: false,
  },
  description: 'Contract resource.',
  key: 'siampark.agreements.contract',
  label: 'Contract',
  owningModuleId: 'siampark.agreements',
} as const satisfies OntosResourceType;
