// @generated by OntOS Codesmith Resource v1
// @ontos-resource-owner siampark.agreements
// @ontos-resource-slug document
import type { OntosResourceType } from '@app/core-runtime';
import { Schema } from 'effect';

const ResourceIdSchema = Schema.String.check(Schema.isUUID()).pipe(Schema.brand('ResourceId'));
const TenantIdSchema = Schema.String.check(Schema.isUUID()).pipe(Schema.brand('TenantId'));

export const DocumentRefSchema = Schema.Struct({
  moduleId: Schema.Literal('siampark.agreements'),
  resourceId: Schema.toEncoded(ResourceIdSchema),
  resourceType: Schema.Literal('siampark.agreements.document'),
  tenantId: Schema.toEncoded(TenantIdSchema),
});
export type DocumentRef = typeof DocumentRefSchema.Type;

export const documentResourceDescriptor = {
  capabilities: {
    graphVisible: false,
    linkable: false,
    mediaAttachable: false,
    searchable: false,
    timelineVisible: false,
  },
  description: 'Document resource.',
  key: 'siampark.agreements.document',
  label: 'Document',
  owningModuleId: 'siampark.agreements',
} as const satisfies OntosResourceType;
