// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner siampark.relationships
// @ontos-action-http-slug apply-command
import type { ActionCoreError } from '@app/core-runtime';
import { Effect, HttpApiMiddleware } from '@modern-js/bff-effect/effect-edge';
import { Match, Schema } from 'effect';
import {
  ApplyCommandActionAlreadyCommittedProblemSchema,
  ApplyCommandActionAuthenticationProblemSchema,
  ApplyCommandActionCommitIndeterminateProblemSchema,
  ApplyCommandActionConflictProblemSchema,
  ApplyCommandActionForbiddenProblemSchema,
  ApplyCommandActionIneligibleProblemSchema,
  ApplyCommandActionInternalProblemSchema,
  ApplyCommandActionInvalidProblemSchema,
  ApplyCommandActionNotFoundProblemSchema,
  ApplyCommandActionPreconditionProblemSchema,
  ApplyCommandActionSchemaErrorMiddleware,
  ApplyCommandActionUnavailableProblemSchema,
} from '../shared/apis/apply-command-action.ts';
import type { ApplyCommandActionProblem } from '../shared/apis/apply-command-action.ts';
import { applyCommandAction } from '../src/actions/apply-command.action.ts';

type DomainError = typeof applyCommandAction.descriptor.domainErrorSchema.Type;
type ProblemOf<Tag extends ApplyCommandActionProblem['_tag']> = Extract<
  ApplyCommandActionProblem,
  { readonly _tag: Tag }
>;

const problemStatus = {
  authentication: 401,
  conflict: 409,
  forbidden: 403,
  ineligible: 422,
  internal: 500,
  invalid: 400,
  notFound: 404,
  precondition: 428,
  rateLimited: 429,
  timeout: 504,
  unavailable: 503,
} as const;

export const applyCommandActionProblem = {
  authentication: (): ProblemOf<'ApplyCommandActionAuthenticationProblem'> =>
    ApplyCommandActionAuthenticationProblemSchema.make({
      detail: 'A valid audience-scoped Bearer assertion is required.',
      status: problemStatus.authentication,
      title: 'Authentication required',
      type: 'https://ontos.dev/problems/operation-authentication-required',
    }),
  conflict: (
    code: ProblemOf<'ApplyCommandActionConflictProblem'>['code'],
  ): ProblemOf<'ApplyCommandActionConflictProblem'> =>
    ApplyCommandActionConflictProblemSchema.make({
      code,
      detail: 'The Action conflicts with current state.',
      status: problemStatus.conflict,
      title: 'Action conflict',
      type: 'https://ontos.dev/problems/action-conflict',
    }),
  forbidden: (
    code: ProblemOf<'ApplyCommandActionForbiddenProblem'>['code'],
  ): ProblemOf<'ApplyCommandActionForbiddenProblem'> =>
    ApplyCommandActionForbiddenProblemSchema.make({
      code,
      detail: 'The principal is not permitted to perform this Action.',
      status: problemStatus.forbidden,
      title: 'Action forbidden',
      type: 'https://ontos.dev/problems/action-forbidden',
    }),
  ineligible: (
    code: ProblemOf<'ApplyCommandActionIneligibleProblem'>['code'],
  ): ProblemOf<'ApplyCommandActionIneligibleProblem'> =>
    ApplyCommandActionIneligibleProblemSchema.make({
      code,
      detail: 'The request is not eligible for this Action.',
      status: problemStatus.ineligible,
      title: 'Action ineligible',
      type: 'https://ontos.dev/problems/action-ineligible',
    }),
  internal: (): ProblemOf<'ApplyCommandActionInternalProblem'> =>
    ApplyCommandActionInternalProblemSchema.make({
      detail: 'The Action could not be completed.',
      status: problemStatus.internal,
      title: 'Action failed',
      type: 'https://ontos.dev/problems/action-failed',
    }),
  invalid: (): ProblemOf<'ApplyCommandActionInvalidProblem'> =>
    ApplyCommandActionInvalidProblemSchema.make({
      detail: 'The apply-command Action request is invalid.',
      status: problemStatus.invalid,
      title: 'Invalid Action request',
      type: 'https://ontos.dev/problems/action-invalid',
    }),
  notFound: (
    code: ProblemOf<'ApplyCommandActionNotFoundProblem'>['code'],
  ): ProblemOf<'ApplyCommandActionNotFoundProblem'> =>
    ApplyCommandActionNotFoundProblemSchema.make({
      code,
      detail: 'The requested resource was not found.',
      status: problemStatus.notFound,
      title: 'Resource not found',
      type: 'https://ontos.dev/problems/action-resource-not-found',
    }),
  precondition: (): ProblemOf<'ApplyCommandActionPreconditionProblem'> =>
    ApplyCommandActionPreconditionProblemSchema.make({
      detail: 'An Idempotency-Key header is required.',
      status: problemStatus.precondition,
      title: 'Idempotency key required',
      type: 'https://ontos.dev/problems/idempotency-key-required',
    }),
  unavailable: (
    code: ProblemOf<'ApplyCommandActionUnavailableProblem'>['code'],
  ): ProblemOf<'ApplyCommandActionUnavailableProblem'> =>
    ApplyCommandActionUnavailableProblemSchema.make({
      code,
      detail: 'The Action capability is temporarily unavailable.',
      retryable: true,
      status: problemStatus.unavailable,
      title: 'Action unavailable',
      type: 'https://ontos.dev/problems/action-unavailable',
    }),
} as const;

const mapDomainProblem = (error: DomainError): ApplyCommandActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      ActivityPermissionDenied: () => applyCommandActionProblem.forbidden('activity_permission_denied'),
      ActivityPersistenceUnavailable: () => applyCommandActionProblem.unavailable('activity_persistence_unavailable'),
      ActivityReferenceIneligible: () => applyCommandActionProblem.ineligible('activity_reference_ineligible'),
      ActivityReferenceUnavailable: () => applyCommandActionProblem.unavailable('activity_reference_unavailable'),
      ActivityRevisionConflict: () => applyCommandActionProblem.conflict('activity_revision_conflict'),
      ActivityScopeMismatch: () => applyCommandActionProblem.forbidden('activity_scope_mismatch'),
    }),
    Match.exhaustive,
  );

const mapCoreProblem = (error: ActionCoreError): ApplyCommandActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      ActionAlreadyCommitted: (failure) =>
        ApplyCommandActionAlreadyCommittedProblemSchema.make({
          code: failure.code,
          detail: 'This Action is already committed. Refresh governed reads.',
          invocationId: failure.invocationId,
          resolution: 'REFRESH_GOVERNED_READS',
          retryCommand: false,
          status: problemStatus.conflict,
          title: 'Action already committed',
          type: 'https://ontos.dev/problems/action-already-committed',
        }),
      ActionCollectorError: applyCommandActionProblem.internal,
      ActionCommitIndeterminate: (failure) =>
        ApplyCommandActionCommitIndeterminateProblemSchema.make({
          detail: 'The Action commit is uncertain. Resolve this invocation before another attempt.',
          invocationId: failure.invocationId,
          resolution: 'RESOLVE_COMMIT',
          retryCommand: false,
          status: problemStatus.unavailable,
          title: 'Action commit uncertain',
          type: 'https://ontos.dev/problems/action-commit-indeterminate',
        }),
      ActionHandlerExecutionError: applyCommandActionProblem.internal,
      ActionIdempotencyKeyRequired: applyCommandActionProblem.precondition,
      ActionInvocationNotFound: (failure) => applyCommandActionProblem.notFound(failure.code),
      ActionInvocationPersistenceError: (failure) => applyCommandActionProblem.unavailable(failure.code),
      ActionInvocationStateError: (failure) => applyCommandActionProblem.conflict(failure.code),
      ActionPayloadValidationError: applyCommandActionProblem.invalid,
      ActionPermissionCheckError: (failure) => applyCommandActionProblem.unavailable(failure.code),
      ActionPermissionDenied: (failure) => applyCommandActionProblem.forbidden(failure.code),
      ActionPolicyDenied: (failure) => applyCommandActionProblem.ineligible(failure.code),
      ActionPolicyEvaluationError: (failure) => applyCommandActionProblem.unavailable(failure.code),
      ActionRequestHashConflict: (failure) => applyCommandActionProblem.conflict(failure.code),
      ActionResultValidationError: applyCommandActionProblem.internal,
      ActionTransactionError: (failure) => applyCommandActionProblem.unavailable(failure.code),
      ActionTrustedContextValidationError: applyCommandActionProblem.authentication,
      ModuleStateCheckUnavailableError: (failure) => applyCommandActionProblem.unavailable(failure.code),
      ModuleStateDeniedError: (failure) => applyCommandActionProblem.forbidden(failure.code),
      OperationAuthenticationRequired: applyCommandActionProblem.authentication,
      OperationContextDenied: (failure) => applyCommandActionProblem.forbidden(failure.code),
      OperationContextInvalid: (failure) => applyCommandActionProblem.forbidden(failure.code),
      OperationContextUnavailable: (failure) => applyCommandActionProblem.unavailable(failure.code),
    }),
    Match.exhaustive,
  );

const isDomainError = Schema.is(applyCommandAction.descriptor.domainErrorSchema);
export const mapApplyCommandActionProblem = (error: ActionCoreError | DomainError): ApplyCommandActionProblem =>
  isDomainError(error) ? mapDomainProblem(error) : mapCoreProblem(error);

export const applyCommandActionSchemaErrorLive = HttpApiMiddleware.layerSchemaErrorTransform(
  ApplyCommandActionSchemaErrorMiddleware,
  () => Effect.fail(applyCommandActionProblem.invalid()),
);
