import { CalendarDateWireSchema } from '@app/shared-contracts';
// @generated by OntOS Codesmith module-api v1
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';

import { PartyRefSchema } from '@app/party-registry/resources/party';
import { CounterpartyRefSchema } from '@app/party-registry/resources/counterparty';
import { OccupancyRefSchema } from '@app/siampark-occupancy/resources/occupancy';
import { PropertyRefSchema } from '@app/siampark-property/resources/property';
import { UnitRefSchema } from '@app/siampark-property/resources/unit';
import { ContractRefSchema } from '../resources/contract.ts';
import { DocumentRefSchema } from '../resources/document.ts';

export const DEMO_BUSINESS_DATE = '2026-10-05';
export const DemoDateSchema = CalendarDateWireSchema;
const TextSchema = Schema.Trim.check(Schema.isMinLength(1), Schema.isMaxLength(500));
export const ContractSchema = Schema.Struct({
  contractRef: ContractRefSchema,
  counterpartyRef: CounterpartyRefSchema,
  endDate: Schema.toEncoded(Schema.OptionFromNullOr(DemoDateSchema)),
  kind: Schema.Literals(['LEASE', 'OTHER']),
  lifecycleState: Schema.Literals(['DRAFT', 'ACTIVE', 'TERMINATED', 'EXPIRED']),
  note: Schema.toEncoded(Schema.OptionFromNullOr(TextSchema)),
  occupancyRef: Schema.toEncoded(Schema.OptionFromNullOr(OccupancyRefSchema)),
  propertyRef: Schema.toEncoded(Schema.OptionFromNullOr(PropertyRefSchema)),
  renewalNoticeDate: Schema.toEncoded(Schema.OptionFromNullOr(DemoDateSchema)),
  signatureState: Schema.Literals(['NOT_SENT', 'SENT', 'SIGNED', 'DECLINED']),
  startDate: DemoDateSchema,
  supersedesContractRef: Schema.toEncoded(Schema.OptionFromNullOr(ContractRefSchema)),
  unitRef: Schema.toEncoded(Schema.OptionFromNullOr(UnitRefSchema)),
});
export type Contract = typeof ContractSchema.Type;
export const DocumentSchema = Schema.Struct({
  contractRef: Schema.toEncoded(Schema.OptionFromNullOr(ContractRefSchema)),
  createdAt: Schema.toEncoded(Schema.DateTimeUtcFromString),
  documentRef: DocumentRefSchema,
  fileName: Schema.toEncoded(Schema.OptionFromNullOr(TextSchema)),
  kind: TextSchema,
  lifecycleState: Schema.Literals(['DRAFT', 'FINAL', 'ARCHIVED']),
  signedDocumentReference: Schema.toEncoded(Schema.OptionFromNullOr(TextSchema)),
  title: TextSchema,
  updatedAt: Schema.toEncoded(Schema.DateTimeUtcFromString),
});
export type Document = typeof DocumentSchema.Type;
export const SignatureSignerSchema = Schema.Struct({
  contact: TextSchema,
  counterpartyRef: CounterpartyRefSchema,
  displayName: Schema.toEncoded(Schema.OptionFromNullOr(TextSchema)),
  partyRef: PartyRefSchema,
});
export const SignatureObservationSchema = Schema.Struct({
  attemptedAt: Schema.toEncoded(Schema.DateTimeUtcFromString),
  completedAt: Schema.toEncoded(Schema.OptionFromNullOr(Schema.DateTimeUtcFromString)),
  contractRef: ContractRefSchema,
  correlation: TextSchema,
  documentRef: Schema.toEncoded(Schema.OptionFromNullOr(DocumentRefSchema)),
  integrationKind: Schema.Literal('ELECTRONIC_SIGNATURE'),
  mode: Schema.Literal('SIMULATED'),
  observationId: Schema.toEncoded(Schema.String.check(Schema.isUUID()).pipe(Schema.brand('ResourceId'))),
  ownerResourceRef: ContractRefSchema,
  providerLabel: TextSchema,
  requestSummary: TextSchema,
  resultSummary: TextSchema,
  signer: SignatureSignerSchema,
  state: Schema.Literals(['SENT', 'SIGNED', 'DECLINED']),
});
export const AgreementsStateSchema = Schema.Struct({
  contracts: Schema.Array(ContractSchema),
  documents: Schema.Array(DocumentSchema),
  signatureObservations: Schema.Array(SignatureObservationSchema),
});
export type AgreementsState = typeof AgreementsStateSchema.Type;
export const RecordsRequestSchema = Schema.Struct({
  expiringSoon: Schema.optionalKey(Schema.Boolean),
  kind: Schema.optionalKey(ContractSchema.fields.kind),
  resourceId: Schema.optionalKey(
    Schema.toEncoded(Schema.String.check(Schema.isUUID()).pipe(Schema.brand('ResourceId'))),
  ),
  state: Schema.optionalKey(ContractSchema.fields.lifecycleState),
});
export type RecordsRequest = typeof RecordsRequestSchema.Type;
export const ContractPresentationSchema = Schema.Struct({
  ...ContractSchema.fields,
  expiringSoon: Schema.Boolean,
  hasSuccessorDraft: Schema.Boolean,
  isExpired: Schema.Boolean,
});
export const RecordsResponseSchema = Schema.Struct({
  contracts: Schema.Array(ContractPresentationSchema),
  documents: Schema.Array(DocumentSchema),
  revision: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)),
  signatureObservations: Schema.Array(SignatureObservationSchema),
});
export type RecordsResponse = typeof RecordsResponseSchema.Type;

export const RecordsAuthenticationProblemSchema = makeProblemDetailsSchema('RecordsAuthenticationProblem', 401);
export const RecordsInvalidProblemSchema = makeProblemDetailsSchema('RecordsInvalidProblem', 400);
export const RecordsUnavailableProblemSchema = makeRetryableProblemDetailsSchema('RecordsUnavailableProblem', 503);
export const RecordsForbiddenProblemSchema = makeProblemDetailsSchema('RecordsForbiddenProblem', 403);
export const RecordsNotFoundProblemSchema = makeProblemDetailsSchema('RecordsNotFoundProblem', 404);
export const RecordsPolicyProblemSchema = makeProblemDetailsSchema('RecordsPolicyProblem', 422);
export const RecordsPolicyConflictProblemSchema = makeProblemDetailsSchema('RecordsPolicyConflictProblem', 409);
export const RecordsInternalProblemSchema = makeProblemDetailsSchema('RecordsInternalProblem', 500);

export const RecordsApi = HttpApi.make('RecordsApi').add(
  HttpApiGroup.make('records').add(
    HttpApiEndpoint.post('execute', '/reads/records', {
      error: [
        RecordsInvalidProblemSchema,
        RecordsAuthenticationProblemSchema,
        RecordsForbiddenProblemSchema,
        RecordsNotFoundProblemSchema,
        RecordsPolicyConflictProblemSchema,
        RecordsPolicyProblemSchema,
        RecordsUnavailableProblemSchema,
        RecordsInternalProblemSchema,
      ],
      payload: RecordsRequestSchema,
      success: RecordsResponseSchema,
    }),
  ),
);
