// @generated by OntOS Codesmith MicroVertical Action Boundary v1
// @ontos-action-boundary-owner siampark-property
import {
  configureDatabasePool,
  DatabaseConfig,
  GatewayAssertionRedemptionService,
  GatewayAssertionRedemptionUnavailableError,
  GatewayAssertionReplayError,
} from '@app/core-runtime';
import type { GatewayAssertionRedemption, GatewayAssertionRedemptionInput } from '@app/core-runtime';
import { GATEWAY_ASSERTION_CLOCK_SKEW_SECONDS } from '@app/shared-contracts';
import { PgClient } from '@effect/sql-pg';
import { defineRelations, lt } from 'drizzle-orm';
import { makeWithDefaults } from 'drizzle-orm/effect-postgres';
import type { EffectPgDatabase } from 'drizzle-orm/effect-postgres';
import { Clock, Context, DateTime, Duration, Effect, Layer, Redacted } from 'effect';
import { gatewayAssertionRedemptions } from '../database/schema.ts';

const gatewayRelations = defineRelations({ gatewayAssertionRedemptions });
type GatewayDatabase = EffectPgDatabase<typeof gatewayRelations>;
class GatewayRedemptionDatabase extends Context.Service<
  GatewayRedemptionDatabase,
  { readonly executor: GatewayDatabase }
>()('@app/siampark-property/auth/gateway-assertion-redemption-runtime/GatewayRedemptionDatabase') {}
const unavailable = (cause?: unknown) => {
  const error = new GatewayAssertionRedemptionUnavailableError({
    reason: 'Bearer assertion redemption is temporarily unavailable',
  });
  return cause === undefined
    ? error
    : Object.defineProperty(error, 'cause', { configurable: false, enumerable: false, value: cause, writable: false });
};
const replay = () => new GatewayAssertionReplayError({ reason: 'The Bearer assertion is no longer usable' });
export const GatewayAssertionPgClientLive = Layer.effect(
  PgClient.PgClient,
  Effect.gen(function* makeGatewayClient() {
    const configuration = yield* DatabaseConfig;
    const pool = yield* configureDatabasePool(Redacted.make(configuration.connectionString)).pipe(
      Effect.mapError(unavailable),
    );
    return yield* PgClient.make(pool).pipe(Effect.mapError(unavailable));
  }),
);
export const GatewayAssertionRedemptionDatabaseLive = Layer.effect(
  GatewayRedemptionDatabase,
  makeWithDefaults({ relations: gatewayRelations }).pipe(Effect.map((executor) => ({ executor }))),
);
const makeGatewayAssertionRedemption = (executor: GatewayDatabase): GatewayAssertionRedemption => ({
  consume: Effect.fn('PropertyGatewayRedemption.consume')(function* consume(input: GatewayAssertionRedemptionInput) {
    const now = yield* Clock.currentTimeMillis;
    if (input.expiresAtEpochSeconds + GATEWAY_ASSERTION_CLOCK_SKEW_SECONDS <= Math.floor(now / 1000)) {
      return yield* replay();
    }
    const expiredBefore = DateTime.toDateUtc(DateTime.makeUnsafe(now - GATEWAY_ASSERTION_CLOCK_SKEW_SECONDS * 1000));
    const expiresAt = DateTime.toDateUtc(DateTime.makeUnsafe(input.expiresAtEpochSeconds * 1000));
    const rows = yield* executor
      .transaction(
        Effect.fn(function* redeem(transaction) {
          yield* transaction
            .delete(gatewayAssertionRedemptions)
            .where(lt(gatewayAssertionRedemptions.expiresAt, expiredBefore));
          return yield* transaction
            .insert(gatewayAssertionRedemptions)
            .values({ audience: input.audience, expiresAt, issuer: input.issuer, jti: input.jti })
            .onConflictDoNothing()
            .returning({ jti: gatewayAssertionRedemptions.jti });
        }),
      )
      .pipe(
        Effect.mapError(unavailable),
        Effect.timeoutOrElse({ duration: Duration.seconds(5), orElse: () => Effect.fail(unavailable()) }),
      );
    if (rows.length !== 1) {
      return yield* replay();
    }
    return yield* Effect.void;
  }),
});
export const GatewayAssertionRedemptionLive = Layer.effect(
  GatewayAssertionRedemptionService,
  GatewayRedemptionDatabase.pipe(Effect.map(({ executor }) => makeGatewayAssertionRedemption(executor))),
);
