// @generated by OntOS Codesmith Action v1
// @ontos-action-owner siampark.property
// @ontos-action-slug apply-command
import { Clock, DateTime, Effect } from 'effect';
import type { ActionHandlerContext } from '@app/core-runtime';
import {
  ApplyCommandPayloadSchema,
  ApplyCommandResultSchema,
  PropertyErrorSchema,
} from '../../shared/actions/apply-command.ts';
import type { ApplyCommandPayload } from '../../shared/actions/apply-command.ts';
import { persistenceService } from '../services/persistence.service.ts';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';

const owningModuleKey = 'siampark.property';
type Services = Effect.Success<ReturnType<typeof persistenceService>>;
const handleApplyCommand = Effect.fn('Property.Action.applyCommand')(function* handlePropertyCommand(
  payload: ApplyCommandPayload,
  context: ActionHandlerContext<Readonly<Record<string, never>>, Services>,
) {
  const milliseconds = yield* Clock.currentTimeMillis;
  yield* context.recordDataAccess({
    accessKind: 'read',
    queryHash: 'property-state',
    resultCount: 1,
    servingModuleKey: owningModuleKey,
  });
  return yield* context.services.apply({
    ...payload,
    now: DateTime.formatIso(DateTime.makeUnsafe(milliseconds)),
    resourceId: context.actionInvocationId,
  });
});

export const applyCommandAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'siampark.property.apply-command.access.v1',
    },
    actionKey: 'siampark.property.apply-command',
    auditProfile: 'standard',
    domainErrorSchema: PropertyErrorSchema,
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'siampark.property.apply-command',
      moduleKey: owningModuleKey,
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'required',
    owningModuleKey,
    payloadSchema: ApplyCommandPayloadSchema,
    policies: [],
    resultSchema: ApplyCommandResultSchema,
    schemaVersion: '1',
  },
  handleApplyCommand,
  persistenceService,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
