// @generated by OntOS Codesmith MicroVertical Action Boundary v1
// @ontos-action-boundary-owner siampark-billing-finance
import {
  DatabaseConfig,
  configureDatabasePool,
  GatewayAssertionRedemptionService,
  GatewayAssertionRedemptionUnavailableError,
  GatewayAssertionReplayError,
} from '@app/core-runtime';
import type { GatewayAssertionRedemptionInput } from '@app/core-runtime';
import { GATEWAY_ASSERTION_CLOCK_SKEW_SECONDS } from '@app/shared-contracts';
import { PgClient } from '@effect/sql-pg';
import { makeWithDefaults } from 'drizzle-orm/effect-postgres';
import { lt } from 'drizzle-orm';
import { Clock, DateTime, Effect, Layer, Redacted } from 'effect';
import { settleFinanceRedemption } from '../../api/http-error-seam.ts';
import { gatewayAssertionRedemptions, financeRelations } from '../database/schema.ts';

const unavailable = (cause?: Error) =>
  Object.defineProperty(
    new GatewayAssertionRedemptionUnavailableError({
      reason: 'Bearer assertion redemption is temporarily unavailable',
    }),
    'cause',
    { value: cause },
  );
const replay = () => new GatewayAssertionReplayError({ reason: 'The Bearer assertion is no longer usable' });

export const FinanceRedemptionClientLive = Layer.effect(
  PgClient.PgClient,
  Effect.gen(function* makeClient() {
    const config = yield* DatabaseConfig;
    const pool = yield* configureDatabasePool(Redacted.make(config.connectionString)).pipe(
      Effect.mapError(unavailable),
    );
    return yield* PgClient.make(pool).pipe(Effect.mapError(unavailable));
  }),
);

// Security infrastructure runs before business scope installation. The pool is used only for
// replay evidence, never for Finance data or a business handler's persistence services.
export const GatewayAssertionRedemptionLive = Layer.effect(
  GatewayAssertionRedemptionService,
  Effect.gen(function* makeRedemption() {
    const executor = yield* makeWithDefaults({ relations: financeRelations });
    return {
      consume: Effect.fn('siampark-billing-finance.redeemAssertion')(function* consume(
        input: GatewayAssertionRedemptionInput,
      ) {
        const now = yield* Clock.currentTimeMillis;
        if (input.expiresAtEpochSeconds + GATEWAY_ASSERTION_CLOCK_SKEW_SECONDS <= Math.floor(now / 1000)) {
          return yield* replay();
        }
        const inserted = yield* executor
          .transaction(
            Effect.fn('siampark-billing-finance.redemptionTransaction')(function* redeem(transaction) {
              yield* transaction
                .delete(gatewayAssertionRedemptions)
                .where(
                  lt(
                    gatewayAssertionRedemptions.expiresAt,
                    DateTime.toDateUtc(DateTime.makeUnsafe(now - GATEWAY_ASSERTION_CLOCK_SKEW_SECONDS * 1000)),
                  ),
                );
              return yield* transaction
                .insert(gatewayAssertionRedemptions)
                .values({
                  audience: input.audience,
                  expiresAt: DateTime.toDateUtc(DateTime.makeUnsafe(input.expiresAtEpochSeconds * 1000)),
                  issuer: input.issuer,
                  jti: input.jti,
                })
                .onConflictDoNothing()
                .returning({ jti: gatewayAssertionRedemptions.jti });
            }),
          )
          .pipe(
            Effect.mapError(unavailable),
            // Native SQL settlement uses SqlError defects; preserve every unrelated defect.
            settleFinanceRedemption,
            Effect.timeoutOrElse({ duration: '5 seconds', orElse: () => Effect.fail(unavailable()) }),
          );
        if (inserted.length !== 1) {
          return yield* replay();
        }
        return yield* Effect.void;
      }),
    };
  }),
);
