// @generated by OntOS Codesmith Action Service v1
import { OperationContextUnavailable } from '@app/core-runtime';
import type { OperationalScope, ReadServiceFactory } from '@app/core-runtime';
import { and, eq } from 'drizzle-orm';
import { DateTime, Effect, Match, Schema } from 'effect';
import type { FinanceCommand, FinanceError } from '../../shared/actions/apply-command.ts';
import {
  FinanceConflict,
  FinanceNotFound,
  FinancePersistenceUnavailable,
  FinanceRejected,
} from '../../shared/actions/apply-command.ts';
import { DEMO_BUSINESS_DATE, FinanceStateSchema } from '../../shared/apis/records.ts';
import type {
  AccountingObservation,
  FinanceState,
  Invoice,
  RecordsRequest,
  RecordsResponse,
} from '../../shared/apis/records.ts';
import { financeStates } from '../database/schema.ts';

type Transaction = Parameters<ReadServiceFactory<Readonly<Record<string, never>>>>[0];
export interface FinanceScope {
  readonly legalEntityId: string;
  readonly tenantId: string;
}
export interface FinanceValidators {
  readonly invoice: (invoice: Invoice) => Effect.Effect<void, FinanceError>;
}
export interface FinanceTransition {
  readonly changed: boolean;
  readonly invoice: Invoice;
  readonly state: FinanceState;
}
const rejected = (reason: string) => new FinanceRejected({ code: 'finance_rejected', reason });
const conflict = (reason: string) => new FinanceConflict({ code: 'finance_conflict', reason });
const unavailable = (cause?: Error) =>
  Object.defineProperty(
    new FinancePersistenceUnavailable({
      code: 'finance_persistence_unavailable',
      reason: 'Finance persistence is temporarily unavailable',
    }),
    'cause',
    { value: cause },
  );
export const requireFinanceRevision = (
  currentRevision: number,
  expectedRevision: number,
): Effect.Effect<void, FinanceConflict> =>
  currentRevision === expectedRevision ? Effect.void : Effect.fail(conflict('stale_revision'));
export const derivePaymentState = (paidMinor: number, totalMinor: number): Invoice['paymentState'] => {
  if (paidMinor === 0) {
    return 'UNPAID';
  }
  return paidMinor === totalMinor ? 'PAID' : 'PARTIALLY_PAID';
};
export const matchesFinanceRef = (
  left: { readonly resourceId: string; readonly tenantId: string },
  right: { readonly resourceId: string; readonly tenantId: string },
) => left.resourceId === right.resourceId && left.tenantId === right.tenantId;
const replace = (state: FinanceState, invoice: Invoice): FinanceTransition => ({
  changed: true,
  invoice,
  state: {
    ...state,
    invoices: state.invoices.map((record) => (matchesFinanceRef(record.ref, invoice.ref) ? invoice : record)),
  },
});
const validate = Effect.fn('Finance.validate')(function* validate(
  invoice: Invoice,
  scope: FinanceScope,
  validators: FinanceValidators,
) {
  if (
    [
      invoice.ref,
      invoice.counterpartyRef,
      invoice.propertyRef,
      invoice.unitRef,
      invoice.contractRef,
      invoice.occupancyRef,
      invoice.taskRef,
    ].some((ref) => ref !== undefined && ref.tenantId !== scope.tenantId)
  ) {
    return yield* rejected('scope_mismatch');
  }
  if (invoice.dueDate < invoice.issueDate || (invoice.unitRef !== undefined && invoice.propertyRef === undefined)) {
    return yield* rejected('invalid_invoice_anchors_or_dates');
  }
  if (invoice.businessState === 'CONFIRMED' && invoice.direction === 'INCOMING' && invoice.propertyRef === undefined) {
    return yield* rejected('supplier_cost_requires_property');
  }
  return yield* validators.invoice(invoice);
});
interface FinanceTransitionContext {
  readonly input: { readonly attemptId: string; readonly now: DateTime.Utc; readonly resourceId: string };
  readonly scope: FinanceScope;
  readonly state: FinanceState;
  readonly validators: FinanceValidators;
}
const unchanged = (state: FinanceState, invoice: Invoice): FinanceTransition => ({ changed: false, invoice, state });
const findInvoice = (state: FinanceState, ref: Invoice['ref'], scope: FinanceScope) => {
  if (ref.tenantId !== scope.tenantId) {
    return Effect.fail(rejected('scope_mismatch'));
  }
  const invoice = state.invoices.find((record) => matchesFinanceRef(record.ref, ref));
  return invoice === undefined
    ? Effect.fail(
        new FinanceNotFound({ code: 'finance_not_found', reason: 'Invoice is not present in the authorized scope' }),
      )
    : Effect.succeed(invoice);
};
const handleCreateInvoiceDraft = Effect.fn('Finance.handleCreateInvoiceDraft')(function* handleCreateInvoiceDraft(
  command: Extract<FinanceCommand, { readonly _tag: 'CreateInvoiceDraft' }>,
  context: FinanceTransitionContext,
): Effect.fn.Return<FinanceTransition, FinanceError> {
  const { input, scope, state, validators } = context;

  if (
    state.invoices.some(
      (record) => record.documentNumber === command.documentNumber || record.ref.resourceId === input.resourceId,
    )
  ) {
    return yield* conflict('invoice_already_exists');
  }
  const { _tag: _commandTag, ...fields } = command;
  const invoice: Invoice = {
    ...fields,
    accountingCorrelation: `demo-accounting:${input.resourceId}`,
    accountingSyncState: 'NOT_SYNCED',
    businessState: 'DRAFT',
    createdAt: input.now,
    paidMinor: 0,
    paymentState: 'UNPAID',
    ref: {
      moduleId: 'siampark.billing-finance',
      resourceId: input.resourceId,
      resourceType: 'siampark.billing-finance.invoice',
      tenantId: scope.tenantId,
    },
    updatedAt: input.now,
  };
  yield* validate(invoice, scope, validators);
  return { changed: true, invoice, state: { ...state, invoices: [...state.invoices, invoice] } };
});

const handleUpdateInvoiceDraft = Effect.fn('Finance.handleUpdateInvoiceDraft')(function* handleUpdateInvoiceDraft(
  command: Extract<FinanceCommand, { readonly _tag: 'UpdateInvoiceDraft' }>,
  context: FinanceTransitionContext,
): Effect.fn.Return<FinanceTransition, FinanceError> {
  const { input, scope, state, validators } = context;
  const previous = yield* findInvoice(context.state, command.invoiceRef, context.scope);

  if (previous.businessState !== 'DRAFT') {
    return yield* conflict('update_requires_draft');
  }
  if (
    state.invoices.some(
      (record) => !matchesFinanceRef(record.ref, previous.ref) && record.documentNumber === command.documentNumber,
    )
  ) {
    return yield* conflict('document_number_already_exists');
  }
  const { _tag: _commandTag, invoiceRef: _invoiceRef, ...fields } = command;
  // Replace all optional draft anchors; omitted anchors are intentionally cleared.
  const {
    contractRef: _contract,
    note: _note,
    occupancyRef: _occupancy,
    propertyRef: _property,
    taskRef: _task,
    unitRef: _unit,
    ...preserved
  } = previous;
  const invoice = { ...preserved, ...fields, updatedAt: input.now };
  yield* validate(invoice, scope, validators);
  return replace(state, invoice);
});

const handleConfirmInvoice = Effect.fn('Finance.handleConfirmInvoice')(function* handleConfirmInvoice(
  command: Extract<FinanceCommand, { readonly _tag: 'ConfirmInvoice' }>,
  context: FinanceTransitionContext,
): Effect.fn.Return<FinanceTransition, FinanceError> {
  const { input, scope, state, validators } = context;
  const previous = yield* findInvoice(context.state, command.invoiceRef, context.scope);

  if (previous.businessState !== 'DRAFT') {
    return yield* conflict('confirm_requires_draft');
  }
  const invoice: Invoice = { ...previous, businessState: 'CONFIRMED', updatedAt: input.now };
  yield* validate(invoice, scope, validators);
  return replace(state, invoice);
});

const handleVoidInvoice = Effect.fn('Finance.handleVoidInvoice')(function* handleVoidInvoice(
  command: Extract<FinanceCommand, { readonly _tag: 'VoidInvoice' }>,
  context: FinanceTransitionContext,
): Effect.fn.Return<FinanceTransition, FinanceError> {
  const { input, state } = context;
  const previous = yield* findInvoice(context.state, command.invoiceRef, context.scope);

  if (previous.businessState === 'VOIDED') {
    return unchanged(state, previous);
  }
  if (
    previous.paidMinor !== 0 ||
    previous.accountingSyncState === 'PENDING' ||
    previous.accountingSyncState === 'SYNCED'
  ) {
    return yield* conflict('void_requires_unpaid_unsynchronized_invoice');
  }
  return replace(state, { ...previous, businessState: 'VOIDED', updatedAt: input.now });
});

const handleRetryAccountingSync = Effect.fn('Finance.handleRetryAccountingSync')(function* handleRetryAccountingSync(
  command: Extract<FinanceCommand, { readonly _tag: 'RequestAccountingSync' | 'RetryAccountingSync' }>,
  context: FinanceTransitionContext,
): Effect.fn.Return<FinanceTransition, FinanceError> {
  const { input, state } = context;
  const previous = yield* findInvoice(context.state, command.invoiceRef, context.scope);

  if (previous.businessState !== 'CONFIRMED') {
    return yield* conflict('accounting_requires_confirmed_invoice');
  }
  if (previous.accountingSyncState === 'SYNCED') {
    return unchanged(state, previous);
  }
  const required = Match.value(command).pipe(
    Match.tag('RetryAccountingSync', () => 'FAILED' as const),
    Match.tag('RequestAccountingSync', () => 'NOT_SYNCED' as const),
    Match.exhaustive,
  );
  if (previous.accountingSyncState !== required) {
    return yield* conflict('accounting_state_does_not_allow_request');
  }
  const changed = replace(state, { ...previous, accountingSyncState: 'PENDING', updatedAt: input.now });
  return {
    ...changed,
    state: {
      ...changed.state,
      accountingObservations: [
        ...state.accountingObservations.map((observation) =>
          observation.correlation === previous.accountingCorrelation ? { ...observation, latest: false } : observation,
        ),
        {
          attemptedAt: input.now,
          attemptId: input.attemptId,
          correlation: previous.accountingCorrelation,
          integrationKind: 'ACCOUNTING',
          invoiceRef: previous.ref,
          latest: true,
          mode: 'SIMULATED',
          providerLabel: 'DEMO',
          requestSummary: 'Simulated accounting export of an existing invoice',
          resultSummary: 'Awaiting simulated accounting result',
          revision: 1,
          status: 'PENDING',
        },
      ],
    },
  };
});

const handleApplyAccountingObservation = Effect.fn('Finance.handleApplyAccountingObservation')(
  function* handleApplyAccountingObservation(
    command: Extract<FinanceCommand, { readonly _tag: 'ApplyAccountingObservation' }>,
    context: FinanceTransitionContext,
  ): Effect.fn.Return<FinanceTransition, FinanceError> {
    const { input, state } = context;
    const previous = yield* findInvoice(context.state, command.invoiceRef, context.scope);

    const duplicate = state.accountingObservations.find((observation) => observation.resultId === command.resultId);
    if (duplicate !== undefined) {
      if (
        !matchesFinanceRef(duplicate.invoiceRef, previous.ref) ||
        duplicate.correlation !== command.correlation ||
        duplicate.status !== command.status ||
        duplicate.receipt !== command.receipt
      ) {
        return yield* conflict('accounting_result_id_reused');
      }
      return unchanged(state, previous);
    }
    if (
      previous.businessState !== 'CONFIRMED' ||
      previous.accountingSyncState !== 'PENDING' ||
      command.correlation !== previous.accountingCorrelation
    ) {
      return yield* conflict('accounting_result_requires_matching_pending_attempt');
    }
    if (command.status === 'SUCCESS' && command.receipt === undefined) {
      return yield* rejected('successful_accounting_requires_receipt');
    }
    const latest = state.accountingObservations.find(
      (observation) =>
        observation.latest &&
        observation.correlation === command.correlation &&
        observation.status === 'PENDING' &&
        matchesFinanceRef(observation.invoiceRef, previous.ref),
    );
    if (latest === undefined) {
      return yield* conflict('accounting_pending_attempt_missing');
    }
    const terminalInvoice: Invoice = {
      ...previous,
      accountingSyncState: command.status === 'SUCCESS' ? 'SYNCED' : 'FAILED',
      updatedAt: input.now,
    };
    const invoice: Invoice =
      command.status === 'SUCCESS' && command.receipt !== undefined
        ? { ...terminalInvoice, externalAccountingReference: command.receipt }
        : terminalInvoice;
    const changed = replace(state, invoice);
    const completedObservation: AccountingObservation = {
      ...latest,
      completedAt: input.now,
      resultId: command.resultId,
      resultSummary:
        command.status === 'SUCCESS'
          ? 'Simulated accounting acknowledged the existing invoice'
          : 'Simulated accounting export failed',
      revision: latest.revision + 1,
      status: command.status,
    };
    const terminalObservation =
      command.receipt === undefined ? completedObservation : { ...completedObservation, receipt: command.receipt };
    return {
      ...changed,
      state: {
        ...changed.state,
        accountingObservations: state.accountingObservations.map((observation) =>
          observation === latest ? terminalObservation : observation,
        ),
      },
    };
  },
);

const handleApplyPaymentObservation = Effect.fn('Finance.handleApplyPaymentObservation')(
  function* handleApplyPaymentObservation(
    command: Extract<FinanceCommand, { readonly _tag: 'ApplyPaymentObservation' }>,
    context: FinanceTransitionContext,
  ): Effect.fn.Return<FinanceTransition, FinanceError> {
    const { input, state } = context;
    const previous = yield* findInvoice(context.state, command.invoiceRef, context.scope);

    const duplicate = state.paymentObservations.find((observation) => observation.resultId === command.resultId);
    if (duplicate !== undefined) {
      if (
        !matchesFinanceRef(duplicate.invoiceRef, previous.ref) ||
        duplicate.correlation !== command.correlation ||
        duplicate.confirmedPaidMinor !== command.confirmedPaidMinor ||
        duplicate.currency !== command.currency
      ) {
        return yield* conflict('payment_result_id_reused');
      }
      return unchanged(state, previous);
    }
    if (
      state.paymentObservations.some(
        (observation) =>
          matchesFinanceRef(observation.invoiceRef, previous.ref) && observation.correlation !== command.correlation,
      )
    ) {
      return yield* conflict('payment_correlation_mismatch');
    }
    if (
      previous.businessState !== 'CONFIRMED' ||
      command.confirmedPaidMinor < previous.paidMinor ||
      command.confirmedPaidMinor > previous.totalMinor ||
      command.currency !== previous.currency ||
      !Number.isSafeInteger(command.confirmedPaidMinor) ||
      command.confirmedPaidMinor < 0
    ) {
      return yield* rejected('invalid_cumulative_payment');
    }
    const invoice: Invoice = {
      ...previous,
      paidMinor: command.confirmedPaidMinor,
      paymentState: derivePaymentState(command.confirmedPaidMinor, previous.totalMinor),
      updatedAt: input.now,
    };
    const changed = replace(state, invoice);
    return {
      ...changed,
      state: {
        ...changed.state,
        paymentObservations: [
          ...state.paymentObservations,
          {
            confirmedPaidMinor: command.confirmedPaidMinor,
            correlation: command.correlation,
            currency: command.currency,
            invoiceRef: previous.ref,
            mode: 'SIMULATED',
            observedAt: input.now,
            resultId: command.resultId,
          },
        ],
      },
    };
  },
);

export const transitionFinance = (
  state: FinanceState,
  request: FinanceCommand,
  scope: FinanceScope,
  validators: FinanceValidators,
  input: FinanceTransitionContext['input'],
): Effect.Effect<FinanceTransition, FinanceError> => {
  const context: FinanceTransitionContext = { input, scope, state, validators };
  return Match.value(request).pipe(
    Match.tag('CreateInvoiceDraft', (command) => handleCreateInvoiceDraft(command, context)),
    Match.tag('UpdateInvoiceDraft', (command) => handleUpdateInvoiceDraft(command, context)),
    Match.tag('ConfirmInvoice', (command) => handleConfirmInvoice(command, context)),
    Match.tag('VoidInvoice', (command) => handleVoidInvoice(command, context)),
    Match.tag('RequestAccountingSync', 'RetryAccountingSync', (command) => handleRetryAccountingSync(command, context)),
    Match.tag('ApplyAccountingObservation', (command) => handleApplyAccountingObservation(command, context)),
    Match.tag('ApplyPaymentObservation', (command) => handleApplyPaymentObservation(command, context)),
    Match.exhaustive,
  );
};

export const projectFinanceRecords = (
  state: FinanceState,
  revision: number,
  request: RecordsRequest,
): Omit<RecordsResponse, 'canWrite'> => {
  const invoices = state.invoices.filter(
    (record) =>
      (request.resourceId === undefined || record.ref.resourceId === request.resourceId) &&
      (request.propertyId === undefined || record.propertyRef?.resourceId === request.propertyId),
  );
  const selected = new Set(invoices.map((record) => record.ref.resourceId));
  const financialPlanEntries = state.financialPlanEntries.filter(
    (record) =>
      (request.propertyId === undefined || record.propertyRef.resourceId === request.propertyId) &&
      (request.resourceId === undefined || record.ref.resourceId === request.resourceId),
  );
  const accountingObservations = state.accountingObservations.filter((record) =>
    selected.has(record.invoiceRef.resourceId),
  );
  const paymentObservations = state.paymentObservations.filter((record) => selected.has(record.invoiceRef.resourceId));
  const confirmed = invoices.filter((record) => record.businessState === 'CONFIRMED');
  const actuals = confirmed.filter((record) => record.issueDate >= '2026-01-01' && record.issueDate < '2027-01-01');
  const outstanding = confirmed.filter((record) => record.paidMinor < record.totalMinor);
  const plans = financialPlanEntries.filter(
    (record) =>
      record.state === 'CONFIRMED' &&
      record.periodStart >= '2026-01-01' &&
      record.periodStart < '2027-01-01' &&
      record.periodEndExclusive > record.periodStart,
  );
  const sumActual = (direction: Invoice['direction']) =>
    actuals.filter((record) => record.direction === direction).reduce((sum, record) => sum + record.totalMinor, 0);
  const sumOutstanding = (direction: Invoice['direction']) =>
    outstanding
      .filter((record) => record.direction === direction)
      .reduce((sum, record) => sum + record.totalMinor - record.paidMinor, 0);
  const sumPlan = (kind: 'COST' | 'REVENUE') =>
    plans.filter((record) => record.kind === kind).reduce((sum, record) => sum + record.plannedMinor, 0);
  const costMinor = sumActual('INCOMING');
  const revenueMinor = sumActual('OUTGOING');
  const plannedCostMinor = sumPlan('COST');
  const plannedRevenueMinor = sumPlan('REVENUE');
  const payablesOutstandingMinor = sumOutstanding('INCOMING');
  const receivablesOutstandingMinor = sumOutstanding('OUTGOING');
  return {
    indicators: {
      costMinor,
      costVarianceMinor: costMinor - plannedCostMinor,
      grossOutstandingMinor: payablesOutstandingMinor + receivablesOutstandingMinor,
      integrationWarnings: new Set(
        accountingObservations.flatMap((record) =>
          record.latest && record.status === 'FAILED' ? [record.correlation] : [],
        ),
      ).size,
      openIncomingInvoices: outstanding.filter((record) => record.direction === 'INCOMING').length,
      openInvoices: outstanding.length,
      openOutgoingInvoices: outstanding.filter((record) => record.direction === 'OUTGOING').length,
      overdueInvoices: outstanding.filter((record) => record.dueDate < DEMO_BUSINESS_DATE).length,
      payablesOutstandingMinor,
      plannedCostMinor,
      plannedRevenueMinor,
      receivablesOutstandingMinor,
      revenueMinor,
      revenueVarianceMinor: revenueMinor - plannedRevenueMinor,
    },
    referenceDate: DEMO_BUSINESS_DATE,
    revision,
    state: { accountingObservations, financialPlanEntries, invoices, paymentObservations },
  };
};
export const persistenceService = (transaction: Transaction, scope: OperationalScope) => {
  if (scope.legalEntityId === undefined) {
    return Effect.fail(
      new OperationContextUnavailable({
        code: 'operation_context_unavailable',
        reason: 'A Legal Entity scope is required',
      }),
    );
  }
  const scopeWhere = and(
    eq(financeStates.tenantId, scope.tenantId),
    eq(financeStates.legalEntityId, scope.legalEntityId),
  );
  return Effect.succeed({
    load: () =>
      transaction
        .select()
        .from(financeStates)
        .where(scopeWhere)
        .limit(1)
        .pipe(
          Effect.mapError(unavailable),
          Effect.flatMap(([row]) =>
            row === undefined
              ? Effect.fail(unavailable())
              : Schema.decodeEffect(FinanceStateSchema)(row.state).pipe(
                  Effect.mapError(unavailable),
                  Effect.map((state) => ({ revision: row.revision, state })),
                ),
          ),
        ),
    save: Effect.fn('Finance.save')(function* save(state: FinanceState, expectedRevision: number) {
      const encoded = yield* Schema.encodeEffect(FinanceStateSchema)(state).pipe(Effect.mapError(unavailable));
      const now = yield* DateTime.now;
      const rows = yield* transaction
        .update(financeStates)
        .set({ revision: expectedRevision + 1, state: encoded, updatedAt: DateTime.toDateUtc(now) })
        .where(and(scopeWhere, eq(financeStates.revision, expectedRevision)))
        .returning({ revision: financeStates.revision })
        .pipe(Effect.mapError(unavailable));
      const [row] = rows;
      if (row === undefined) {
        return yield* conflict('stale_revision');
      }
      return row.revision;
    }),
  });
};
