// @generated by @modern-js/ultramodern-create.
// Author route metadata in colocated src/routes/**/route.meta.ts files.
// This compatibility manifest is regenerated from route-owned metadata.

export const ultramodernRouteNamespace = 'assortment' as const;

export const ultramodernRouteMetadata = [
  {
    canonicalPath: '/',
    descriptionKey: 'assortment.seo.description',
    entrypoint: {
      access: 'read',
      authorization: {
        kind: 'context_permission',
        permission: 'assortment.configuration.read',
      },
      entrypointKey: 'commerce.assortment.page.assortment-home',
      moduleKey: 'commerce.assortment',
      role: 'page',
      scope: 'tenant',
    },
    id: 'assortment-home',
    indexable: false,
    localisedPaths: {
      cs: '/',
      en: '/',
    },
    mfBoundaryId: 'verticalAssortment',
    moduleId: 'commerce.assortment',
    namespace: 'assortment',
    ownerAppId: 'assortment',
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'assortment.title',
  },
] as const;

export const ultramodernLocalisedUrls = {} as const;
