// @generated by OntOS Codesmith module-api v1
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { CalendarDateWireSchema } from '@app/shared-contracts';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';
import { LegalEntityRefSchema } from '@app/core-runtime/resources/legal-entity';
import { PropertyRefSchema } from '../resources/property.ts';
import { UnitRefSchema } from '../resources/unit.ts';
import { AssetRefSchema } from '../resources/asset.ts';

export const PropertyLifecycleSchema = Schema.Literals(['PLANNED', 'ACTIVE', 'INACTIVE', 'DISPOSED']);
export const UnitLifecycleSchema = Schema.Literals(['ACTIVE', 'OUT_OF_SERVICE', 'RETIRED']);
export const AssetLifecycleSchema = Schema.Literals(['ACTIVE', 'IN_SERVICE', 'OUT_OF_SERVICE', 'DISPOSED']);
export const PropertyTextSchema = Schema.Trim.check(Schema.isNonEmpty(), Schema.isMaxLength(300));
export const PropertyDateSchema = CalendarDateWireSchema;
export const PropertyInstantSchema = Schema.toEncoded(Schema.DateTimeUtcFromString);
export const PropertyRecordSchema = Schema.Struct({
  address: PropertyTextSchema,
  code: PropertyTextSchema,
  createdAt: PropertyInstantSchema,
  legalEntityRef: LegalEntityRefSchema,
  lifecycleState: PropertyLifecycleSchema,
  name: PropertyTextSchema,
  note: Schema.toEncoded(Schema.OptionFromNullOr(Schema.String)),
  propertyRef: PropertyRefSchema,
  updatedAt: PropertyInstantSchema,
});
export const UnitRecordSchema = Schema.Struct({
  capacity: Schema.toEncoded(Schema.OptionFromNullOr(Schema.Int.check(Schema.isGreaterThan(0)))),
  code: PropertyTextSchema,
  lifecycleState: UnitLifecycleSchema,
  name: PropertyTextSchema,
  note: Schema.toEncoded(Schema.OptionFromNullOr(Schema.String)),
  propertyRef: PropertyRefSchema,
  unitKind: Schema.toEncoded(Schema.OptionFromNullOr(PropertyTextSchema)),
  unitRef: UnitRefSchema,
});
export const AssetRecordSchema = Schema.Struct({
  acquiredAt: Schema.toEncoded(Schema.OptionFromNullOr(PropertyDateSchema)),
  assetRef: AssetRefSchema,
  category: PropertyTextSchema,
  code: PropertyTextSchema,
  lastServiceAt: Schema.toEncoded(Schema.OptionFromNullOr(PropertyDateSchema)),
  lifecycleState: AssetLifecycleSchema,
  name: PropertyTextSchema,
  nextServiceAt: Schema.toEncoded(Schema.OptionFromNullOr(PropertyDateSchema)),
  propertyRef: PropertyRefSchema,
  serialNumber: Schema.toEncoded(Schema.OptionFromNullOr(PropertyTextSchema)),
  unitRef: Schema.toEncoded(Schema.OptionFromNullOr(UnitRefSchema)),
});
export const PropertyStateSchema = Schema.Struct({
  assets: Schema.Array(AssetRecordSchema),
  properties: Schema.Array(PropertyRecordSchema),
  units: Schema.Array(UnitRecordSchema),
});
export type PropertyState = typeof PropertyStateSchema.Type;
export const RecordsRequestSchema = Schema.Struct({
  propertyId: Schema.optionalKey(
    Schema.toEncoded(Schema.String.check(Schema.isUUID()).pipe(Schema.brand('ResourceId'))),
  ),
  resourceId: Schema.optionalKey(
    Schema.toEncoded(Schema.String.check(Schema.isUUID()).pipe(Schema.brand('ResourceId'))),
  ),
});
export type RecordsRequest = typeof RecordsRequestSchema.Type;
export const RecordsResponseSchema = Schema.Struct({
  assets: Schema.Array(AssetRecordSchema),
  properties: Schema.Array(PropertyRecordSchema),
  revision: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)),
  units: Schema.Array(UnitRecordSchema),
});
export type RecordsResponse = typeof RecordsResponseSchema.Type;

export const RecordsAuthenticationProblemSchema = makeProblemDetailsSchema('RecordsAuthenticationProblem', 401);
export const RecordsInvalidProblemSchema = makeProblemDetailsSchema('RecordsInvalidProblem', 400);
export const RecordsUnavailableProblemSchema = makeRetryableProblemDetailsSchema('RecordsUnavailableProblem', 503);
export const RecordsForbiddenProblemSchema = makeProblemDetailsSchema('RecordsForbiddenProblem', 403);
export const RecordsNotFoundProblemSchema = makeProblemDetailsSchema('RecordsNotFoundProblem', 404);
export const RecordsPolicyProblemSchema = makeProblemDetailsSchema('RecordsPolicyProblem', 422);
export const RecordsPolicyConflictProblemSchema = makeProblemDetailsSchema('RecordsPolicyConflictProblem', 409);
export const RecordsInternalProblemSchema = makeProblemDetailsSchema('RecordsInternalProblem', 500);

export const RecordsApi = HttpApi.make('RecordsApi').add(
  HttpApiGroup.make('records').add(
    HttpApiEndpoint.post('execute', '/reads/records', {
      error: [
        RecordsInvalidProblemSchema,
        RecordsAuthenticationProblemSchema,
        RecordsForbiddenProblemSchema,
        RecordsNotFoundProblemSchema,
        RecordsPolicyConflictProblemSchema,
        RecordsPolicyProblemSchema,
        RecordsUnavailableProblemSchema,
        RecordsInternalProblemSchema,
      ],
      payload: RecordsRequestSchema,
      success: RecordsResponseSchema,
    }),
  ),
);
