// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner siampark.relationships
// @ontos-action-http-slug apply-command
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { HttpApi, HttpApiEndpoint, HttpApiGroup, Schema } from '@modern-js/bff-effect/effect-client';
import { HttpApiMiddleware } from 'effect/unstable/httpapi';
import { ApplyCommandPayloadSchema, ApplyCommandResultSchema } from '../actions/apply-command.ts';

export { ApplyCommandPayloadSchema } from '../actions/apply-command.ts';

export const ApplyCommandActionInvalidProblemSchema = makeProblemDetailsSchema('ApplyCommandActionInvalidProblem', 400);
export const ApplyCommandActionAuthenticationProblemSchema = makeProblemDetailsSchema(
  'ApplyCommandActionAuthenticationProblem',
  401,
);
export const ApplyCommandActionForbiddenProblemSchema = makeProblemDetailsSchema(
  'ApplyCommandActionForbiddenProblem',
  403,
  {
    code: Schema.Literals([
      'action_permission_denied',
      'module_state_denied',
      'operation_context_denied',
      'operation_context_invalid',
      'activity_permission_denied',
      'activity_scope_mismatch',
    ]),
  },
);
export const ApplyCommandActionNotFoundProblemSchema = makeProblemDetailsSchema(
  'ApplyCommandActionNotFoundProblem',
  404,
  { code: Schema.Literal('action_invocation_not_found') },
);
export const ApplyCommandActionConflictProblemSchema = makeProblemDetailsSchema(
  'ApplyCommandActionConflictProblem',
  409,
  {
    code: Schema.Literals([
      'action_request_hash_conflict',
      'action_invocation_state_invalid',
      'activity_revision_conflict',
    ]),
  },
);
export const ApplyCommandActionIneligibleProblemSchema = makeProblemDetailsSchema(
  'ApplyCommandActionIneligibleProblem',
  422,
  { code: Schema.Literals(['action_policy_denied', 'activity_reference_ineligible']) },
);
export const ApplyCommandActionPreconditionProblemSchema = makeProblemDetailsSchema(
  'ApplyCommandActionPreconditionProblem',
  428,
);
export const ApplyCommandActionUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'ApplyCommandActionUnavailableProblem',
  503,
  {
    code: Schema.Literals([
      'action_invocation_persistence_failed',
      'action_permission_check_failed',
      'action_policy_evaluation_failed',
      'action_transaction_failed',
      'module_state_check_unavailable',
      'operation_context_unavailable',
      'activity_persistence_unavailable',
      'activity_reference_unavailable',
    ]),
  },
);
export const ApplyCommandActionAlreadyCommittedProblemSchema = makeProblemDetailsSchema(
  'ApplyCommandActionAlreadyCommittedProblem',
  409,
  {
    code: Schema.Literal('action_already_committed'),
    invocationId: Schema.String,
    resolution: Schema.Literal('REFRESH_GOVERNED_READS'),
    retryCommand: Schema.Literal(false),
  },
);
export const ApplyCommandActionCommitIndeterminateProblemSchema = makeProblemDetailsSchema(
  'ApplyCommandActionCommitIndeterminateProblem',
  503,
  {
    invocationId: Schema.String,
    resolution: Schema.Literal('RESOLVE_COMMIT'),
    retryCommand: Schema.Literal(false),
  },
);
export const ApplyCommandActionInternalProblemSchema = makeProblemDetailsSchema(
  'ApplyCommandActionInternalProblem',
  500,
);

export type ApplyCommandActionProblem =
  | typeof ApplyCommandActionInvalidProblemSchema.Type
  | typeof ApplyCommandActionAuthenticationProblemSchema.Type
  | typeof ApplyCommandActionForbiddenProblemSchema.Type
  | typeof ApplyCommandActionNotFoundProblemSchema.Type
  | typeof ApplyCommandActionConflictProblemSchema.Type
  | typeof ApplyCommandActionIneligibleProblemSchema.Type
  | typeof ApplyCommandActionPreconditionProblemSchema.Type
  | typeof ApplyCommandActionUnavailableProblemSchema.Type
  | typeof ApplyCommandActionAlreadyCommittedProblemSchema.Type
  | typeof ApplyCommandActionCommitIndeterminateProblemSchema.Type
  | typeof ApplyCommandActionInternalProblemSchema.Type;

export class ApplyCommandActionSchemaErrorMiddleware extends HttpApiMiddleware.Service<ApplyCommandActionSchemaErrorMiddleware>()(
  'siampark-relationships/ApplyCommandActionSchemaErrorMiddleware',
  { error: ApplyCommandActionInvalidProblemSchema },
) {}

const actionErrors = [
  ApplyCommandActionInvalidProblemSchema,
  ApplyCommandActionAuthenticationProblemSchema,
  ApplyCommandActionForbiddenProblemSchema,
  ApplyCommandActionNotFoundProblemSchema,
  ApplyCommandActionConflictProblemSchema,
  ApplyCommandActionIneligibleProblemSchema,
  ApplyCommandActionPreconditionProblemSchema,
  ApplyCommandActionUnavailableProblemSchema,
  ApplyCommandActionAlreadyCommittedProblemSchema,
  ApplyCommandActionCommitIndeterminateProblemSchema,
  ApplyCommandActionInternalProblemSchema,
] as const;

/**
 * The endpoint chain stays a `const`. The MicroVertical API boundary checker walks a root API's
 * operands through const bindings only, so a class declaration hides the composed endpoints from
 * it. The exported group is annotated with a named type alias so its type still has a name: the
 * vertical's `shared/api.ts` merges every group type into one `HttpApi` and declaration emit
 * serializes that union verbatim, so an anonymous group type pushes the composed contract past
 * the compiler's serialization limit (TS7056).
 *
 * Exported only so the named contract type can reference it; the merged vertical HttpApi prints
 * this group by name (declaration-emit size).
 *
 * @public
 */
export const applyCommandActionGroupDefinition = HttpApiGroup.make('applyCommandAction')
  .add(
    HttpApiEndpoint.post('execute', '/siampark-relationships/actions/apply-command', {
      error: actionErrors,
      payload: Schema.toEncoded(ApplyCommandPayloadSchema),
      success: ApplyCommandResultSchema,
    }),
  )
  .middleware(ApplyCommandActionSchemaErrorMiddleware);

export type ApplyCommandActionGroupContract = HttpApiGroup.HttpApiGroup<
  'applyCommandAction',
  HttpApiGroup.Endpoints<typeof applyCommandActionGroupDefinition>
>;

const ApplyCommandActionGroup: ApplyCommandActionGroupContract = applyCommandActionGroupDefinition;

export const ApplyCommandActionApi = HttpApi.make('ApplyCommandActionApi').add(ApplyCommandActionGroup);
