import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { DateTime, Schema } from 'effect';
import { PrincipalRefSchema } from '@app/core-runtime/permissions/principal-ref';
import { CounterpartyRefSchema } from '@app/party-registry/resources/counterparty';
import { PartyRefSchema } from '@app/party-registry/resources/party';
import { TaskRefSchema } from '@app/siampark-work/resources/task';
import { ActivityRefSchema } from '../resources/activity.ts';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';

// @generated by OntOS Codesmith module-api v1

export const ActivityKindSchema = Schema.Literals(['CALL', 'EMAIL', 'MEETING', 'NOTE']);
export const ContextRefSchema = Schema.Never;
export const ActivitySchema = Schema.Struct({
  contextRefs: Schema.Array(ContextRefSchema).check(Schema.isMaxLength(12)),
  counterpartyRef: Schema.optionalKey(CounterpartyRefSchema),
  createdAt: Schema.DateTimeUtcFromString,
  followUpTaskRef: Schema.optionalKey(TaskRefSchema),
  kind: ActivityKindSchema,
  occurredAt: Schema.DateTimeUtcFromString,
  ownerPrincipalRef: PrincipalRefSchema,
  partyRef: Schema.optionalKey(PartyRefSchema),
  ref: ActivityRefSchema,
  summary: Schema.Trim.check(Schema.isMinLength(1), Schema.isMaxLength(2000)),
}).check(
  Schema.makeFilter((activity) =>
    activity.partyRef !== undefined || activity.counterpartyRef !== undefined
      ? undefined
      : 'Activity must identify a Party or Counterparty',
  ),
);
export type Activity = typeof ActivitySchema.Type;
const EmailObservationIdSchema = Schema.String.check(Schema.isUUID()).pipe(
  Schema.brand('siampark.relationships.EmailObservationId'),
);
export const EmailObservationSchema = Schema.Struct({
  attemptedAt: Schema.DateTimeUtcFromString,
  completedAt: Schema.DateTimeUtcFromString,
  correlation: Schema.Trim.check(Schema.isMinLength(1), Schema.isMaxLength(500)),
  integrationKind: Schema.Literal('EMAIL'),
  mode: Schema.Literal('SIMULATED'),
  observationId: EmailObservationIdSchema,
  ownerResourceRef: ActivityRefSchema,
  providerLabel: Schema.Literal('DEMO'),
  receipt: Schema.Trim.check(Schema.isMinLength(1), Schema.isMaxLength(500)),
  requestSummary: Schema.Trim.check(Schema.isMinLength(1), Schema.isMaxLength(1000)),
  resultSummary: Schema.Trim.check(Schema.isMinLength(1), Schema.isMaxLength(1000)),
  status: Schema.Literal('SUCCESS'),
}).check(
  Schema.makeFilter((observation) =>
    DateTime.toEpochMillis(observation.completedAt) >= DateTime.toEpochMillis(observation.attemptedAt)
      ? undefined
      : 'Email completion cannot precede its attempt',
  ),
);
export type EmailObservation = typeof EmailObservationSchema.Type;
export const RelationshipsStateSchema = Schema.Struct({
  activities: Schema.Array(ActivitySchema),
  emailObservations: Schema.Array(EmailObservationSchema),
}).check(
  Schema.makeFilter((state) =>
    state.emailObservations.every((observation) =>
      state.activities.some(
        ({ ref }) =>
          ref.resourceId === observation.ownerResourceRef.resourceId &&
          ref.tenantId === observation.ownerResourceRef.tenantId,
      ),
    )
      ? undefined
      : 'Email observations must identify an existing Activity in the same tenant',
  ),
);
export type RelationshipsState = typeof RelationshipsStateSchema.Type;
export const RecordsRequestSchema = Schema.Struct({
  counterpartyId: Schema.optionalKey(CounterpartyRefSchema.fields.resourceId),
  partyId: Schema.optionalKey(PartyRefSchema.fields.resourceId),
  resourceId: Schema.optionalKey(ActivityRefSchema.fields.resourceId),
});
export type RecordsRequest = typeof RecordsRequestSchema.Type;
export type RecordsRequestEncoded = typeof RecordsRequestSchema.Encoded;
export const RecordsResponseSchema = Schema.Struct({
  actorPrincipalRef: PrincipalRefSchema,
  canWrite: Schema.Boolean,
  emailObservations: Schema.Array(EmailObservationSchema),
  items: Schema.Array(ActivitySchema),
  revision: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)),
});
export type RecordsResponse = typeof RecordsResponseSchema.Type;

export const RecordsAuthenticationProblemSchema = makeProblemDetailsSchema('RecordsAuthenticationProblem', 401);
export const RecordsInvalidProblemSchema = makeProblemDetailsSchema('RecordsInvalidProblem', 400);
export const RecordsUnavailableProblemSchema = makeRetryableProblemDetailsSchema('RecordsUnavailableProblem', 503);
export const RecordsForbiddenProblemSchema = makeProblemDetailsSchema('RecordsForbiddenProblem', 403);
export const RecordsNotFoundProblemSchema = makeProblemDetailsSchema('RecordsNotFoundProblem', 404);
export const RecordsPolicyProblemSchema = makeProblemDetailsSchema('RecordsPolicyProblem', 422);
export const RecordsPolicyConflictProblemSchema = makeProblemDetailsSchema('RecordsPolicyConflictProblem', 409);
export const RecordsInternalProblemSchema = makeProblemDetailsSchema('RecordsInternalProblem', 500);

export const RecordsApi = HttpApi.make('RecordsApi').add(
  HttpApiGroup.make('records').add(
    HttpApiEndpoint.post('execute', '/reads/records', {
      error: [
        RecordsInvalidProblemSchema,
        RecordsAuthenticationProblemSchema,
        RecordsForbiddenProblemSchema,
        RecordsNotFoundProblemSchema,
        RecordsPolicyConflictProblemSchema,
        RecordsPolicyProblemSchema,
        RecordsUnavailableProblemSchema,
        RecordsInternalProblemSchema,
      ],
      payload: RecordsRequestSchema,
      success: RecordsResponseSchema,
    }),
  ),
);
