// @generated by OntOS Codesmith Business Permission v1
// @ontos-permission-owner siampark.work
// @ontos-permission-code siampark.work.write_all
import { defineBusinessPermission } from '@app/core-runtime';

export const siamparkWorkWriteAllPermission = defineBusinessPermission({
  allowedScopeKinds: ['module'],
  auditSensitivity: 'sensitive',
  authorityGroups: [],
  customerDelegable: false,
  internalGrantable: false,
  key: 'siampark.work.write_all',
  meaning: 'Siampark Work Write All module-scoped permission.',
  owningCapability: 'siampark.work',
  protectedEntrypoints: [],
  schemaVersion: '1',
});
