// @generated by OntOS Codesmith module-api v1
import { CalendarDateWireSchema as CalendarDateSchema } from '@app/shared-contracts';
import { PropertyRefSchema } from '@app/siampark-property/resources/property';
import { UnitRefSchema } from '@app/siampark-property/resources/unit';
import { AssetRefSchema } from '@app/siampark-property/resources/asset';
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { PrincipalRefSchema } from '@app/core-runtime/permissions/principal-ref';
import { TaskRefSchema } from '../resources/task.ts';
import { TaskCollectionRefSchema } from '../resources/task-collection.ts';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';

export { CalendarDateWireSchema as CalendarDateSchema } from '@app/shared-contracts';

export const ContextRefSchema = Schema.Union([PropertyRefSchema, UnitRefSchema, AssetRefSchema]);
export type ContextRef = typeof ContextRefSchema.Type;
export const TaskStateSchema = Schema.Literals(['NEW', 'IN_PROGRESS', 'WAITING', 'DONE', 'CANCELLED']);
export type TaskState = typeof TaskStateSchema.Type;
export const TaskPrioritySchema = Schema.Literals(['LOW', 'NORMAL', 'HIGH']);
export const TaskSchema = Schema.Struct({
  collectionRef: TaskCollectionRefSchema,
  contextRefs: Schema.Array(ContextRefSchema).check(Schema.isMaxLength(12)),
  createdAt: Schema.DateTimeUtcFromString,
  description: Schema.optionalKey(Schema.Trim.check(Schema.isMaxLength(2000))),
  dueDate: Schema.optionalKey(CalendarDateSchema),
  ownerPrincipalRef: Schema.optionalKey(PrincipalRefSchema),
  priority: TaskPrioritySchema,
  ref: TaskRefSchema,
  state: TaskStateSchema,
  title: Schema.Trim.check(Schema.isMinLength(1), Schema.isMaxLength(200)),
  updatedAt: Schema.DateTimeUtcFromString,
});
export type Task = typeof TaskSchema.Type;
export const TaskCollectionSchema = Schema.Struct({
  properties: Schema.Struct({
    dueDate: Schema.Struct({ locked: Schema.Literal(true), type: Schema.Literal('DATE') }),
    ownerPrincipalRef: Schema.Struct({ locked: Schema.Literal(true), type: Schema.Literal('PRINCIPAL') }),
    status: Schema.Struct({
      groups: Schema.Tuple([Schema.Literal('NOT_STARTED'), Schema.Literal('IN_PROGRESS'), Schema.Literal('DONE')]),
      locked: Schema.Literal(true),
      type: Schema.Literal('STATUS'),
    }),
    title: Schema.Struct({ locked: Schema.Literal(true), type: Schema.Literal('TEXT') }),
  }),
  ref: TaskCollectionRefSchema,
  title: Schema.Trim.check(Schema.isNonEmpty()),
});
export const WorkStateSchema = Schema.Struct({ collection: TaskCollectionSchema, tasks: Schema.Array(TaskSchema) });
export type WorkState = typeof WorkStateSchema.Type;
export const RecordsRequestSchema = Schema.Struct({
  contextResourceId: Schema.optionalKey(PropertyRefSchema.fields.resourceId),
  ownerPrincipalId: Schema.optionalKey(PrincipalRefSchema.fields.principalId),
  resourceId: Schema.optionalKey(TaskRefSchema.fields.resourceId),
  state: Schema.optionalKey(TaskStateSchema),
});
export type RecordsRequest = typeof RecordsRequestSchema.Type;
export type RecordsRequestEncoded = typeof RecordsRequestSchema.Encoded;
export const RecordsResponseSchema = Schema.Struct({
  actorPrincipalRef: PrincipalRefSchema,
  canWrite: Schema.Boolean,
  collection: TaskCollectionSchema,
  indicators: Schema.Struct({
    open: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)),
    overdue: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)),
  }),
  items: Schema.Array(TaskSchema),
  referenceDate: Schema.Literal('2026-10-05'),
  revision: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)),
});
export type RecordsResponse = typeof RecordsResponseSchema.Type;

export const RecordsAuthenticationProblemSchema = makeProblemDetailsSchema('RecordsAuthenticationProblem', 401);
export const RecordsInvalidProblemSchema = makeProblemDetailsSchema('RecordsInvalidProblem', 400);
export const RecordsUnavailableProblemSchema = makeRetryableProblemDetailsSchema('RecordsUnavailableProblem', 503);
export const RecordsForbiddenProblemSchema = makeProblemDetailsSchema('RecordsForbiddenProblem', 403);
export const RecordsNotFoundProblemSchema = makeProblemDetailsSchema('RecordsNotFoundProblem', 404);
export const RecordsPolicyProblemSchema = makeProblemDetailsSchema('RecordsPolicyProblem', 422);
export const RecordsPolicyConflictProblemSchema = makeProblemDetailsSchema('RecordsPolicyConflictProblem', 409);
export const RecordsInternalProblemSchema = makeProblemDetailsSchema('RecordsInternalProblem', 500);

export const RecordsApi = HttpApi.make('RecordsApi').add(
  HttpApiGroup.make('records').add(
    HttpApiEndpoint.post('execute', '/reads/records', {
      error: [
        RecordsInvalidProblemSchema,
        RecordsAuthenticationProblemSchema,
        RecordsForbiddenProblemSchema,
        RecordsNotFoundProblemSchema,
        RecordsPolicyConflictProblemSchema,
        RecordsPolicyProblemSchema,
        RecordsUnavailableProblemSchema,
        RecordsInternalProblemSchema,
      ],
      payload: RecordsRequestSchema,
      success: RecordsResponseSchema,
    }),
  ),
);
