// @generated by OntOS Codesmith module-api v1
import type { ReadHandlerContext } from '@app/core-runtime';
import {
  defineRead,
  defineTenantModuleEntrypoint,
  OperationContextUnavailable,
  ReadHandlerNotFound,
  ReadHandlerUnavailable,
} from '@app/core-runtime';
import { Effect } from 'effect';
import { RecordsRequestSchema, RecordsResponseSchema } from '../../shared/apis/records.ts';
import { persistenceService, filterAgreementsRecords } from '../services/persistence.service.ts';

const OWNER_MODULE_KEY = 'siampark.agreements';

type Services = Effect.Success<ReturnType<typeof persistenceService>>;

const recordsEntrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: { kind: 'context_permission', permission: 'module.access' },
  entrypointKey: 'siampark.agreements.api.records',
  moduleKey: OWNER_MODULE_KEY,
  role: 'api',
});

export const recordsRead = defineRead(
  {
    accessKind: 'list',
    entrypoint: recordsEntrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'siampark.agreements.api.records.evidence.v1',
    },
    inputSchema: RecordsRequestSchema,
    legalEntityScope: 'required',
    owningModuleKey: OWNER_MODULE_KEY,
    permissionTarget: 'module',
    policies: [],
    readKey: 'siampark.agreements.api.records',
    resultSchema: RecordsResponseSchema,
    schemaVersion: '1',
  },
  (input, context: ReadHandlerContext<Services>) =>
    context.services.load().pipe(
      Effect.mapError((cause) =>
        Object.defineProperty(
          new ReadHandlerUnavailable({
            code: 'read_handler_unavailable',
            reason: 'Agreements data is temporarily unavailable',
          }),
          'cause',
          { configurable: false, enumerable: false, value: cause, writable: false },
        ),
      ),
      Effect.flatMap((current) => {
        const result = filterAgreementsRecords(current.snapshot, current.revision, input);
        const resultCount = result.contracts.length + result.documents.length;
        return input.resourceId !== undefined && resultCount === 0
          ? Effect.fail(
              new ReadHandlerNotFound({
                code: 'read_handler_not_found',
                reason: 'Record is not present in the authorized scope',
              }),
            )
          : Effect.succeed({ evidence: { resultCount }, result });
      }),
    ),
  (transaction, scope) =>
    persistenceService(transaction, scope).pipe(
      Effect.mapError((cause) =>
        Object.defineProperty(
          new OperationContextUnavailable({
            code: 'operation_context_unavailable',
            reason: 'Owner persistence is temporarily unavailable',
          }),
          'cause',
          { configurable: false, enumerable: false, value: cause, writable: false },
        ),
      ),
    ),
  () => ({ kind: 'module', moduleId: OWNER_MODULE_KEY }),
);
