// @generated by OntOS Codesmith Module Contract v1
// @ontos-deployment-app-id siampark-relationships
// @ontos-module-id siampark.relationships
import {
  defineOntosModuleManifest,
  ShellNavigationContributionSchema,
  ShellPageContributionSchema,
} from '@app/core-runtime';
import { Result, Schema } from 'effect';
// <generated-module-manifest-imports>
import { activityResourceDescriptor } from './shared/resources/activity.ts';
import { applyCommandAction } from './src/actions/apply-command.action.ts';
import { RecordsApi } from './shared/apis/records.ts';
import { RecordsPage } from './src/routes/[lang]/siampark/relationships/page.tsx';
import { siamparkRelationshipsReadAllPermission } from './shared/permissions/siampark-relationships-read-all.ts';
import { siamparkRelationshipsWriteAllPermission } from './shared/permissions/siampark-relationships-write-all.ts';
// </generated-module-manifest-imports>

type NavigationContributionInput = typeof ShellNavigationContributionSchema.Encoded;
type PageContributionInput = typeof ShellPageContributionSchema.Encoded;

const navigationContribution = (value: NavigationContributionInput) =>
  Result.getOrThrow(Schema.decodeResult(ShellNavigationContributionSchema)(value));
const pageContribution = (value: PageContributionInput) =>
  Result.getOrThrow(Schema.decodeResult(ShellPageContributionSchema)(value));

const moduleKey = 'siampark.relationships';
const recordsPageKey = 'siampark.relationships.page.records';

export const siamparkRelationshipsManifest = defineOntosModuleManifest({
  activation: {
    defaultState: 'inactive',
    preservesHistoryWhenInactive: true,
    scope: 'tenant',
    supportedStates: ['inactive', 'active', 'read_only', 'suspended', 'quarantined', 'deprecated', 'archived'],
  },
  module: {
    description: 'Siampark Relationships business capability.',
    displayName: 'Siampark Relationships',
    id: moduleKey,
    implementedAs: 'ultramodern_microvertical',
    kind: 'business_module',
  },
  publicSurface: {
    actions: [
      // <generated-module-manifest-actions>
      applyCommandAction,
      // </generated-module-manifest-actions>
    ],
    api: {
      // <generated-module-manifest-apis>
      records: RecordsApi,
      // </generated-module-manifest-apis>
    },
    businessPermissions: [
      // <generated-module-manifest-business-permissions>
      siamparkRelationshipsReadAllPermission,
      siamparkRelationshipsWriteAllPermission,
      // </generated-module-manifest-business-permissions>
    ],
    components: {
      // <generated-module-manifest-components>
      'page-records': RecordsPage,
      // </generated-module-manifest-components>
    },
    events: [],
    reports: [
      // <generated-module-manifest-reports>
      // </generated-module-manifest-reports>
    ],
    resourceTypes: [
      // <generated-module-manifest-resources>
      activityResourceDescriptor,
      // </generated-module-manifest-resources>
    ],
    search: [
      // <generated-module-manifest-search>
      // </generated-module-manifest-search>
    ],
    shellContributions: {
      mediaAttachments: [],
      navigation: [
        // <generated-module-shell-navigation>
        navigationContribution({
          contributionKey: 'siampark.relationships.navigation.records',
          entrypoint: {
            access: 'read',
            authorization: { kind: 'context_permission', permission: 'module.access' },
            entrypointKey: recordsPageKey,
            moduleKey,
            role: 'page',
            scope: 'tenant',
          },
          groupKey: 'shell.navigation.modules',
          order: 100,
          pageKey: recordsPageKey,
        }),
        // </generated-module-shell-navigation>
      ],
      pages: [
        // <generated-module-shell-pages>
        pageContribution({
          componentKey: 'siampark.relationships.page-records',
          contributionKey: recordsPageKey,
          entrypoint: {
            access: 'read',
            authorization: { kind: 'context_permission', permission: 'module.access' },
            entrypointKey: recordsPageKey,
            moduleKey,
            role: 'page',
            scope: 'tenant',
          },
          expose: './PageRecords',
          routePath: '/siampark/relationships',
        }),
        // </generated-module-shell-pages>
      ],
      publicComponents: [
        // <generated-module-shell-components>
        // </generated-module-shell-components>
      ],
      reports: [
        // <generated-module-shell-reports>
        // </generated-module-shell-reports>
      ],
      resourceDetails: [],
      search: [
        // <generated-module-shell-search>
        // </generated-module-shell-search>
      ],
      timelines: [],
    },
  },
});
