// @generated by scaffold:outbox-worker worker-host
// @ontos-outbox-worker-host-owner commerce.inventory
import { Layer } from 'effect';
import { extractOutboxWorkerSubscriptions, startOutboxWorkerProcess } from '@app/core-runtime/outbox/worker';
import { outboxWorkers } from '../src/workers/index.ts';
import {
  outboxWorkerCorePersistenceLive,
  outboxWorkerDatabaseConfigLive,
  outboxWorkerLayer as outboxWorkerDefinitionLayer,
  outboxWorkerRepositoryLive,
} from '../src/worker-host/layer.ts';
import { InventoryBackendEffectsUnavailableLive } from '../src/services/inventory-backend-effects.service.ts';

const outboxSubscriptions = extractOutboxWorkerSubscriptions(outboxWorkers);
const outboxWorkerProcessLayer = outboxWorkerDefinitionLayer.pipe(
  Layer.provide(InventoryBackendEffectsUnavailableLive),
  Layer.provide(outboxWorkerRepositoryLive),
  Layer.provide(outboxWorkerCorePersistenceLive),
  Layer.provide(outboxWorkerDatabaseConfigLive),
);

export const startInventoryOutboxWorker = (): void =>
  startOutboxWorkerProcess({
    claimOwnerPrefix: 'commerce.inventory-outbox-worker',
    health: true,
    layer: outboxWorkerProcessLayer,
    registrations: outboxWorkers,
    subscriptions: outboxSubscriptions,
  });

startInventoryOutboxWorker();
