// @generated by OntOS Codesmith Action v1
// @ontos-action-owner siampark.billing-finance
// @ontos-action-slug apply-command
import { randomUUID } from 'node:crypto';
import { DateTime, Effect } from 'effect';
import { OperationContextUnavailable, defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import type { ActionHandlerContext, ActionServiceFactory } from '@app/core-runtime';
import {
  ApplyCommandPayloadSchema,
  ApplyCommandResultSchema,
  FinanceErrorSchema,
  FinanceRejected,
} from '../../shared/actions/apply-command.ts';
import type { ApplyCommandPayload } from '../../shared/actions/apply-command.ts';
import { persistenceService, requireFinanceRevision, transitionFinance } from '../services/persistence.service.ts';
import type { FinanceValidators } from '../services/persistence.service.ts';
import { makeFinanceValidators } from '../services/reference-validation.ts';
import type { FinanceValidatorRequirements } from '../services/reference-validation.ts';

const financeModuleKey = 'siampark.billing-finance';

export { ApplyCommandPayloadSchema, ApplyCommandResultSchema } from '../../shared/actions/apply-command.ts';
type Services = Effect.Success<ReturnType<typeof persistenceService>> & { readonly validators: FinanceValidators };
const handleApplyCommand = Effect.fn('Finance.applyCommand')(function* handleApplyCommand(
  payload: ApplyCommandPayload,
  context: ActionHandlerContext<Readonly<Record<string, never>>, Services>,
) {
  const current = yield* context.services.load();
  yield* requireFinanceRevision(current.revision, payload.expectedRevision);
  if (context.scope.legalEntityId === undefined) {
    return yield* new FinanceRejected({ code: 'finance_rejected', reason: 'legal_entity_required' });
  }
  yield* context.recordDataAccess({
    accessKind: 'read',
    queryHash: 'siampark.billing-finance.state.v1',
    resultCount: 1,
    servingModuleKey: financeModuleKey,
  });
  const now = yield* DateTime.now;
  const resourceId = yield* Effect.sync(randomUUID);
  const attemptId = yield* Effect.sync(randomUUID);
  const result = yield* transitionFinance(
    current.state,
    payload.command,
    { legalEntityId: context.scope.legalEntityId, tenantId: context.scope.tenantId },
    context.services.validators,
    { attemptId, now, resourceId },
  );
  const revision = result.changed ? yield* context.services.save(result.state, current.revision) : current.revision;
  return { changed: result.changed, invoice: result.invoice, revision };
});

const makeActionServices: ActionServiceFactory<Services, FinanceValidatorRequirements> = Effect.fn(
  'Finance.makeActionServices',
)(function* makeServices(transaction, scope) {
  const result = yield* Effect.all(
    {
      persistence: persistenceService(transaction, scope),
      validators: makeFinanceValidators(scope),
    },
    { concurrency: 1 },
  ).pipe(
    Effect.mapError(
      (failure) => new OperationContextUnavailable({ code: 'operation_context_unavailable', reason: failure.reason }),
    ),
  );
  return { ...result.persistence, validators: result.validators };
});

export const applyCommandAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'siampark.billing-finance.apply-command.access.v1',
    },
    actionKey: 'siampark.billing-finance.apply-command',
    auditProfile: 'standard',
    domainErrorSchema: FinanceErrorSchema,
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'siampark.billing-finance.apply-command',
      moduleKey: financeModuleKey,
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'required',
    owningModuleKey: financeModuleKey,
    payloadSchema: ApplyCommandPayloadSchema,
    policies: [],
    resultSchema: ApplyCommandResultSchema,
    schemaVersion: '1',
  },
  handleApplyCommand,
  makeActionServices,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
