// @generated by OntOS Codesmith Action v1
// @ontos-action-owner siampark.relationships
// @ontos-action-slug apply-command
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import type { ActionHandlerContext } from '@app/core-runtime';
import type { Effect } from 'effect';
import {
  ApplyCommandPayloadSchema,
  ApplyCommandResultSchema,
  ActivityErrorSchema,
} from '../../shared/actions/apply-command.ts';
import type { ApplyCommandPayload } from '../../shared/actions/apply-command.ts';
import { persistenceService } from '../services/persistence.service.ts';

export { ApplyCommandPayloadSchema, ApplyCommandResultSchema } from '../../shared/actions/apply-command.ts';
type Services = Effect.Success<ReturnType<typeof persistenceService>>;
const handleApplyCommand = (
  payload: ApplyCommandPayload,
  context: ActionHandlerContext<Readonly<Record<string, never>>, Services>,
): Effect.Effect<
  Effect.Success<ReturnType<Services['apply']>>,
  Effect.Error<ReturnType<Services['apply']>>,
  Effect.Services<ReturnType<typeof persistenceService>> | Effect.Services<ReturnType<Services['apply']>>
> => context.services.apply(payload.command, payload.expectedRevision, context.actionInvocationId);

export const applyCommandAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'siampark.relationships.apply-command.access.v1',
    },
    actionKey: 'siampark.relationships.apply-command',
    auditProfile: 'standard',
    domainErrorSchema: ActivityErrorSchema,
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'siampark.relationships.apply-command',
      moduleKey: 'siampark.relationships',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'required',
    owningModuleKey: 'siampark.relationships',
    payloadSchema: ApplyCommandPayloadSchema,
    policies: [],
    resultSchema: ApplyCommandResultSchema,
    schemaVersion: '1',
  },
  handleApplyCommand,
  persistenceService,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
