// @generated by OntOS Codesmith MicroVertical Action Boundary v1
// @ontos-action-boundary-owner siampark-work
export {
  GatewayAssertionRedemptionLive,
  GatewayAssertionRedemptionDatabaseLive,
} from '../../src/auth/gateway-assertion-redemption-runtime.ts';
