import { CalendarDateWireSchema } from '@app/shared-contracts';
// @generated by OntOS Codesmith module-api v1
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';

import { CounterpartyRefSchema } from '@app/party-registry/resources/counterparty';
import { PartyRefSchema } from '@app/party-registry/resources/party';
import { ContractRefSchema } from '@app/siampark-agreements/resources/contract';
import { UnitRefSchema } from '@app/siampark-property/resources/unit';
import { OccupancyRefSchema } from '../resources/occupancy.ts';

export const DemoDateSchema = CalendarDateWireSchema;
const TextSchema = Schema.Trim.check(Schema.isMinLength(1), Schema.isMaxLength(500));
export const OccupancySchema = Schema.Struct({
  contractRef: Schema.toEncoded(Schema.OptionFromNullOr(ContractRefSchema)),
  customerCounterpartyRef: Schema.toEncoded(Schema.OptionFromNullOr(CounterpartyRefSchema)),
  endDate: Schema.toEncoded(Schema.OptionFromNullOr(DemoDateSchema)),
  externalBookingCorrelation: Schema.toEncoded(Schema.OptionFromNullOr(TextSchema)),
  guestPartyRef: Schema.toEncoded(Schema.OptionFromNullOr(PartyRefSchema)),
  kind: Schema.Literals(['LONG_TERM_LEASE', 'SHORT_STAY']),
  note: Schema.toEncoded(Schema.OptionFromNullOr(TextSchema)),
  occupancyRef: OccupancyRefSchema,
  peopleCount: Schema.toEncoded(Schema.OptionFromNullOr(Schema.Int.check(Schema.isGreaterThan(0)))),
  startDate: DemoDateSchema,
  state: Schema.Literals(['DRAFT', 'CONFIRMED', 'ACTIVE', 'COMPLETED', 'CANCELLED']),
  unitRef: UnitRefSchema,
});
export type Occupancy = typeof OccupancySchema.Type;
export const BookingObservationSchema = Schema.Struct({
  attemptedAt: Schema.toEncoded(Schema.DateTimeUtcFromString),
  attempts: Schema.Int.check(Schema.isGreaterThan(0)),
  completedAt: Schema.toEncoded(Schema.OptionFromNullOr(Schema.DateTimeUtcFromString)),
  correlation: TextSchema,
  integrationKind: Schema.Literal('BOOKING'),
  mode: Schema.Literal('SIMULATED'),
  observationId: Schema.toEncoded(Schema.String.check(Schema.isUUID()).pipe(Schema.brand('ResourceId'))),
  occupancyRef: Schema.toEncoded(Schema.OptionFromNullOr(OccupancyRefSchema)),
  ownerResourceRef: Schema.Union([OccupancyRefSchema, UnitRefSchema]),
  providerLabel: TextSchema,
  requestSummary: TextSchema,
  resultSummary: TextSchema,
  state: Schema.Literals(['SUCCESS', 'FAILED', 'CONFLICT']),
});
export type BookingObservation = typeof BookingObservationSchema.Type;
export const OccupancyStateSchema = Schema.Struct({
  bookingObservations: Schema.Array(BookingObservationSchema),
  occupancies: Schema.Array(OccupancySchema),
});
export type OccupancyState = typeof OccupancyStateSchema.Type;
export const RecordsRequestSchema = Schema.Struct({
  fromDate: Schema.optionalKey(DemoDateSchema),
  kind: Schema.optionalKey(OccupancySchema.fields.kind),
  resourceId: Schema.optionalKey(
    Schema.toEncoded(Schema.String.check(Schema.isUUID()).pipe(Schema.brand('ResourceId'))),
  ),
  state: Schema.optionalKey(OccupancySchema.fields.state),
  toDate: Schema.optionalKey(DemoDateSchema),
  unitRef: Schema.optionalKey(UnitRefSchema),
});
export type RecordsRequest = typeof RecordsRequestSchema.Type;
export const RecordsResponseSchema = Schema.Struct({
  ...OccupancyStateSchema.fields,
  revision: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)),
});
export type RecordsResponse = typeof RecordsResponseSchema.Type;

export const RecordsAuthenticationProblemSchema = makeProblemDetailsSchema('RecordsAuthenticationProblem', 401);
export const RecordsInvalidProblemSchema = makeProblemDetailsSchema('RecordsInvalidProblem', 400);
export const RecordsUnavailableProblemSchema = makeRetryableProblemDetailsSchema('RecordsUnavailableProblem', 503);
export const RecordsForbiddenProblemSchema = makeProblemDetailsSchema('RecordsForbiddenProblem', 403);
export const RecordsNotFoundProblemSchema = makeProblemDetailsSchema('RecordsNotFoundProblem', 404);
export const RecordsPolicyProblemSchema = makeProblemDetailsSchema('RecordsPolicyProblem', 422);
export const RecordsPolicyConflictProblemSchema = makeProblemDetailsSchema('RecordsPolicyConflictProblem', 409);
export const RecordsInternalProblemSchema = makeProblemDetailsSchema('RecordsInternalProblem', 500);

export const RecordsApi = HttpApi.make('RecordsApi').add(
  HttpApiGroup.make('records').add(
    HttpApiEndpoint.post('execute', '/reads/records', {
      error: [
        RecordsInvalidProblemSchema,
        RecordsAuthenticationProblemSchema,
        RecordsForbiddenProblemSchema,
        RecordsNotFoundProblemSchema,
        RecordsPolicyConflictProblemSchema,
        RecordsPolicyProblemSchema,
        RecordsUnavailableProblemSchema,
        RecordsInternalProblemSchema,
      ],
      payload: RecordsRequestSchema,
      success: RecordsResponseSchema,
    }),
  ),
);
