// @generated by OntOS Codesmith module-api v1
import { CounterpartyRefSchema } from '@app/party-registry/resources/counterparty';
import { ContractRefSchema } from '@app/siampark-agreements/resources/contract';
import { OccupancyRefSchema } from '@app/siampark-occupancy/resources/occupancy';
import { PropertyRefSchema } from '@app/siampark-property/resources/property';
import { UnitRefSchema } from '@app/siampark-property/resources/unit';
import { TaskRefSchema } from '@app/siampark-work/resources/task';
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { CalendarDateWireSchema } from '@app/shared-contracts';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';
import { InvoiceRefSchema } from '../resources/invoice.ts';
import { FinancialPlanEntryRefSchema } from '../resources/financial-plan-entry.ts';

export const DEMO_BUSINESS_DATE = '2026-10-05';
export const CalendarDateSchema = CalendarDateWireSchema;
export const FinanceTextSchema = Schema.Trim.check(Schema.isMinLength(1), Schema.isMaxLength(500));
export const FinanceAttemptIdSchema = Schema.toEncoded(FinanceTextSchema.pipe(Schema.brand('FinanceAttemptId')));
export const FinanceResultIdSchema = Schema.toEncoded(FinanceTextSchema.pipe(Schema.brand('FinanceResultId')));
const FinancePropertyIdSchema = Schema.toEncoded(FinanceTextSchema.pipe(Schema.brand('FinancePropertyId')));
const FinanceResourceIdSchema = Schema.toEncoded(FinanceTextSchema.pipe(Schema.brand('FinanceResourceId')));
// Bounded aggregates keep sums of at most 1000 amounts safely inside Number's exact integer range.
export const MoneyMinorSchema = Schema.Int.check(
  Schema.isGreaterThanOrEqualTo(0),
  Schema.isLessThanOrEqualTo(1_000_000_000_000),
);
export const InvoiceDirectionSchema = Schema.Literals(['OUTGOING', 'INCOMING']);
export const InvoiceBusinessStateSchema = Schema.Literals(['DRAFT', 'CONFIRMED', 'VOIDED']);
export const PaymentStateSchema = Schema.Literals(['UNPAID', 'PARTIALLY_PAID', 'PAID']);
export const AccountingSyncStateSchema = Schema.Literals(['NOT_SYNCED', 'PENDING', 'SYNCED', 'FAILED']);
export const InvoiceDraftFields = {
  contractRef: Schema.optionalKey(ContractRefSchema),
  counterpartyRef: CounterpartyRefSchema,
  currency: Schema.Literal('CZK'),
  direction: InvoiceDirectionSchema,
  documentNumber: FinanceTextSchema,
  dueDate: CalendarDateSchema,
  issueDate: CalendarDateSchema,
  note: Schema.optionalKey(FinanceTextSchema),
  occupancyRef: Schema.optionalKey(OccupancyRefSchema),
  propertyRef: Schema.optionalKey(PropertyRefSchema),
  taskRef: Schema.optionalKey(TaskRefSchema),
  totalMinor: MoneyMinorSchema.check(Schema.isGreaterThan(0)),
  unitRef: Schema.optionalKey(UnitRefSchema),
};
export const InvoiceSchema = Schema.Struct({
  ...InvoiceDraftFields,
  accountingCorrelation: FinanceTextSchema,
  accountingSyncState: AccountingSyncStateSchema,
  businessState: InvoiceBusinessStateSchema,
  createdAt: Schema.DateTimeUtcFromString,
  externalAccountingReference: Schema.optionalKey(FinanceTextSchema),
  paidMinor: MoneyMinorSchema,
  paymentState: PaymentStateSchema,
  ref: InvoiceRefSchema,
  updatedAt: Schema.DateTimeUtcFromString,
});
export type Invoice = typeof InvoiceSchema.Type;
export const FinancialPlanEntrySchema = Schema.Struct({
  category: FinanceTextSchema,
  currency: Schema.Literal('CZK'),
  kind: Schema.Literals(['COST', 'REVENUE']),
  periodEndExclusive: CalendarDateSchema,
  periodStart: CalendarDateSchema,
  plannedMinor: MoneyMinorSchema,
  propertyRef: PropertyRefSchema,
  ref: FinancialPlanEntryRefSchema,
  state: Schema.Literals(['PLANNED', 'CONFIRMED', 'CANCELLED']),
});
export type FinancialPlanEntry = typeof FinancialPlanEntrySchema.Type;
export const AccountingObservationSchema = Schema.Struct({
  attemptedAt: Schema.DateTimeUtcFromString,
  attemptId: FinanceAttemptIdSchema,
  completedAt: Schema.optionalKey(Schema.DateTimeUtcFromString),
  correlation: FinanceTextSchema,
  integrationKind: Schema.Literal('ACCOUNTING'),
  invoiceRef: InvoiceRefSchema,
  latest: Schema.Boolean,
  mode: Schema.Literal('SIMULATED'),
  providerLabel: Schema.Literal('DEMO'),
  receipt: Schema.optionalKey(FinanceTextSchema),
  requestSummary: FinanceTextSchema,
  resultId: Schema.optionalKey(FinanceResultIdSchema),
  resultSummary: FinanceTextSchema,
  revision: Schema.Int.check(Schema.isGreaterThan(0)),
  status: Schema.Literals(['PENDING', 'SUCCESS', 'FAILED']),
});
export type AccountingObservation = typeof AccountingObservationSchema.Type;
export const PaymentObservationSchema = Schema.Struct({
  confirmedPaidMinor: MoneyMinorSchema,
  correlation: FinanceTextSchema,
  currency: Schema.Literal('CZK'),
  invoiceRef: InvoiceRefSchema,
  mode: Schema.Literal('SIMULATED'),
  observedAt: Schema.DateTimeUtcFromString,
  resultId: FinanceResultIdSchema,
});
export type PaymentObservation = typeof PaymentObservationSchema.Type;
export const FinanceStateSchema = Schema.Struct({
  accountingObservations: Schema.Array(AccountingObservationSchema).check(Schema.isMaxLength(5000)),
  financialPlanEntries: Schema.Array(FinancialPlanEntrySchema).check(Schema.isMaxLength(1000)),
  invoices: Schema.Array(InvoiceSchema).check(Schema.isMaxLength(1000)),
  paymentObservations: Schema.Array(PaymentObservationSchema).check(Schema.isMaxLength(5000)),
});
export type FinanceState = typeof FinanceStateSchema.Type;
export const RecordsRequestSchema = Schema.Struct({
  propertyId: Schema.optionalKey(FinancePropertyIdSchema),
  resourceId: Schema.optionalKey(FinanceResourceIdSchema),
});
export type RecordsRequest = typeof RecordsRequestSchema.Type;
const AggregateMinorSchema = Schema.Int.check(
  Schema.isGreaterThanOrEqualTo(0),
  Schema.isLessThanOrEqualTo(1_000_000_000_000_000),
);
export const FinanceIndicatorsSchema = Schema.Struct({
  costMinor: AggregateMinorSchema,
  costVarianceMinor: Schema.Int,
  grossOutstandingMinor: AggregateMinorSchema,
  integrationWarnings: Schema.Int,
  openIncomingInvoices: Schema.Int,
  openInvoices: Schema.Int,
  openOutgoingInvoices: Schema.Int,
  overdueInvoices: Schema.Int,
  payablesOutstandingMinor: AggregateMinorSchema,
  plannedCostMinor: AggregateMinorSchema,
  plannedRevenueMinor: AggregateMinorSchema,
  receivablesOutstandingMinor: AggregateMinorSchema,
  revenueMinor: AggregateMinorSchema,
  revenueVarianceMinor: Schema.Int,
});
export const RecordsResponseSchema = Schema.Struct({
  canWrite: Schema.Boolean,
  indicators: FinanceIndicatorsSchema,
  referenceDate: Schema.Literal('2026-10-05'),
  revision: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)),
  state: FinanceStateSchema,
});
export type RecordsResponse = typeof RecordsResponseSchema.Type;

export const RecordsAuthenticationProblemSchema = makeProblemDetailsSchema('RecordsAuthenticationProblem', 401);
export const RecordsInvalidProblemSchema = makeProblemDetailsSchema('RecordsInvalidProblem', 400);
export const RecordsUnavailableProblemSchema = makeRetryableProblemDetailsSchema('RecordsUnavailableProblem', 503);
export const RecordsForbiddenProblemSchema = makeProblemDetailsSchema('RecordsForbiddenProblem', 403);
export const RecordsNotFoundProblemSchema = makeProblemDetailsSchema('RecordsNotFoundProblem', 404);
export const RecordsPolicyProblemSchema = makeProblemDetailsSchema('RecordsPolicyProblem', 422);
export const RecordsPolicyConflictProblemSchema = makeProblemDetailsSchema('RecordsPolicyConflictProblem', 409);
export const RecordsInternalProblemSchema = makeProblemDetailsSchema('RecordsInternalProblem', 500);

export const RecordsApi = HttpApi.make('RecordsApi').add(
  HttpApiGroup.make('records').add(
    HttpApiEndpoint.post('execute', '/reads/records', {
      error: [
        RecordsInvalidProblemSchema,
        RecordsAuthenticationProblemSchema,
        RecordsForbiddenProblemSchema,
        RecordsNotFoundProblemSchema,
        RecordsPolicyConflictProblemSchema,
        RecordsPolicyProblemSchema,
        RecordsUnavailableProblemSchema,
        RecordsInternalProblemSchema,
      ],
      payload: RecordsRequestSchema,
      success: RecordsResponseSchema,
    }),
  ),
);
