// @generated by OntOS Codesmith Resource v1
// @ontos-resource-owner siampark.occupancy
// @ontos-resource-slug occupancy
import type { OntosResourceType } from '@app/core-runtime';
import { Schema } from 'effect';

const ResourceIdSchema = Schema.String.check(Schema.isUUID()).pipe(Schema.brand('ResourceId'));
const TenantIdSchema = Schema.String.check(Schema.isUUID()).pipe(Schema.brand('TenantId'));

export const OccupancyRefSchema = Schema.Struct({
  moduleId: Schema.Literal('siampark.occupancy'),
  resourceId: Schema.toEncoded(ResourceIdSchema),
  resourceType: Schema.Literal('siampark.occupancy.occupancy'),
  tenantId: Schema.toEncoded(TenantIdSchema),
});
export type OccupancyRef = typeof OccupancyRefSchema.Type;

export const occupancyResourceDescriptor = {
  capabilities: {
    graphVisible: false,
    linkable: false,
    mediaAttachable: false,
    searchable: false,
    timelineVisible: false,
  },
  description: 'Occupancy resource.',
  key: 'siampark.occupancy.occupancy',
  label: 'Occupancy',
  owningModuleId: 'siampark.occupancy',
} as const satisfies OntosResourceType;
