// @generated by OntOS Codesmith MicroVertical Action Boundary v1
// @ontos-action-boundary-owner assortment
// @ontos-action-boundary-audience assortment
import { GatewayAssertionRedemptionService } from '@app/core-runtime/auth/gateway-assertion-redemption';
import { makeMicroverticalHttpPrincipalAuthentication } from '@app/core-runtime/http/principal-authentication';
import { bindGatewayPrincipalVerifier } from '@app/gateway-principal-verifier/server';
import type { GatewayPrincipalVerificationWithRedemptionOptions } from '@app/gateway-principal-verifier/server';
import { Effect } from 'effect';
import type { Redacted } from 'effect';

export {
  ACTION_PRINCIPAL_BEARER_CHALLENGE,
  ActionPrincipalConfigurationErrorSchema,
  ActionPrincipalExpiredErrorSchema,
  ActionPrincipalInvalidErrorSchema,
  ActionPrincipalMissingErrorSchema,
  ActionPrincipalScopeErrorSchema,
  ActionPrincipalUnavailableErrorSchema,
} from '@app/gateway-principal-verifier/server';
export type {
  ActionPrincipalConfigurationError,
  ActionPrincipalError,
  ActionPrincipalExpiredError,
  ActionPrincipalInvalidError,
  ActionPrincipalMissingError,
  ActionPrincipalScopeError,
  ActionPrincipalUnavailableError,
} from '@app/gateway-principal-verifier/server';

export const ACTION_GATEWAY_AUDIENCE = 'assortment' as const;
export {
  GatewayPrincipalVerifierConfiguration as ActionPrincipalVerifier,
  GatewayPrincipalVerifierLive as ActionPrincipalVerifierLive,
} from '@app/gateway-principal-verifier/server';
export type ActionPrincipalVerificationOptions = GatewayPrincipalVerificationWithRedemptionOptions;

const principalVerifier = bindGatewayPrincipalVerifier(ACTION_GATEWAY_AUDIENCE);

export const verifyActionPrincipal = (
  authorization: Redacted.Redacted<string | undefined>,
  options: ActionPrincipalVerificationOptions,
) => principalVerifier.verifyAndRedeem(authorization, options);

const verifyOperationPrincipal = (authorization: Redacted.Redacted<string | undefined>) =>
  GatewayAssertionRedemptionService.pipe(
    Effect.flatMap((redemption) => principalVerifier.verifyAndRedeem(authorization, { redemption })),
  );

/** Shared HTTP acquisition bound to this deployment's audience-specific verifier. */
export const authenticateOperationPrincipal = makeMicroverticalHttpPrincipalAuthentication(verifyOperationPrincipal);
