// @generated by OntOS Codesmith Action Service v1
import { ContextAccess, OperationContextUnavailable, principalEligibilityForTransaction } from '@app/core-runtime';
import { makeReferenceGatewayCredentialSource } from '@app/gateway-principal-verifier/server';
import {
  executeCounterpartyReadWithAuthorization,
  executePartyDetailWithAuthorization,
} from '@app/party-registry/api/client';
import { executeRecordsWithAuthorization as executeWorkRecords } from '@app/siampark-work/clients/records';
import type { OperationalScope, ScopedTransactionExecutor } from '@app/core-runtime';
import type { PartyRef } from '@app/party-registry/resources/party';
import { and, eq } from 'drizzle-orm';
import { Context, DateTime, Effect, Match, Option, Schema, Struct } from 'effect';

import {
  ActivityPermissionDenied,
  ActivityPersistenceUnavailable,
  ActivityReferenceIneligible,
  ActivityReferenceUnavailable,
  ActivityRevisionConflict,
  ActivityScopeMismatch,
} from '../../shared/actions/apply-command.ts';
import type { ActivityCommand } from '../../shared/actions/apply-command.ts';
import { RelationshipsStateSchema } from '../../shared/apis/records.ts';
import type { Activity, EmailObservation, RecordsRequest, RelationshipsState } from '../../shared/apis/records.ts';
import { ActivityRefSchema } from '../../shared/resources/activity.ts';
import { relationshipsStates } from '../database/schema.ts';

const unavailable = (cause?: unknown) =>
  Object.defineProperty(
    new ActivityPersistenceUnavailable({
      code: 'activity_persistence_unavailable',
      reason: 'Activity persistence is temporarily unavailable',
    }),
    'cause',
    { enumerable: false, value: cause },
  );

const referenceUnavailable = (cause?: unknown) =>
  Object.defineProperty(
    new ActivityReferenceUnavailable({
      code: 'activity_reference_unavailable',
      reason: 'Reference authorization is temporarily unavailable',
    }),
    'cause',
    { enumerable: false, value: cause },
  );

export interface ActivityReferenceVerifierService {
  readonly verify: (
    command: ActivityCommand,
    scope: OperationalScope,
  ) => Effect.Effect<
    { readonly partyRef: PartyRef },
    ActivityReferenceIneligible | ActivityReferenceUnavailable | ActivityPermissionDenied | ActivityScopeMismatch
  >;
}
export class ActivityReferenceVerifier extends Context.Service<
  ActivityReferenceVerifier,
  ActivityReferenceVerifierService
>()('@app/siampark-relationships/services/persistence.service/ActivityReferenceVerifier') {}

const counterpartyReadFailure = (error: Effect.Error<ReturnType<typeof executeCounterpartyReadWithAuthorization>>) =>
  Match.value(error).pipe(
    Match.tag(
      'CounterpartyReadForbiddenProblem',
      'CounterpartyReadNotFoundProblem',
      () =>
        new ActivityReferenceIneligible({
          code: 'activity_reference_ineligible',
          reason: 'Counterparty is absent or forbidden',
        }),
    ),
    Match.orElse(referenceUnavailable),
  );
const partyReadFailure = (error: Effect.Error<ReturnType<typeof executePartyDetailWithAuthorization>>) =>
  Match.value(error).pipe(
    Match.tag(
      'PartyDetailForbiddenProblem',
      'PartyDetailNotFoundProblem',
      () =>
        new ActivityReferenceIneligible({
          code: 'activity_reference_ineligible',
          reason: 'Party is absent or forbidden',
        }),
    ),
    Match.orElse(referenceUnavailable),
  );

export const makeActivityReferenceVerifier = (
  source: Effect.Success<ReturnType<typeof makeReferenceGatewayCredentialSource>>,
): ActivityReferenceVerifierService => ({
  verify: Effect.fn('Relationships.verifyReferences')(function* verifyReferences(command, scope) {
    const refs = [
      ...(command.partyRef === undefined ? [] : [command.partyRef]),
      ...(command.counterpartyRef === undefined ? [] : [command.counterpartyRef]),
      ...(command.followUpTaskRef === undefined ? [] : [command.followUpTaskRef]),
    ];
    if (refs.some((ref) => ref.tenantId !== scope.tenantId)) {
      return yield* new ActivityScopeMismatch({
        code: 'activity_scope_mismatch',
        reason: 'References must belong to the trusted tenant',
      });
    }
    const credential = yield* source.issue('party-registry').pipe(Effect.mapError(referenceUnavailable));
    const options = { baseUrl: credential.apiBaseUrl, compositionRevision: credential.compositionRevision };
    const identity = Effect.gen(function* canonicalIdentity() {
      if (command.counterpartyRef !== undefined) {
        return yield* executeCounterpartyReadWithAuthorization(
          { counterpartyRef: command.counterpartyRef },
          credential.authorization,
          scope.correlationId,
          options,
        ).pipe(
          Effect.mapError(counterpartyReadFailure),
          Effect.flatMap((response) =>
            response.party.archived
              ? Effect.fail(
                  new ActivityReferenceIneligible({
                    code: 'activity_reference_ineligible',
                    reason: 'An archived Party cannot receive a new Activity',
                  }),
                )
              : Effect.succeed(response.party.canonicalPartyRef),
          ),
        );
      }
      if (command.partyRef === undefined) {
        return yield* new ActivityReferenceIneligible({
          code: 'activity_reference_ineligible',
          reason: 'Activity must identify a Party or Counterparty',
        });
      }
      return yield* executePartyDetailWithAuthorization(
        { partyRef: command.partyRef },
        credential.authorization,
        scope.correlationId,
        options,
      ).pipe(
        Effect.mapError(partyReadFailure),
        Effect.flatMap((response) =>
          Option.isSome(response.party.archivedAt)
            ? Effect.fail(
                new ActivityReferenceIneligible({
                  code: 'activity_reference_ineligible',
                  reason: 'An archived Party cannot receive a new Activity',
                }),
              )
            : Effect.succeed(response.resolution.canonicalPartyRef),
        ),
      );
    });
    const partyRef = yield* identity;
    if (command.partyRef !== undefined && command.partyRef.resourceId !== partyRef.resourceId) {
      return yield* new ActivityReferenceIneligible({
        code: 'activity_reference_ineligible',
        reason: 'Activity must use canonical matching identity',
      });
    }
    if (command.followUpTaskRef !== undefined) {
      const taskCredential = yield* source.issue('siampark-work').pipe(Effect.mapError(referenceUnavailable));
      const tasks = yield* executeWorkRecords(
        { resourceId: command.followUpTaskRef.resourceId },
        taskCredential.authorization,
        scope.correlationId,
        { baseUrl: taskCredential.apiBaseUrl, compositionRevision: taskCredential.compositionRevision },
      ).pipe(
        Effect.mapError((error) =>
          Match.value(error).pipe(
            Match.tag(
              'RecordsForbiddenProblem',
              'RecordsNotFoundProblem',
              () =>
                new ActivityReferenceIneligible({
                  code: 'activity_reference_ineligible',
                  reason: 'Follow-up Task is absent or forbidden',
                }),
            ),
            Match.orElse(referenceUnavailable),
          ),
        ),
      );
      if (
        !tasks.items.some(
          ({ ref }) => ref.resourceId === command.followUpTaskRef?.resourceId && ref.tenantId === scope.tenantId,
        )
      ) {
        return yield* new ActivityReferenceIneligible({
          code: 'activity_reference_ineligible',
          reason: 'Follow-up must identify an existing Task',
        });
      }
    }
    if ((command.contextRefs?.length ?? 0) > 0) {
      return yield* new ActivityReferenceIneligible({
        code: 'activity_reference_ineligible',
        reason: 'Link the Activity to its canonical identity and follow-up Task',
      });
    }
    return { partyRef };
  }),
});

export const evolveRelationshipsState = Effect.fn('Relationships.evolveState')(function* evolveState(
  state: RelationshipsState,
  command: ActivityCommand,
  input: {
    readonly now: DateTime.Utc;
    readonly partyRef: PartyRef;
    readonly resourceId: string;
    readonly tenantId: string;
  },
) {
  const refs = [
    input.partyRef,
    ...(command.partyRef === undefined ? [] : [command.partyRef]),
    ...(command.counterpartyRef === undefined ? [] : [command.counterpartyRef]),
    ...(command.followUpTaskRef === undefined ? [] : [command.followUpTaskRef]),
  ];
  if (refs.some((ref) => ref.tenantId !== input.tenantId) || command.ownerPrincipalRef.tenantId !== input.tenantId) {
    return yield* new ActivityScopeMismatch({
      code: 'activity_scope_mismatch',
      reason: 'References must belong to the trusted tenant',
    });
  }
  if (command.partyRef !== undefined && command.partyRef.resourceId !== input.partyRef.resourceId) {
    return yield* new ActivityReferenceIneligible({
      code: 'activity_reference_ineligible',
      reason: 'Activity must refer to the canonical Party of its Counterparty',
    });
  }
  if (state.activities.some((entry) => entry.ref.resourceId === input.resourceId)) {
    return yield* new ActivityRevisionConflict({
      code: 'activity_revision_conflict',
      reason: 'Activity identity is already in use',
    });
  }
  const ref = yield* Schema.decodeEffect(ActivityRefSchema)({
    moduleId: 'siampark.relationships',
    resourceId: input.resourceId,
    resourceType: 'siampark.relationships.activity',
    tenantId: input.tenantId,
  }).pipe(
    Effect.mapError((cause) =>
      Object.defineProperty(
        new ActivityScopeMismatch({ code: 'activity_scope_mismatch', reason: 'Activity identity must be valid' }),
        'cause',
        { enumerable: false, value: cause },
      ),
    ),
  );
  const activity: Activity = {
    contextRefs: command.contextRefs ?? [],
    ...Struct.pick(command, ['counterpartyRef', 'followUpTaskRef']),
    createdAt: input.now,
    kind: command.kind,
    occurredAt: command.occurredAt,
    ownerPrincipalRef: command.ownerPrincipalRef,
    partyRef: input.partyRef,
    ref,
    summary: command.summary,
  };
  return { activity, state: { ...state, activities: [...state.activities, activity] } };
});

export const visibleEmailObservations = (
  observations: readonly EmailObservation[],
  activities: readonly Activity[],
): readonly EmailObservation[] =>
  observations.filter((observation) =>
    activities.some(
      ({ ref }) =>
        ref.moduleId === observation.ownerResourceRef.moduleId &&
        ref.resourceType === observation.ownerResourceRef.resourceType &&
        ref.resourceId === observation.ownerResourceRef.resourceId &&
        ref.tenantId === observation.ownerResourceRef.tenantId,
    ),
  );

const contextGrant = Effect.fn('Relationships.contextGrant')(function* contextGrant(
  scope: OperationalScope,
  permission: 'read_all' | 'write_all',
) {
  const access = yield* ContextAccess;
  if (scope.legalEntityId === undefined || access.contextPermissions === undefined) {
    return yield* referenceUnavailable();
  }
  const decisions = yield* access.contextPermissions({
    legalEntityId: scope.legalEntityId,
    principalId: scope.principalId,
    targets: [{ moduleId: 'siampark.relationships', permission: `siampark.relationships.${permission}` }],
    tenantId: scope.tenantId,
  });
  if (
    decisions.length !== 1 ||
    decisions[0]?.key !== `siampark.relationships:siampark.relationships.${permission}` ||
    decisions[0]?.decision === 'unavailable'
  ) {
    return yield* referenceUnavailable();
  }
  return decisions[0]?.decision === 'allowed';
});
export const visibleActivities = Effect.fn('Relationships.visibleActivities')(function* visibleActivities(
  activities: readonly Activity[],
  scope: OperationalScope,
) {
  const access = yield* ContextAccess;
  if (yield* contextGrant(scope, 'read_all')) {
    return activities;
  }
  if (scope.legalEntityId === undefined) {
    return yield* referenceUnavailable();
  }
  const decisions = yield* access.resources({
    legalEntityId: scope.legalEntityId,
    principalId: scope.principalId,
    resources: activities.map(({ ref }) => ref),
    tenantId: scope.tenantId,
  });
  if (
    decisions.length !== activities.length ||
    decisions.some(
      (decision, index) =>
        decision.decision === 'unavailable' ||
        decision.key !==
          `${activities[index]?.ref.moduleId}:${activities[index]?.ref.resourceType}:${activities[index]?.ref.resourceId}`,
    )
  ) {
    return yield* referenceUnavailable();
  }
  return activities.filter((_, index) => decisions[index]?.decision === 'allowed');
});

export const persistenceService = Effect.fn('Relationships.persistenceService')(
  function* makePersistence(transaction: ScopedTransactionExecutor, scope: OperationalScope) {
    const { legalEntityId } = scope;
    if (
      legalEntityId === undefined ||
      transaction.scope.tenantId !== scope.tenantId ||
      transaction.scope.legalEntityId !== legalEntityId
    ) {
      return yield* new ActivityScopeMismatch({
        code: 'activity_scope_mismatch',
        reason: 'A scoped company transaction is required',
      });
    }
    const principalEligibility = principalEligibilityForTransaction(transaction);
    const injectedVerifier = yield* Effect.serviceOption(ActivityReferenceVerifier);
    const source = yield* makeReferenceGatewayCredentialSource(scope).pipe(Effect.mapError(referenceUnavailable));
    const verifier = Option.getOrElse(injectedVerifier, () => makeActivityReferenceVerifier(source));
    const whereScope = and(
      eq(relationshipsStates.tenantId, scope.tenantId),
      eq(relationshipsStates.legalEntityId, legalEntityId),
    );
    const load = Effect.fn('Relationships.load')(function* load() {
      const rows = yield* transaction
        .select()
        .from(relationshipsStates)
        .where(whereScope)
        .limit(1)
        .pipe(Effect.mapError(unavailable));
      const [row] = rows;
      if (row === undefined) {
        return yield* unavailable();
      }
      const state = yield* Schema.decodeUnknownEffect(RelationshipsStateSchema)(row.state).pipe(
        Effect.mapError(unavailable),
      );
      return { revision: row.revision, state };
    });
    const apply = Effect.fn('Relationships.apply')(function* apply(
      command: ActivityCommand,
      expectedRevision: number,
      resourceId: string,
    ) {
      if (!(yield* contextGrant(scope, 'write_all'))) {
        return yield* new ActivityPermissionDenied({
          code: 'activity_permission_denied',
          reason: 'Recording Activity requires Relationships write permission',
        });
      }
      if (command.ownerPrincipalRef.tenantId !== scope.tenantId) {
        return yield* new ActivityScopeMismatch({
          code: 'activity_scope_mismatch',
          reason: 'Principal must belong to the trusted tenant',
        });
      }
      const principal = yield* principalEligibility.resolve(command.ownerPrincipalRef);
      if (principal.decision === 'unavailable') {
        return yield* referenceUnavailable();
      }
      if (principal.decision !== 'eligible') {
        return yield* new ActivityReferenceIneligible({
          code: 'activity_reference_ineligible',
          reason: 'Activity owner must be an active Principal in the trusted tenant',
        });
      }
      const snapshot = yield* load();
      if (snapshot.revision !== expectedRevision) {
        return yield* new ActivityRevisionConflict({
          code: 'activity_revision_conflict',
          reason: 'Activities changed; refresh before another operation',
        });
      }
      const canonical = yield* verifier.verify(command, scope);
      const now = yield* DateTime.now;
      const change = yield* evolveRelationshipsState(snapshot.state, command, {
        now,
        partyRef: canonical.partyRef,
        resourceId,
        tenantId: scope.tenantId,
      });
      const state = yield* Schema.encodeEffect(RelationshipsStateSchema)(change.state).pipe(
        Effect.mapError(unavailable),
      );
      const rows = yield* transaction
        .update(relationshipsStates)
        .set({ revision: expectedRevision + 1, state, updatedAt: DateTime.toDateUtc(now) })
        .where(and(whereScope, eq(relationshipsStates.revision, expectedRevision)))
        .returning({ revision: relationshipsStates.revision })
        .pipe(Effect.mapError(unavailable));
      if (rows.length !== 1) {
        return yield* new ActivityRevisionConflict({
          code: 'activity_revision_conflict',
          reason: 'Activities changed; refresh before another operation',
        });
      }
      return { activity: change.activity, revision: expectedRevision + 1 };
    });
    const records = Effect.fn('Relationships.records')(function* records(request: RecordsRequest) {
      const snapshot = yield* load();
      const visible = yield* visibleActivities(snapshot.state.activities, scope);
      if (
        request.resourceId !== undefined &&
        !visible.some((activity) => activity.ref.resourceId === request.resourceId)
      ) {
        return yield* new ActivityPermissionDenied({
          code: 'activity_permission_denied',
          reason: 'Activity detail is forbidden or absent',
        });
      }
      const items = visible
        .filter(
          (activity) =>
            (request.resourceId === undefined || activity.ref.resourceId === request.resourceId) &&
            (request.partyId === undefined || activity.partyRef?.resourceId === request.partyId) &&
            (request.counterpartyId === undefined || activity.counterpartyRef?.resourceId === request.counterpartyId),
        )
        .toSorted((left, right) => DateTime.toEpochMillis(right.occurredAt) - DateTime.toEpochMillis(left.occurredAt));
      return {
        actorPrincipalRef: { principalId: scope.principalId, tenantId: scope.tenantId },
        canWrite: yield* contextGrant(scope, 'write_all'),
        emailObservations: visibleEmailObservations(snapshot.state.emailObservations, items),
        items,
        revision: snapshot.revision,
      };
    });
    return { apply, records };
  },
  Effect.mapError((cause) =>
    Object.defineProperty(
      new OperationContextUnavailable({
        code: 'operation_context_unavailable',
        reason: 'Owner-scoped services are temporarily unavailable',
      }),
      'cause',
      { enumerable: false, value: cause },
    ),
  ),
);
