// @generated by OntOS Codesmith Action v1
// @ontos-action-owner siampark.agreements
// @ontos-action-slug apply-command
import type { makeReferenceGatewayCredentialSource } from '@app/gateway-principal-verifier/server';
import type { Crypto } from 'effect';
import type { ActionHandlerContext, ActionServiceFactory } from '@app/core-runtime';
import { defineAction, defineTenantModuleEntrypoint, OperationContextUnavailable } from '@app/core-runtime';
import { Effect } from 'effect';

import {
  ApplyCommandErrorSchema,
  ApplyCommandPayloadSchema,
  ApplyCommandResultSchema,
  AgreementsConflict,
} from '../../shared/actions/apply-command.ts';
import type { ApplyCommandPayload } from '../../shared/actions/apply-command.ts';
import { persistenceService, transitionAgreements, makeAgreementsValidators } from '../services/persistence.service.ts';
import type { AgreementsValidators } from '../services/persistence.service.ts';

const OWNER_MODULE_KEY = 'siampark.agreements';

type Persistence = Effect.Success<ReturnType<typeof persistenceService>>;
export type ApplyCommandServices = Persistence & { readonly validators: AgreementsValidators };
const handleApplyCommand = Effect.fn('Agreements.applyCommand')(function* handleApplyCommand(
  payload: ApplyCommandPayload,
  context: ActionHandlerContext<Readonly<Record<string, never>>, ApplyCommandServices>,
) {
  const current = yield* context.services.load();
  if (current.revision !== payload.expectedRevision) {
    return yield* new AgreementsConflict({ code: 'agreements_conflict', reason: 'stale_revision' });
  }
  if (context.scope.legalEntityId === undefined) {
    return yield* new AgreementsConflict({ code: 'agreements_conflict', reason: 'legal_entity_required' });
  }
  yield* context.recordDataAccess({
    accessKind: 'read',
    queryHash: 'siampark.agreements.state.v1',
    resultCount: 1,
    servingModuleKey: OWNER_MODULE_KEY,
  });
  const changed = yield* transitionAgreements(
    current.snapshot,
    payload.command,
    { legalEntityId: context.scope.legalEntityId, tenantId: context.scope.tenantId },
    context.services.validators,
  );
  const revision = yield* context.services.save(changed.snapshot, payload.expectedRevision);
  return { resourceRef: changed.resourceRef, revision };
});

const makeServices: ActionServiceFactory<
  ApplyCommandServices,
  Effect.Services<ReturnType<typeof makeReferenceGatewayCredentialSource>> | Crypto.Crypto
> = (transaction, scope) =>
  Effect.all(
    {
      persistence: persistenceService(transaction, scope),
      validators: makeAgreementsValidators(scope),
    },
    { concurrency: 2 },
  ).pipe(
    Effect.map(({ persistence, validators }) => ({ ...persistence, validators })),
    Effect.mapError((cause) =>
      Object.defineProperty(
        new OperationContextUnavailable({
          code: 'operation_context_unavailable',
          reason: 'Owner services are temporarily unavailable',
        }),
        'cause',
        { configurable: false, enumerable: false, value: cause, writable: false },
      ),
    ),
    Effect.withSpan('Agreements.services'),
  );

export const applyCommandAction = defineAction(
  {
    accessEvidencePolicy: { captureMode: 'metadata_only', policyKey: 'siampark.agreements.apply-command.access.v1' },
    actionKey: 'siampark.agreements.apply-command',
    auditProfile: 'standard',
    domainErrorSchema: ApplyCommandErrorSchema,
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'siampark.agreements.apply-command',
      moduleKey: OWNER_MODULE_KEY,
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'required',
    owningModuleKey: OWNER_MODULE_KEY,
    payloadSchema: ApplyCommandPayloadSchema,
    policies: [],
    resultSchema: ApplyCommandResultSchema,
    schemaVersion: '1',
  },
  handleApplyCommand,
  makeServices,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
